### ISSUE TITLE
Example's README

### ISSUE THREAD

**Issue by paul-hammant** [jonsamwell/flutter_gherkin#1]
Re: https://github.com/jonsamwell/flutter_gherkin/tree/master/example

Any chance this can be changed from the default generated README ("For help getting started with Flutter, view our online documentation.") and have something that shows the reader how to run the supplied example?

Also: would need a link and a H1 in the root README :)

Why?  Some of us are allergic to tutorials, and can only grasp a 'new' technologies from tight and complete examples.  You have that example, but the how-to-run-it info is missing. 

Great work, by the way.

**Comment by jonsamwell** [comment]
@paul-hammant Great idea!  I'll sort this out asap.

**Comment by jonsamwell** [comment]
@paul-hammant updated https://github.com/jonsamwell/flutter_gherkin/blob/master/example/README.md

Let me know if the steps to run are adequate.

Thanks again.

**Comment by paul-hammant** [comment]
Cool, I followed the advice:

```
$ dart test_driver/app_test.dart
Starting Flutter app under test 'test_driver/app.dart', this might take a few moments
$
```

I didn't see any output in the console, nor could see if there were a place in the file system where results would go.... Advice?

**Comment by jonsamwell** [comment]
Hi Paul,

Try including the standard out reporter (see code below) which logs all messages from the runner to the standard output (console in most cases).  By default in the example it just uses the progress reporter which only logs the result of each scenario / step.  If you weren't seeing any output at all I bet it can't find any features to run.  I fixed an issue with the GLOB pattern (should be `Glob(r"test_driver/features/**.feature")`) in the example so I suggest you do a get on the repo and it should be resolved and now tell you if it can't find any feature files to run.

```dart
import 'dart:async';
import 'package:glob/glob.dart';
import 'package:flutter_gherkin/flutter_gherkin.dart';
import 'hooks/hook_example.dart';
import 'steps/colour_parameter.dart';
import 'steps/given_I_pick_a_colour_step.dart';
import 'steps/tap_button_n_times_step.dart';

Future<void> main() {
  final config = FlutterTestConfiguration()
    ..features = [Glob(r"test_driver/features/**.feature")]
    ..reporters = [
      ProgressReporter(),
      TestRunSummaryReporter(),
      StdoutReporter(MessageLevel.warning)
    ] // you can include the "StdoutReporter()" without the message level parameter for verbose log information
    ..hooks = [HookExample()]
    ..stepDefinitions = [TapButtonNTimesStep(), GivenIPickAColour()]
    ..customStepParameterDefinitions = [ColourParameter()]
    ..restartAppBetweenScenarios = true
    ..targetAppPath = "test_driver/app.dart"
    // ..tagExpression = "@smoke" // uncomment to see an example of running scenarios based on tag expressions
    ..exitAfterTestRun = true; // set to false if debugging to exit cleanly
  return GherkinRunner().execute(config);
}
```

Regarding outputting test results to a file system.  This would be done via a reporter and would be fairly trivial to implement.  Feel free to submit a PR or please provide a link to the file format and structure you would like created.  I have plans to add more reporters like a TeamCity one and various other so any help would be very much appreciated.

**Comment by jonsamwell** [comment]
@paul-hammant glad it is all working.  Yes, in theory if should work with widget test although I haven't tried it.  I'll try and get an example of a widget test added to the docs.
