### ISSUE TITLE
Running Gherkin code within a Step definition

### ISSUE THREAD

**Issue by Holloweye** [jonsamwell/flutter_gherkin#10]
Is there a way to run Gherkin code within a step definition?

For example:

```dart
class GivenOnboardingScreenStep extends GivenWithWorld<FlutterWorld> 
{
  @override
  Future<void> executeStep() async
  {
      run("
      Given I am on Login screen
      Then entered valid credentials
      And pressed login button
      ");
  }

  @override
  RegExp get pattern => RegExp(r"I am on Onboarding screen");
}
```

With Calabash it was possible to run steps within a step definition. I found that a very useful feature when writing pre-conditions. It cut down quite much on the number of repeating steps.

For example lets say we have the following interface:
`Welcome screen` -> `Login screen` -> `Onboarding screen`.

To open the onboarding screen right now, I have to do something like this.
```gherkin
Feature: Onboarding

Scenario: Skip onboarding
  Given I am on Welcome screen
  And pressed login button
  And I entered valid credentials
  And pressed login button
  When I press skip button
  Then I should see Main screen
```

I could put that in the __background__ for the feature. But it does not solve the issue that I might need to repeat myself with multiple features within the same screen.

But if I were able to run Gherkin code within a step definition I can do a setup like this:

```gherkin
Feature: Onboarding

Scenario: Skip onboarding
  Given I am on Onboarding screen
  When I press skip button
  Then I should see Main screen
```

```dart
class GivenOnboardingScreenStep extends GivenWithWorld<FlutterWorld> 
{
  @override
  Future<void> executeStep() async
  {
      run("
      Given I am on Login screen
      Then entered valid credentials
      And pressed login button
      ");
  }

  @override
  RegExp get pattern => RegExp(r"I am on Onboarding screen");
}

class GivenLoginScreenStep extends GivenWithWorld<FlutterWorld> 
{
  @override
  Future<void> executeStep() async
  {
      run("
      Given I am on Welcome screen
      Then pressed login button
      ");
  }

  @override
  RegExp get pattern => RegExp(r"I am on Login screen");
}

class GivenWelcomeScreenStep extends GivenWithWorld<FlutterWorld> 
{
  @override
  Future<void> executeStep() async
  {
      final locator = find.byValueKey("welcome message");
      await world.driver.isPresent(locator);
  }

  @override
  RegExp get pattern => RegExp(r"I am on Welcome screen");
}
```

Now I can now easily reuse these steps defintions. It's also very easy to add new "Given I am on x screen" step definitions, as they can reference existing step definitions.

Maybe there is a better way of doing what I am trying to accomplish?

**Comment by jonsamwell** [comment]
Hi @Holloweye I can see the benefit of this.  Implementing it would be quiet hard I fear.

Could you not re-use the other step definitions or code rather than execute another text based child scenario?  What might be nice is the ability to execute a step class from within a step.  This might solve the problem and be far easier to implement.

For example: 

```
class GivenLoginScreenStep extends GivenWithWorld<FlutterWorld> 
{
  @override
  Future<void> executeStep() async
  {
      await executeChildStep(new GivenWelcomeScreenStep(), args...);
      await executeChildStep(new GivenLoginButtonIsPressed(), args...);
     // step code here...
  }

  @override
  RegExp get pattern => RegExp(r"I am on Login screen");
}

class GivenWelcomeScreenStep extends GivenWithWorld<FlutterWorld> 
{
  @override
  Future<void> executeStep() async
  {
      final locator = find.byValueKey("welcome message");
      await world.driver.isPresent(locator);
  }

  @override
  RegExp get pattern => RegExp(r"I am on Welcome screen");
}
```

It looks like the cucumber team do not support running nested textual steps, favouring code reuse https://docs.cucumber.io/guides/anti-patterns/#support-for-conjunction-steps

Let me have a think and get back to you.

**Comment by Holloweye** [comment]
@jonsamwell 

Yeah right now I added it programmatically:
```dart
class OnLoginStep extends GivenWithWorld<FlutterWorld>
{
  OnLoginStep()
      : super(StepDefinitionConfiguration()
    ..timeout = Duration(seconds: 10));

  @override
  Future<void> executeStep()
  async
  {
    await OnLoginStep.perform(world.driver);
  }

  static Future<void> perform(FlutterDriver driver)
  async
  {
    await OnWelcomeStep.perform(driver);
    await PressButtonStep.perform(driver, "Login");
    await OnScreenStep.perform(driver, "Login"); // Checks that login screen is showing.
  }

  @override
  RegExp get pattern
  => RegExp(r"I am on Login screen");
}

class OnWelcomeStep extends GivenWithWorld<FlutterWorld>
{
  OnWizardStep()
      : super(StepDefinitionConfiguration()
    ..timeout = Duration(seconds: 10));

  @override
  Future<void> executeStep()
  async
  {
    await OnWelcomeStep.perform(world.driver);
  }

  static Future<void> perform(FlutterDriver driver)
  async
  {
    await OnScreenStep.perform(driver, "Welcome"); // Checks that welcome screen is showing.
  }

  @override
  RegExp get pattern
  => RegExp(r"I am on Welcome screen");
}
```

I added so that each step definition has a static method `perform` that other step definitions can call. It works reasonable well. Although writing it in Gherkin would add much more flexibility and less boilerplate in the step definitions.

**Comment by jonsamwell** [comment]
I'll see what I can do about running a basic step class from within a step so that you don't have to have static methods etc.

**Comment by jonsamwell** [comment]
Closing from lack of activity feel free to re-open
