### ISSUE TITLE
Question:  How can I click a position (x,y)?

### ISSUE THREAD

**Issue by bartonhammond** [jonsamwell/flutter_gherkin#105]
I have ImagePicker - how can I pick one of the images?

![Screen Shot 2020-12-18 at 2 45 50 PM](https://user-images.githubusercontent.com/1282364/102659887-c0e65e00-413f-11eb-9057-1b13043971c7.png)

**Comment by bartonhammond** [comment]
I mocked it out...

**Comment by jonsamwell** [comment]
@bartonhammond yes this is a known issue with the flutter driver as you are crossing the application boundary into the native device so need to somehow use native commands to picture the image (as you are no longer in the flutter app).  I have done something similar on Android pushing the flutter app to the background and bringing it back into focus to trigger a pin screen.

```
import 'dart:io';

import 'package:gherkin/gherkin.dart';

class PushAppToBackgroundAndBringToForeground extends Given {
  PushAppToBackgroundAndBringToForeground() : super();

  @override
  Future<void> executeStep() async {
    // adb -s "emulator-5556" shell input keyevent 187
    // press home button then double press app selector to select previous app
    await Process.start(
      "adb",
      ["shell", "input", "keyevent", "3"],
      runInShell: true,
    );
    await Future<void>.delayed(const Duration(seconds: 3));
    await Process.start(
      "adb",
      ["shell", "input", "keyevent", "187"],
      runInShell: true,
    );
    await Future<void>.delayed(const Duration(seconds: 3));
    await Process.start(
      "adb",
      ["shell", "input", "keyevent", "187"],
      runInShell: true,
    );
    await Future<void>.delayed(const Duration(seconds: 5));
  }

  @override
  RegExp get pattern => RegExp(
      r'I push the app to the background then bring it to the foreground');
}
```

Although I am not sure how to use native ios simulator command to tap the screen.
