### ISSUE TITLE
Is it possible to select a scenario by condition?

### ISSUE THREAD

**Issue by Drrrybi** [jonsamwell/flutter_gherkin#112]
Is it possible to specify the " if " condition to run a specific feature scenario? 
For example:

Future<void> executeStep() async {
    final SerializableFinder locator = find.byValueKey('Home_screen');
    await FlutterDriverUtils.isPresent(world.driver, locator);
  }

If (home_screen isPresent) you are logged in to the app - run 2_scenario.feature 
(in this case, the scenarios are run when the user is logged in with their account)

If you are logged out to the app - run 1_scenario.feature
(in this case, the scenarios are run checking the health of the login, signup screens)

Several developers perform automation tests. 
Someone runs an application where the account is logged in, where it is not.

Can this be implemented?

**Comment by jonsamwell** [comment]
I think this goes against the fundamental concept that a test should not rely on any state and be atomic.

When I have a test that needs say the use to be logged in I add background steps to log the user in before the test is performed.

**Comment by Drrrybi** [comment]
Thank you 👍

**Comment by jonsamwell** [comment]
If you migrate to the integration_test way of doing things you could put your app in the state you want before the test is run see 
https://github.com/jonsamwell/flutter_gherkin/issues/101 and the branch https://github.com/jonsamwell/flutter_gherkin/tree/integration_test__package_support

I'll be making this the standard way to do tests in the lib in the coming month
