### ISSUE TITLE
How can I press Enter on the system keyboard?

### ISSUE THREAD

**Issue by Drrrybi** [jonsamwell/flutter_gherkin#117]
In the application to which I am writing the test. The search starts after pressing enter on the keyboard. Please tell me how this can be implemented?
![photo_2021-02-17_03-23-24](https://user-images.githubusercontent.com/49107326/108123159-a42ebe00-70cf-11eb-8677-2510aedcf2b9.jpg)

The search is launched only through the system keyboard

**Comment by jonsamwell** [comment]
Sorry this is not a place for implementation help on tests, I suggest you use StackOverflow for that.

However, can you just not send a enter character?

**Comment by Drrrybi** [comment]
@jonsamwell https://stackoverflow.com/questions/66825911/how-can-i-press-enter-on-the-system-keyboard-using-flutter-gherkin
