### ISSUE TITLE
[Feature Request] Force end 1 step in a scenario

### ISSUE THREAD

**Issue by harrytran998** [jonsamwell/flutter_gherkin#120]
In my case, I want to force a step on my scenario. Because my widget has a Timer countdown, and the scenario must wait for the timer to end up --> run the next scenario! Thanks, you <3. 

Here it's the log message when waiting for the timer to end up.
```bash
VMServiceFlutterDriver: waitForCondition message is taking a long time to complete...
```

![image](https://user-images.githubusercontent.com/24296018/110108395-b8b4cb00-7dde-11eb-8afd-1b459a9cc12f.png)

**Comment by jonsamwell** [comment]
I'm not sure what you want here?  Could you provide a better example and some code of what you are trying to achieve

**Comment by harrytran998** [comment]
Sorry about this issue, actually this relative to the timer problem. I fixed!
