### ISSUE TITLE
Migrating to null safety?

### ISSUE THREAD

**Issue by azcama** [jonsamwell/flutter_gherkin#121]
Hi @jonsamwell, thanks for sharing this library.
I would like to ask you if you have considered the migration to null safety with the new Flutter 2. It would be great to have this library updated in order to use it in some web Flutter projects.
In case of a positive answer, I really appreciate if you can give us an approximate date of release. I'm examining this library as a great candidate for my Flutter testing projects.
Thanks in advance!

**Comment by jonsamwell** [comment]
It'll probably be in the next few months.  I am working on the converting the base gherkin library to null safety and this library to use `WidgetTester` instead of the now deprecated flutter driver.  There just isn't enough hours in the day.  Feel free to contribute a PR.

**Comment by thanh-vo-opun-ai** [comment]
Hi @jonsamwell ,
How about progress of migrating this library to null safety?

**Comment by steadycoding** [comment]
@jonsamwell I'm interested in contributing a PR to migrate flutter_gherkin to null safety. Have you started on this task?

**Comment by jonsamwell** [comment]
Hoping to get this package migrated to null safety and publish the branch using the `integration_test` package next week,

**Comment by SomeCodingUser** [comment]
@jonsamwell Any way to help you migrating to null safety?

**Comment by jonsamwell** [comment]
Finally migrated!
