### ISSUE TITLE
Update dependency on glob to 2.0 or higher

### ISSUE THREAD

**Issue by rmargolinross** [jonsamwell/flutter_gherkin#124]
I am using this package as well as injectable_generator. There is a dependency conflict due to both of them referencing glob, but this packages references an older version. ^1.1.7.

This work may be done eventually when you convert the package to use null safety, but it might be nice to get this step done earlier.

**Comment by jonsamwell** [comment]
@rmargolinross thank for this, you are correct as part of the null-safety migration this will be updated.  Hoping to get that done next week.

**Comment by jonsamwell** [comment]
The dependencies on Glob can been removed in the latest release
