### ISSUE TITLE
Fails to update to 3.0.0-rc.1 

### ISSUE THREAD

**Issue by Gayatri-N** [jonsamwell/flutter_gherkin#133]
Hello,

I am trying to add `flutter_gherkin: ^3.0.0-rc.1` with `integration_test: ^1.0.2+3`
however `flutter pub get` gives below error:

```
Because flutter_gherkin >=3.0.0-rc.1 depends on integration_test from sdk and home_app depends on integration_test from hosted, flutter_gherkin >=3.0.0-rc.1 is forbidden.
So, because <app_name> depends on flutter_gherkin ^3.0.0-rc.1, version solving failed.
Running "flutter pub get" in <app_name>...                                
pub get failed (1; So, because <app_name> depends on flutter_gherkin ^3.0.0-rc.1, version solving failed.)
```

When I try to add it using the command `flutter pub add flutter_gherkin`, it adds a version 2.0.0 successfully.
I am not able to figure out what is wrong here. 
Can anyone help me to solve this issue, or guide the correct path?

Thank you!

**Comment by jonsamwell** [comment]
Could you post your pubspec.yaml.  There is no specific version requirement on `integration_test` I think you might be adding it wrong in your pubspec.yaml you shouldn't need to specify a version number as it is now part of the sdk?

**Comment by jonsamwell** [comment]
Closing due to no response.  Feel free to reopen if you are still encountering this issue
