### ISSUE TITLE
Datatable to JSON

### ISSUE THREAD

**Issue by fadhlimaulidri** [jonsamwell/flutter_gherkin#136]
i have table like below
```
| KMSY | Louis Armstrong New Orleans International Airport |
| KSFO | San Francisco International Airport               |
| KSEA | Seattle–Tacoma International Airport              |
| KJFK | John F. Kennedy International Airport             |
```
can i get JSON like below?
```
{
  "KMSY": "Louis Armstrong New Orleans International Airport",
  "KSFO": "San Francisco International Airport",
  "KSEA": "Seattle–Tacoma International Airport",
  "KJFK": "John F. Kennedy International Airport"
}
```

my question reference from https://github.com/cucumber/common/tree/main/datatable

i use cucumber in ruby too. when i have datatable like a define before, i can get json easy use
```
body = dataTable.rows_hash.to_json
```
and then we can get the output like JSON as before

**Comment by jonsamwell** [comment]
@fadhlimaulidri you can use `dataTable.asMap()` which gives back a `Map<String, dynamic>` then you can use `json.encode` if yo require.  Please see the docs on the table https://github.com/jonsamwell/flutter_gherkin#data-tables

**Comment by fadhlimaulidri** [comment]
i have try use like that
```
      print(dataTable);
      final Map<String, dynamic> data = dataTable.asMap().elementAt(0);
      print(data);
```
i have get output `data` like below
```
Instance of 'GherkinTable'
{KMSY: KSFO, Louis Armstrong New Orleans International Airport: San Francisco International Airport}

**Comment by fadhlimaulidri** [comment]
@jonsamwell have you try yet?

**Comment by jonsamwell** [comment]
@fadhlimaulidri the tests work as expected see

https://github.com/jonsamwell/dart_gherkin/blob/master/test/gherkin/runnables/table_test.dart#L196

See the actual code also
