### ISSUE TITLE
run dart app_test.dart but test not run 

### ISSUE THREAD

**Issue by Nut41tank** [jonsamwell/flutter_gherkin#138]
### try to run test but look like it not run
**flutter_gherkin** version 2.0

Hello, I follow your documentation and try to set up my own test
but When I run it got 
```
Starting Flutter app under test 'test_driver/app.dart', this might take a few moments
0 scenario ()
0 step ()
0:00:00.001000
Terminating Flutter app under test
```
### **this is my set up**

**config - app_test.dart**

![image](https://user-images.githubusercontent.com/26061580/125259388-74f04600-e329-11eb-8549-bf9d551c222d.png)

**steps**

![image](https://user-images.githubusercontent.com/26061580/125259447-83d6f880-e329-11eb-90f4-934ef411fd5e.png)

**page model**

![image](https://user-images.githubusercontent.com/26061580/125259559-9fda9a00-e329-11eb-8bb5-428bd3ccdcf1.png)

not should what happened
please help

**Comment by jonsamwell** [comment]
You could try modifiying the `features` regex so that is matches the path to your feature files

**Comment by Nut41tank** [comment]
OK thank you, resolve this problem by changing from `Regex` to `Glob`

**Comment by jonsamwell** [comment]
Great!
