### ISSUE TITLE
VMServiceFlutterDriver It is taking an unusually long time to connect to the VM...

### ISSUE THREAD

**Issue by Boomspip** [jonsamwell/flutter_gherkin#139]
i was running flutter_gherkin example file with "dart app_test.dart" command as in readme file, and i got this message "VMServiceFlutterDriver It is taking an unusually long time to connect to the VM...". i wait for an hour but nothing happened. pls help.

**Comment by Boomspip** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1052], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.58.0)
[√] Connected device (3 available)

**Comment by jonsamwell** [comment]
I've seen this before (https://github.com/flutter/flutter/issues/50898) but never had a solution.  It has always been intermittent and not related to this library.  Try searching stackoverflow for some possible solutions.

You could try using an x86 version of the Android emulator

Sorry I could not be of more help
