### ISSUE TITLE
Run test but got missing provider 

### ISSUE THREAD

**Issue by Nut41tank** [jonsamwell/flutter_gherkin#140]
**flutter_gherkin** version 2.0

Hello, I try to run but got this issue related to provider package. Do I need to include specific provider for test with _flutter_gherkin_

![image](https://user-images.githubusercontent.com/26061580/125431446-f28e5f3d-cc68-404f-989e-713fd80cdec1.png)

Thank you

**Comment by jonsamwell** [comment]
No the v2 package will not affect you application in anyway.  This must be a problem with your application I would imagine

**Comment by Nut41tank** [comment]
I see but  when I run main.dart. it work just fine as expected 
not sure which part should look into first ?

**Comment by jonsamwell** [comment]
Are you calling `enableFlutterDriverExtension();` before `runApp()`?

**Comment by Nut41tank** [comment]
![image](https://user-images.githubusercontent.com/26061580/125434725-1ff6fd4f-0fb3-4a22-9bf6-c9d0967361c3.png)
already

**Comment by jonsamwell** [comment]
Does it work if you just run main without running flutter_gherkin?

**Comment by Nut41tank** [comment]
Yes it work but when run with dart app_test.dart it show error on above

**Comment by jonsamwell** [comment]
To be honest if you are just starting out with this I would use the V3 package which uses intergration_test as it recommended way of doing it now and I'll soon be push that version as the default way to do things.

https://pub.dev/packages/flutter_gherkin/versions/3.0.0-rc.2

It'll give you a better idea of what is going on

**Comment by jonsamwell** [comment]
Great.  If you are still having trouble with V2 if you could produce a sample app with the problem I can see what is going on

**Comment by jonsamwell** [comment]
Closed due to no reproducible example
