### ISSUE TITLE
How to generate the html report with the pre-release 3.0.0-rc2 ?

### ISSUE THREAD

**Issue by Stephane99** [jonsamwell/flutter_gherkin#141]
Hi,
I managed to use **simple_cucumber_html_reporter** and **multiple_cucumber_html_reporter** with **Flutter driver** and **flutter_gherkin** a few months ago.
Now I have switched to **integration_test** with **fluter_gherkin 3.0.0.-rc2**.

### simple_cucumber_html_reporter / multiple_cucumber_html_reporter
Firstly, when I try to generate the gherkin report with the simple or multiple reporter, I get this error:
`TypeError: jsonFile.readFileSync(...).map is not a function`
(e.g. simple-cucumber-html-reporter\lib\collect-jsons.js:22).

The json file is in a string starting like this:
`{
"gherkin_reports": "[[{\"description\":..."
}`

After converted the string to this array `[[{"description":...` I can generate the html report but some items are not taken into account by the report such as the feature name and the scenario name.

### cucumber_html_report
Secondly, when I try to generate the report with **cucumber_html_reporter** like indicated in the **flutter_gherkin** documentation, I get this error:
'TypeError: suite.features.forEach is not a function'
(e.g. cucumber-html-reporter\lib\hierarchyReporter.js:22)

### Versions installed:
simple-cucumber-html-reporter: **2.0.2**
multiple-cucumber-html-reporter: **1.18.0**
cucumber-html-reporter: **5.4.0**

### Json file
[Example of a generated json file](https://gist.github.com/Stephane99/fe408ef5724abb15b99c04cab9bc3f0e "Generated json file")

**Comment by jonsamwell** [comment]
I think this related to #128 

I take a look this weekend.  Thanks for reporting

**Comment by Stephane99** [comment]
Hello, has there been any progress on this subject?

**Comment by jonsamwell** [comment]
Fixed in 3.0.0-rc.3

See https://github.com/jonsamwell/flutter_gherkin/blob/3.0.0-rc.3/example_with_integration_test/generate-cucumber-html-report.js on how to generate html report from output
