### ISSUE TITLE
Screenshoot can't be work at Hooks

### ISSUE THREAD

**Issue by fadhlimaulidri** [jonsamwell/flutter_gherkin#143]
hi,
i try to take a screenshoot if any failed or pass step.

but there isn't image receive in the folder

this is my code

test_driver/app_test.dart
```
import 'dart:async';
import 'package:flutter_gherkin/flutter_gherkin.dart';
import 'package:gherkin/gherkin.dart';
import 'package:glob/glob.dart';
import 'steps/initial_state_of_app.dart';

Future<void> main() {
  final config = FlutterTestConfiguration()
    ..features = [Glob(r"test_driver/features/**.feature")]
    ..reporters = [
      ProgressReporter(),
      TestRunSummaryReporter(),
      JsonReporter(path: './report.json')
    ] // you can include the "StdoutReporter()" without the message level parameter for verbose log information
    ..hooks = [
      AttachScreenshotOnFailedStepHook()
    ]
    ..stepDefinitions = [
      InitialStateOfApp()
    //, ISeeValue(), ClickSubtract()
    ]
    ..restartAppBetweenScenarios = true
    ..targetAppPath = "test_driver/bdd.dart";
    // ..tagExpression = "@smoke" // uncomment to see an example of running scenarios based on tag expressions
    // ..exitAfterTestRun = true; // set to false if debugging to exit cleanly
  return GherkinRunner().execute(config);
}
```

test_driver/hooks/attach_screenshot_on_failed_step_hook.dart
```
import 'dart:convert';

import 'package:gherkin/gherkin.dart';
import 'package:meta/meta.dart';

class AttachScreenshotOnFailedStepHook extends Hook {
  @override
  Future<void> onAfterStep(
    World world,
    String step,
    StepResult stepResult,
  ) async {
    if (stepResult.result == StepExecutionResult.fail ||
        stepResult.result == StepExecutionResult.error ||
        stepResult.result == StepExecutionResult.timeout) {
      try {
        final screenshotData = await takeScreenshot(world);
        world.attach(screenshotData, 'image/png', step);
      } catch (e, st) {
        world.attach('Failed to take screenshot\n$e\n$st', 'text/plain', step);
      }
    }else{
      final screenshotData = await takeScreenshot(world);
      world.attach(screenshotData, 'image/png', step);
    }
  }

  @protected
  Future<String> takeScreenshot(World world) async {
    final bytes = await (world as FlutterWorld).driver!.screenshot();

    return base64Encode(bytes);
  }
}

```

for the complete code here
https://github.com/fadhlimaulidri/flutter_apps/tree/cucumber_version_1.0.1/test_driver

to run
`flutter drive --target=test_driver/bdd.dart`

**Comment by jonsamwell** [comment]
The class `AttachScreenshotOnFailedStepHook` does not save the image to a folder it attached it to the report.  If you want to save it to a folder add some code to do this  after the `await takeScreenshot(world);` code.

**Comment by fadhlimaulidri** [comment]
yes, my expected isn't attach image to report,  but just generate image if step passed or failed. somehow the image can't generate. i have use `await takeScreenshot(world);` but no happen at the hooks
https://github.com/fadhlimaulidri/flutter_apps/blob/cucumber_version_1.0.1/test_driver/hooks/attach_screenshot_on_failed_step_hook.dart#L18

**Comment by jonsamwell** [comment]
Sorry I am not sure what you mean?

Is the code `await takeScreenshot(world);` throwing an exception?

**Comment by fadhlimaulidri** [comment]
nothing error
<img width="962" alt="Screenshot 2021-07-27 at 12 09 09" src="https://user-images.githubusercontent.com/11204909/127098842-28105485-1577-4221-8c5d-39f04cc49b47.png">

i think the hooks isn't called

**Comment by jonsamwell** [comment]
It would be called it just does not print anything or save the image to disk

**Comment by fadhlimaulidri** [comment]
have you seen at else section? i do same action

**Comment by fadhlimaulidri** [comment]
```
import 'dart:convert';

import 'package:gherkin/gherkin.dart';
import 'package:meta/meta.dart';

class AttachScreenshotOnFailedStepHook extends Hook {
  @override
  Future<void> onAfterStep(
    World world,
    String step,
    StepResult stepResult,
  ) async {
    print("***************************************");
  }

  @protected
  Future<String> takeScreenshot(World world) async {
    final bytes = await (world as FlutterWorld).driver!.screenshot();

    return base64Encode(bytes);
  }
}
```

i try code like that, there's no print '******'

**Comment by jonsamwell** [comment]
It won't print to the console as it is running in a different process than the console being logged (I think).  Try debugging it.  I'm confident this works as expected.  

It would be easier and more future proof (as well as really easy debugging) to use the latest RC version of the library as this generates the code and is easier to run and debug https://pub.dev/packages/flutter_gherkin/versions/3.0.0-rc.2

**Comment by fadhlimaulidri** [comment]
i find why can't printed, thats because there in class `AttachScreenshotOnFailedStepHook` in the package, not call to my own file
<img width="712" alt="Screenshot 2021-07-27 at 13 39 57" src="https://user-images.githubusercontent.com/11204909/127107811-8e2f4b26-8962-4865-b93c-66914dd2cb79.png">
 
so i rename the file, and now can print **** as expected

ok. next continue to screenshot hooks.
in file hooks, i use like below
test_driver/hooks/screenshot_on_failed_step_hook.dart
```
import 'dart:convert';

import 'package:gherkin/gherkin.dart';
import 'package:meta/meta.dart';

class ScreenshotOnFailedStepHook extends Hook {
  @override
  Future<void> onAfterStep(
    World world,
    String step,
    StepResult stepResult,
  ) async {
    if (stepResult.result == StepExecutionResult.fail ||
        stepResult.result == StepExecutionResult.error ||
        stepResult.result == StepExecutionResult.timeout) {
      try {
        final screenshotData = await takeScreenshot(world);
        world.attach(screenshotData, 'image/png', step);
      } catch (e, st) {
        world.attach('Failed to take screenshot\n$e\n$st', 'text/plain', step);
      }
    }else{
      final screenshotData = await takeScreenshot(world);
      world.attach(screenshotData, 'image/png', step);
    }
  }

  @protected
  Future<String> takeScreenshot(World world) async {
    final bytes = await (world as FlutterWorld).driver!.screenshot();

    return base64Encode(bytes);
  }
}
```
but show error like this
<img width="906" alt="Screenshot 2021-07-27 at 13 57 05" src="https://user-images.githubusercontent.com/11204909/127110000-d661fd3b-a001-4852-9e1a-4cb5db2f4387.png">

any idea @jonsamwell ?

**Comment by jonsamwell** [comment]
FlutterWorld is not in that package.  You will need to not modify the code directly and create your own class

**Comment by fadhlimaulidri** [comment]
do you mean i should use class `AttachScreenshotOnFailedStepHook`?

**Comment by jonsamwell** [comment]
I'm not really sure what you are trying to achieve here? Modifying a class in the library is not good practice.  If you want a step to just capture a screenshot after a step you will have to write your own hook class

**Comment by fadhlimaulidri** [comment]
i just want get a screenshot when the step is failed

**Comment by jonsamwell** [comment]
WARNING: Code not tested

```
import 'dart:convert';

import 'package:gherkin/gherkin.dart';
import 'package:meta/meta.dart';

class CustomDiskScreenshotOnFailedStepHook extends Hook {
  @override
  Future<void> onAfterStep(
    World world,
    String step,
    StepResult stepResult,
  ) async {
    if (stepResult.result == StepExecutionResult.fail ||
        stepResult.result == StepExecutionResult.error ||
        stepResult.result == StepExecutionResult.timeout) {
      try {
         await takeAndSaveScreenshotToDisk(world);
      } catch (e, st) {
        world.attach('Failed to take screenshot\n$e\n$st', 'text/plain', step);
      }
    }else{
      final screenshotData = await takeScreenshot(world);
      world.attach(screenshotData, 'image/png', step);
    }
  }

  @protected
  Future<void> takeAndSaveScreenshotToDisk(World world) async {
    final bytes = await (world as FlutterWorld).driver!.screenshot();

    final buffer = data.buffer;
  await new File(path).writeAsBytes(
      buffer.asUint8List(data.offsetInBytes, data.lengthInBytes,
    ),
   );
  }
}
```

**Comment by fadhlimaulidri** [comment]
i have try your code but i get error like below

<img width="960" alt="Screenshot 2021-07-27 at 17 25 18" src="https://user-images.githubusercontent.com/11204909/127138948-96458114-05a9-4647-acbc-e60908691c57.png">

**Comment by jonsamwell** [comment]
Post your code to github and will have a look over the next few days.

**Comment by fadhlimaulidri** [comment]
this is my code https://github.com/fadhlimaulidri/flutter_apps/pull/3/files

**Comment by fadhlimaulidri** [comment]
hi @jonsamwell . i have get why. i think it will generate file such png or jpeg, but the image in the form of code from json. so my code run as expected. thanks for this library and thanks also for your response

**Comment by jonsamwell** [comment]
Great glad you figured it out!
