### ISSUE TITLE
[QUESTION] Is there full support to the integration_test already?

### ISSUE THREAD

**Issue by brenoasm** [jonsamwell/flutter_gherkin#144]
Hi, I'm doing some research so we can use integration tests. I've managed to get the project setup to work using the integration_test package, but now I need to do a custom Step and there is no example on how to do that with the new structure, is there a way to do it? Thanks in advance.

**Comment by jonsamwell** [comment]
Hi @brenoasm yes the integration_test implementation has full support and I am using it on two large and complex projects.  I'll soon be releasing the rc and a major version (I just have to find time to do new documentation).

In terms of creating a custom step it is the same as the way currently documented.  See https://github.com/jonsamwell/flutter_gherkin#steps-definitions

**Comment by brenoasm** [comment]
Thanks for the answer! How to access the integration_test methods? Like WidgetTester (like from context accessing the flutter_driver)?

**Comment by jonsamwell** [comment]
See https://github.com/jonsamwell/flutter_gherkin/blob/integration_test__package_support/example_with_integration_test/integration_test/gherkin/steps/expect_todos_step.dart#L6

```
final someCustomStep = then1<num, FlutterWidgetTesterWorld>(
  'I expect the todo list',
  (val, context) async {
    // get the parent list
    final listTileFinder = context.world.appDriver.findBy(
      ListTile,
      FindType.type,
    );

  // access the WidgetTesterDirectly using rawAppDriver
  await context.world.rawAppDriver.pumpAndSettle();

// see https://github.com/jonsamwell/flutter_gherkin/blob/integration_test__package_support/lib/src/flutter/world/flutter_world.dart#L37
  },
  configuration: StepDefinitionConfiguration()
    ..timeout = const Duration(seconds: 5),
);
```
