### ISSUE TITLE
Run the application that has been built (existing app)

### ISSUE THREAD

**Issue by fadhlimaulidri** [jonsamwell/flutter_gherkin#146]
i have 2 stage in pipline, build app and run automation. i have build the application and passed. can i run automation with the app has been built?

**Comment by jonsamwell** [comment]
If you are using the intergration_test RC version of this package no as that executes within the app.

If you are using the Flutter driver version you would have to build the app with the `enableFlutterDriverExtension()` call in which would be detrimental to the apps performance when released.

So overall you cannot unfortunately

**Comment by fadhlimaulidri** [comment]
oke thank you @jonsamwell
