### ISSUE TITLE
what is different create new class with use step generic?

### ISSUE THREAD

**Issue by fadhlimaulidri** [jonsamwell/flutter_gherkin#149]
what do you recomended?

if step defenition is not found, can i get step def in terminal in the form of step generic?
<img width="930" alt="Screenshot 2021-09-03 at 17 40 38" src="https://user-images.githubusercontent.com/11204909/131992862-47e6e7d9-b277-446a-a1a3-622d23647e80.png">

**Comment by jonsamwell** [comment]
Hi the class definition to create a step and the function declaration are exactly the same.  I recommend choosing one that fits your use cases best.

```
import 'package:flutter_driver/flutter_driver.dart';
import 'package:flutter_gherkin/flutter_gherkin.dart';
import 'package:gherkin/gherkin.dart';

StepDefinitionGeneric TapButtonNTimesStep() {
  return when2<String, int, FlutterWorld>(
    'I tap the {string} button {int} times',
    (key, count, context) async {
      final locator = find.byValueKey(key);
      for (var i = 0; i < count; i += 1) {
        await FlutterDriverUtils.tap(context.world.driver, locator);
      }
    },
  );
}
```

**Comment by fadhlimaulidri** [comment]
any plan to add step generic at not found step definition?

**Comment by jonsamwell** [comment]
What do you mean? Could you explain a bit further?

**Comment by fadhlimaulidri** [comment]
for example we have scenario in example.feature. and then we run. but step defenition of our step have yet we create. for now it give step definition in the form of class definition as the screenshot. any plan to change class definition to step generic / (or) add step generic at there?
