### ISSUE TITLE
Cucumber steps not working on window

### ISSUE THREAD

**Issue by skumar11pk** [jonsamwell/flutter_gherkin#153]
I am executing feature file on mac that is working fine, but same code not working on window, showing 0 scenario, 0 steps..

PS D:\flutterautomation\test_driver> dart app_test.dart 'ws://127.0.0.1:49898/U2WgzMRMI2w=/ws'
Connecting to running Flutter app under test at 'ws://127.0.0.1:49898/U2WgzMRMI2w=/ws', this might take a few moments
before run hook

0 scenario ()
0 step ()
0:00:00.002000
after run hook

Here is my app_test.dart code:

import 'dart:async';
import 'dart:io';
import 'package:flutter_gherkin/flutter_gherkin.dart';
import 'package:gherkin/gherkin.dart';
import 'hooks/hooks.dart';
import 'steps/home.dart';

Future<void> main(List<String> args) async {
  if (args.isEmpty) {
    print('please pass in the uri');
    exit(1);
  }
  final steps = [
    verifyHomeScreen(),
  ];

  final config = FlutterTestConfiguration.DEFAULT(
    steps,
    featurePath: 'features/*.*.feature',
    targetAppPath: 'test_driver/app.dart',
  )
    ..hooks = [HookExample(), AttachScreenshotOnFailedStepHook()]
    ..logFlutterProcessOutput = true
    ..verboseFlutterProcessLogs = true
    ..restartAppBetweenScenarios = false
    ..targetAppWorkingDirectory = '../'
    ..runningAppProtocolEndpointUri = args[0]
    ..targetAppPath = 'test_driver/app.dart';

  return GherkinRunner().execute(config);
}

**Comment by jonsamwell** [comment]
It looks like the `featurePath` pattern is not finding anything on windows.  You could try 'features/*.*.feature' instead

**Comment by skumar11pk** [comment]
Thanks for the reply !

I tried this 'features/..feature', but no luck.

any other solution ?

**Comment by jonsamwell** [comment]
Sorry looks like the last thing I posted was wrong try this

```
features/**.feature
```

**Comment by skumar11pk** [comment]
I have tried everything, even I have passed the absolute path of feature file, but its not working

**Comment by SoftWyer** [comment]
It looks like [there's some path parsing issues](https://github.com/jonsamwell/dart_gherkin/issues/49) in Gherkin that means it doesn't handle Android/iOS platform differences particularly well. 

On Windows, try this:

```
featurePath: r'features\\.*.feature',
```

In the [Gherkin test code](https://github.com/jonsamwell/dart_gherkin/blob/2c6fa8a7564578a9e33ec295d2abde573d0cb75d/example/test.dart#L14), they have this cumbersome logic:
```
String buildFeaturesPathRegex() {
  // '\' must be escaped, '/' must not be escaped:
  var featuresPath = (Platform.isWindows)
      ? 'features${Platform.pathSeparator}\\.*\.feature'
      : 'features${Platform.pathSeparator}.*\.feature';

  return featuresPath;
}
```

**Comment by jonsamwell** [comment]
@SoftWyer thanks for this.  Yes we really need to address this logic.  Feel free to do a PR!  I will add some better documentation around this as well

**Comment by jonsamwell** [comment]
Fixed in latest RC release
