### ISSUE TITLE
Continue running cucumber steps after a failure step

### ISSUE THREAD

**Issue by duchdtran** [jonsamwell/flutter_gherkin#157]
I have many test features. When there is a failed step in any *.feature file, the test process will be stopped immediately. Could I  continue running cucumber steps after a failure step?

**Comment by jonsamwell** [comment]
@duchdtran @umangdivyanshu are you see this with the latest version.  I am seeing it continue after failed tests

**Comment by umangdivyanshu** [comment]
@jonsamwell  I am not facing this issue with the latest version, working fine for me 👍

**Comment by jonsamwell** [comment]
Thanks for letting me know.  Closing this for now then!
