### ISSUE TITLE
Question -  Do we have tags support in 3.0.0-rc6? 

### ISSUE THREAD

**Issue by umangdivyanshu** [jonsamwell/flutter_gherkin#163]
Hi @jonsamwell, Could you please answer below queries - 

Do we have tags support in 3.0.0-rc6? 
How can I execute specific feature files/scenarios based on tags?

**Comment by jonsamwell** [comment]
Yes, just set the tags you want to run on your configuration.  I'll try and get an example of using args to pass in tags at runtime using --dart-define="@tags" syntax

**Comment by jonsamwell** [comment]
Everything you have asked in on the readme file and can be set on the configuration object
