### ISSUE TITLE
[3.0.0-rc.6] Empty .feature files

### ISSUE THREAD

**Issue by AFASbart** [jonsamwell/flutter_gherkin#165]
When a project has empty .feature files, the test suite (.g.dart) file builds these files into functions as well, but because there aren't any scenario's the functions get thrown away. Problem is that the onRun() still references them. Creating errors.

The functions testFeature0 and testFeature1 do not exist.
![code](https://user-images.githubusercontent.com/89916189/140028949-6ec29c5e-d196-4c45-97b1-021a65fdeab3.png)

**Comment by jonsamwell** [comment]
Should be fixed in 3.0.0-rc.7

**Comment by AFASbart** [comment]
This still is not fixed in 3.0.0-rc.7, I am right now checking what the problem is. If I find it I will come back here.

**Comment by AFASbart** [comment]
So I have found the issue. In the file gherkin_suite_test_generator.dart the function generateForAnnotatedElement() creates the .g.dart file (at least the code that messes everything up). Where the features are build, I have changed a bit of code. What happens when there are no features / scenarios? The function `generator.generate` returns an empty string. But then when you create the onRun function you actually just go through all the files.

I have changed the code a bit.
`final featuresToExecute = new StringBuffer();

    for (var featureFileContent in featureFiles) {
      final code = await generator.generate(
        id++,
        featureFileContent,
        '',
        _languageService,
        _reporter,
      );
      if (code != "") {
        featuresToExecute.writeln('testFeature${id - 1}();');
        featureExecutionFunctionsBuilder.writeln(code);
      }
    }

    return TEMPLATE
        .replaceAll('{{feature_functions}}',
            featureExecutionFunctionsBuilder.toString())
        .replaceAll(
          '{{features_to_execute}}',
          featuresToExecute.toString(),
        );
`
This is the bottom part, I have created a new StringBuffer, where we write the function names to instead of doing it in a for loop later (what we are doing rn with `List.generate()`).
`if (code != "") {
        featuresToExecute.writeln('testFeature${id - 1}();');
        featureExecutionFunctionsBuilder.writeln(code);
}`

Here I check if the generator returns an actual function. If it doesn't (String is empty) the function reference also doesn't get added.

This edit is from line 74 in gherkin_suite_test_generator.dart

**Comment by AFASbart** [comment]
Pull request has been made.
