### ISSUE TITLE
Log display a lot of exceptions when test are finished correctly

### ISSUE THREAD

**Issue by jamontes79** [jonsamwell/flutter_gherkin#167]
Hi,

using version 3.0.0-rc.7 when the test are finished the console display a lot of exceptions not related with the code that I'm testing. This is console output:

`juanalberto@MacBook-Pro-de-admin cms_fe % fvm flutter drive --driver=test_driver/integration_test_driver.dart --target=integration_test/gherkin_suite_test.dart --flavor dev
Running "flutter pub get" in cms_fe...                          
Warning: You are using these overridden dependencies:
! flutter_colorpicker 0.6.0 (0.6.1 available)
! http 0.13.4-dev from git https://github.com/tlueder/http.git at cdfa36
Running "flutter pub get" in cms_fe...                           1.502ms
Launching integration_test/gherkin_suite_test.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             31,7s
This app is linked to the debug service: ws://127.0.0.1:51947/9asZQWdqO0A=/ws
Debug service listening on ws://127.0.0.1:51947/9asZQWdqO0A=/ws

💪 Running with sound null safety 💪
00:00 +0: Content management system: [RTG-25] Check login is not correct when data are not valid
Running scenario: [RTG-25] Check login is not correct when data are not valid # :0
   √ Given I am in login page for Content Managment System # :0 took 3ms
   √ And I fill the "loginForm_username_input" field with "xxxxxx" # :0 took 722ms
   √ And I fill the "loginForm_password_input" field with "notValidPassword" # :0 took 742ms
00:05 +1: Content management system: [RTG-25] Check login is correct when data are valid
Running scenario: [RTG-25] Check login is correct when data are valid # :0
   √ Given I am in login page for Content Managment System # :0 took 0ms
   √ And I fill the "loginForm_username_input" field with "xxxxxxx" # :0 took 1180ms
   √ And I fill the "loginForm_password_input" field with "xxxxxxx" # :0 took 1207ms
   √ When I tap the "loginForm_submit" button # :0 took 1284ms
   √ Then I expect the "home_page_title" to be "Home page" # :0 took 109ms
PASSED: Scenario [RTG-25] Check login is correct when data are valid # :0
00:09 +2: (tearDownAll)
2 scenarios (2 passed)
10 steps (10 passed)
0:00:09.772000
00:09 +3: All tests passed!
[INFO]: http://localhost:51907/ 58:26 "Installed new service worker."
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "00:00 +0: Content management system: [RTG-25] Check login is not correct when data are not valid"
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "\u001B[33;10mRunning scenario: [RTG-25] Check login is not correct when data are not valid # :0\u001B[33;0m"
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "\u001B[33;32m   √ Given I am in login page for Content Managment System # :0 took 1ms\u001B[33;0m"
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "\u001B[33;31m   × And I fill the \"loginForm_username_input\" field with \"xxxxxxx\" # :0 took 3ms  \nException: Bad state: No element\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49                throw_\ndart-sdk/lib/core/iterable.dart 520:63                                                      get single\npackages/flutter_test/src/controller.dart 114:18                                            element\npackages/flutter_test/src/controller.dart 1156:73                                           ensureVisible\npackages/flutter_gherkin/src/flutter/adapters/widget_tester_app_driver_adapter.dart 229:24  scrollIntoView\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                          runBody\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                          _async\npackages/flutter_gherkin/src/flutter/adapters/widget_tester_app_driver_adapter.dart 225:30  scrollIntoView\npackages/flutter_gherkin/src/flutter/steps/when_fill_field_step.dart 15:20                  \u003Cfn>\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                          runBody\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                          _async\npackages/flutter_gherkin/src/flutter/steps/when_fill_field_step.dart 13:18                  \u003Cfn>\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 334:14            _checkAndCall\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 339:39            dcall\ndart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 118:12                          apply\npackages/gherkin/src/gherkin/steps/step_definition_implementations.dart 236:21              onRun\npackages/gherkin/src/gherkin/steps/step_definition.dart 42:50                               \u003Cfn>\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                          runBody\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                          _async\npackages/gherkin/src/gherkin/steps/step_definition.dart 38:9                                \u003Cfn>\npackages/gherkin/src/utils/perf.dart 11:26                                                  measure\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                          runBody\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                          _async\npackages/gherkin/src/utils/perf.dart 4:30                                                   measure\npackages/gherkin/src/gherkin/steps/step_definition.dart 37:18                               run\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                          runBody\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                          _async\npackages/gherkin/src/gherkin/steps/step_definition.dart 27:25                               run\npackages/flutter_gherkin/src/flutter/runners/gherkin_integration_test_runner.dart 283:36    runStep\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                          \u003Cfn>\ndart-sdk/lib/async/zone.dart 1436:47                                                        _rootRunUnary\ndart-sdk/lib/async/zone.dart 1335:19                                                        runUnary\ndart-sdk/lib/async/future_impl.dart 160:18                                                  handleValue\ndart-sdk/lib/async/future_impl.dart 767:44                                                  handleValueCallback\ndart-sdk/lib/async/future_impl.dart 796:13                                                  _propagateToListeners\ndart-sdk/lib/async/future_impl.dart 602:5                                                   [_completeWithValue]\ndart-sdk/lib/async/future_impl.dart 640:7                                                   \u003Cfn>\ndart-sdk/lib/async/zone.dart 1428:13                                                        _rootRun\ndart-sdk/lib/async/zone.dart 1328:19                                                        run\ndart-sdk/lib/async/zone.dart 1236:7                                                         runGuarded\ndart-sdk/lib/async/zone.dart 1276:23                                                        callback\ndart-sdk/lib/async/schedule_microtask.dart 40:11                                            _microtaskLoop\ndart-sdk/lib/async/schedule_microtask.dart 49:5                                             _startMicrotaskLoop\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15                         \u003Cfn>\u001B[33;0m"
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "\u001B[33;32mPASSED: Scenario [RTG-25] Check login is not correct when data are not valid # :0\u001B[33;0m"
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════"
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "The following _Exception was thrown running a test:"
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "Exception: Bad state: No element"
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 ""
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "When the exception was thrown, this was the stack:"
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49             throw_"
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "packages/flutter_gherkin/src/flutter/runners/gherkin_integration_test_runner.dart 299:7  runStep"
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                       \u003Cfn>"
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "dart-sdk/lib/async/zone.dart 1436:47                                                     _rootRunUnary"
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "dart-sdk/lib/async/zone.dart 1335:19                                                     runUnary"
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "dart-sdk/lib/async/future_impl.dart 160:18                                               handleValue"
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "dart-sdk/lib/async/future_impl.dart 767:44                                               handleValueCallback"
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "dart-sdk/lib/async/future_impl.dart 796:13                                               _propagateToListeners"
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "dart-sdk/lib/async/future_impl.dart 602:5                                                [_completeWithValue]"
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "dart-sdk/lib/async/future_impl.dart 640:7                                                \u003Cfn>"
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "dart-sdk/lib/async/zone.dart 1428:13                                                     _rootRun"
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "dart-sdk/lib/async/zone.dart 1328:19                                                     run"
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "dart-sdk/lib/async/zone.dart 1236:7                                                      runGuarded"
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "dart-sdk/lib/async/zone.dart 1276:23                                                     callback"
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "dart-sdk/lib/async/schedule_microtask.dart 40:11                                         _microtaskLoop"
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "dart-sdk/lib/async/schedule_microtask.dart 49:5                                          _startMicrotaskLoop"
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15                      \u003Cfn>"
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 ""
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "The test description was:"
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "  [RTG-25] Check login is not correct when data are not valid"
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "════════════════════════════════════════════════════════════════════════════════════════════════════"
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "00:01 +0: Content management system: [RTG-25] Check login is not correct when data are not valid [E]"
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "  Test failed. See exception logs above.\n  The test description was: [RTG-25] Check login is not correct when data are not valid"
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "  "
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "Consider enabling the flag chain-stack-traces to receive more detailed exceptions.\nFor example, 'dart test --chain-stack-traces'."
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "00:01 +0 -1: Content management system: [RTG-25] Check login is correct when data are valid"
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "\u001B[33;10mRunning scenario: [RTG-25] Check login is correct when data are valid # :0\u001B[33;0m"
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "\u001B[33;32m   √ Given I am in login page for Content Managment System # :0 took 0ms\u001B[33;0m"
[INFO]: http://localhost:51907/dart_sdk.js 28067:14 "\u001B[33;32m   √ And I fill the \"loginForm_username_input\" field with \"xxxxxxx\" # :0 took 2260ms\u001B[33;0m"
Failure Details:
Failure in method: [RTG-25] Check login is not correct when data are not valid
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following _Exception was thrown running a test:
Exception: Bad state: No element

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49             throw_
packages/flutter_gherkin/src/flutter/runners/gherkin_integration_test_runner.dart 299:7  runStep
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                       <fn>
dart-sdk/lib/async/zone.dart 1436:47                                                     _rootRunUnary
dart-sdk/lib/async/zone.dart 1335:19                                                     runUnary
dart-sdk/lib/async/future_impl.dart 160:18                                               handleValue
dart-sdk/lib/async/future_impl.dart 767:44                                               handleValueCallback
dart-sdk/lib/async/future_impl.dart 796:13                                               _propagateToListeners
dart-sdk/lib/async/future_impl.dart 602:5                                                [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 640:7                                                <fn>
dart-sdk/lib/async/zone.dart 1428:13                                                     _rootRun
dart-sdk/lib/async/zone.dart 1328:19                                                     run
dart-sdk/lib/async/zone.dart 1236:7                                                      runGuarded
dart-sdk/lib/async/zone.dart 1276:23                                                     callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                                         _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                                          _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15                      <fn>

The test description was:
  [RTG-25] Check login is not correct when data are not valid
═════════════════════════════════════════════════════════════════

end of failure 1

Application finished.
`

Thanks a lot for this great library.

**Comment by AFASbart** [comment]
What I am seeing is that the errors are the Bad State no element exceptions?
These errors are caused when the driver cannot find the element you are trying to find with the finder.
Make sure your driver can find the element. (In rc-07 you can also use textContaining)

**Comment by jonsamwell** [comment]
I wonder why these cannot find element errors did not result in a test failure? @jamontes79 did the test actually work and manipulate the elements correctly?  Are you able to do a small reproducing repo for me to look at?

**Comment by jamontes79** [comment]
Hi, finally there was a problem in my code, but I don't understand why the test was green and then lunch the exceptions. That's fine because alert us, but in my opinion the test must be red. 

For my part the issue can be closed.

Thanks a lot for your comments.

**Comment by jonsamwell** [comment]
@jamontes79 agree it should probably be red and fail are you able to do a sample to reproduce this so it can be fixed?
