### ISSUE TITLE
Is it possible to skip a test from an hook?

### ISSUE THREAD

**Issue by AFASbart** [jonsamwell/flutter_gherkin#169]
I want to be able to skip a test from an hook. Is this possible?

**Comment by jonsamwell** [comment]
This is an interesting idea.  At the moment it is not possible.  I will check and see if cucumber actually supports this and how they do it.  Let me get back to you on this

**Comment by jonsamwell** [comment]
@zaralockheart you can already run tests based on tags. Furthermore you can provide expressions to tags i.e. `@smoke and not @payment` etc

@AFASbart do you still have this requirement? I am not sure this is in the gherkin spec?
