### ISSUE TITLE
Json bad generated when first scenario of a feature is not executed

### ISSUE THREAD

**Issue by jamontes79** [jonsamwell/flutter_gherkin#171]
Using flutter_gherkin 3.0.0-rc.7 when I run only some specific test by tag and the scenario is not the first of the feature, the json generated by JsonReporter is not well generated. 

integration_test_driver.dart
`
import 'package:integration_test/integration_test_driver.dart'
as integration_test_driver;

Future main() {
// The Gherkin report data send back to this runner by the app after
// the tests have run will be saved to this directory
integration_test_driver.testOutputsDirectory =
'integration_test/gherkin/reports';

return integration_test_driver.integrationDriver(
timeout: Duration(minutes: 90),
);
}
`

gherkin_suite_test.dart
`
part 'gherkin_suite_test.g.dart';

@GherkinTestSuite()
void main() {
executeTestSuite(
FlutterTestConfiguration.DEFAULT(
[

  ],
)
  ..tagExpression = "@TEST_RTG-112"
  ..reporters = [
    JsonReporter(
      writeReport: (_, __) => Future<void>.value(),
    ),
  ],
(World world) async {
  await getIt.reset();
  app.main();
},
);
}
`
generated json:
`
{
  "gherkin_reports": "[[{\"description\":\"An unnamed feature is possible if something is logged before any feature has started to execute\",\"id\":null,\"keyword\":\"Feature\",\"line\":0,\"name\":\"Unnamed feature\",\"uri\":\"unknown\",\"elements\":[{\"keyword\":\"Scenario\",\"type\":\"scenario\",\"id\":\"null;unnamed\",\"name\":\"Unnamed\",\"description\":\"An unnamed scenario is possible if something is logged before any feature has started to execute\",\"line\":0,\"steps\":[{\"keyword\":null,\"name\":\"Unnamed\",\"line\":0,\"match\":{\"location\":\"null:0\"},\"result\":{\"status\":\"failed\",\"duration\":0}}]},{\"keyword\":\"Scenario\",\"type\":\"scenario\",\"id\":\"null;[rtg-25] check login is correct when data are valid\",\"name\":\"[RTG-25] Check login is correct when data are valid\",\"description\":\"\",\"line\":1,\"tags\":[{\"line\":1,\"name\":\"@REQ_RTG-19\"},{\"line\":1,\"name\":\"@TEST_RTG-114\"},{\"line\":1,\"name\":\"@REQ_RTG-25\"}],\"steps\":[{\"keyword\":\"Given \",\"name\":\"I am in login page for Content Managment System\",\"line\":1,\"match\":{\"location\":\":1\"},\"result\":{\"status\":\"passed\",\"duration\":3043000000}},{\"keyword\":\"And \",\"name\":\"I fill the \\\"loginForm_username_input\\\" field with \\\"xxxxx\\\"\",\"line\":1,\"match\":{\"location\":\":1\"},\"result\":{\"status\":\"passed\",\"duration\":2924000000}},{\"keyword\":\"And \",\"name\":\"I fill the \\\"loginForm_password_input\\\" field with \\\"xxxxx\\\"\",\"line\":1,\"match\":{\"location\":\":1\"},\"result\":{\"status\":\"passed\",\"duration\":6524000000}},{\"keyword\":\"When \",\"name\":\"I tap the \\\"loginForm_submit\\\" button\",\"line\":1,\"match\":{\"location\":\":1\"},\"result\":{\"status\":\"passed\",\"duration\":7055000000}},{\"keyword\":\"Then \",\"name\":\"I expect the \\\"home_page_title\\\" to be \\\"Home page\\\"\",\"line\":1,\"match\":{\"location\":\":1\"},\"result\":{\"status\":\"passed\",\"duration\":239000000}}]}]}]]"
}
`
feature:
`
@REQ_RTG-19
Feature: Content management system

  @TEST_RTG-112 @REQ_RTG-25
  Scenario: [RTG-25] Check login is not correct when data are not valid
    Given I am in login page for Content Managment System
    And I fill the "loginForm_username_input" field with "xxxxx"
    And I fill the "loginForm_password_input" field with "xxxxx"
    When I tap the "loginForm_submit" button
    Then I see a notification in the bottom with text "Email or password invalid"

  @TEST_RTG-114 @REQ_RTG-25
  Scenario: [RTG-25] Check login is correct when data are valid
    Given I am in login page for Content Managment System
    And I fill the "loginForm_username_input" field with "xxxxx"
    And I fill the "loginForm_password_input" field with "xxxxx"
    When I tap the "loginForm_submit" button
    Then I expect the "home_page_title" to be "Home page"
`
Thanks a lot in advance

**Comment by jonsamwell** [comment]
Could you try the latest version and see if this is still a problem?

**Comment by Stephane99** [comment]
Hi,

After successfully generating the report when at least one test is in error (thanks to the workaround proposed in the previous issue https://github.com/jonsamwell/flutter_gherkin/issues/170),
I have the same problem with flutter_gherkin version 3.0.0-rc.9:
- when the first test is in error, the report contains "Unnamed feature" as the name of the feature.
- when the second test is in error but not the first, the report is well formatted.

I saw the warning "An unnamed feature is possible if something is saved before a feature has started to run", but I don't try to attach any text or a screenshot.

**Comment by jonsamwell** [comment]
@Stephane99 that would indicate there is an exception being raised and sent to the reporter before the first scenario has started executing.  Are you able to provide a reproducible repo that I can look at?

**Comment by jonsamwell** [comment]
Could you try this in the latest rc release?
