### ISSUE TITLE
Error with log output when lunch the tests over web

### ISSUE THREAD

**Issue by jamontes79** [jonsamwell/flutter_gherkin#172]
Using flutter_gherkin 3.0.0-rc.7 the log output throws an exception using Android Studio + macOs

integration_test_driver.dart
`
import 'package:integration_test/integration_test_driver.dart'
as integration_test_driver;

Future main() {
// The Gherkin report data send back to this runner by the app after
// the tests have run will be saved to this directory
integration_test_driver.testOutputsDirectory =
'integration_test/gherkin/reports';

return integration_test_driver.integrationDriver(
timeout: Duration(minutes: 90),
);
}
`

gherkin_suite_test.dart
`
part 'gherkin_suite_test.g.dart';

@GherkinTestSuite()
void main() {
executeTestSuite(
FlutterTestConfiguration.DEFAULT(
[

  ],
)
  ..reporters = [
     ProgressReporter()
          ..setWriteLineFn(print)
          ..setWriteFn(print),
    TestRunSummaryReporter()
          ..setWriteLineFn(print)
          ..setWriteFn(print),
    JsonReporter(
      writeReport: (_, __) => Future<void>.value(),
    ),
  ],
(World world) async {
  await getIt.reset();
  app.main();
},
);
}
`

Output with version  3.0.0-rc.6:
![version6](https://user-images.githubusercontent.com/11333270/141792166-59b7b3c2-61c5-4dd5-9510-64366d9718d5.png)

Output with version  3.0.0-rc.7:
![version7](https://user-images.githubusercontent.com/11333270/141792248-94cbb305-2300-42d4-b050-bc05d9368cd9.png)

Thanks a lot in advance

**Comment by jonsamwell** [comment]
Looks like the StdoutReporter can't be supported on the web now - I added a check to see if ANSI code are supported due to #155.  You could try running it and removing that report from the reporters config?  I think the best option would be to catch this error in the stdout reporter though.  I'll try and get a fix in tomorrow

**Comment by jamontes79** [comment]
Thanks a lot, I'll try it and I give you feedback. :)

**Comment by bluego-joe** [comment]
I am experiencing this issue also. Removing the reporters solves the problem, but means that you can't see any test output. Needless to say, this makes debugging tricky :)

**Comment by jonsamwell** [comment]
Should be fixed in v3.0.0-rc.9

**Comment by jonsamwell** [comment]
great

**Comment by jamontes79** [comment]
Working like a charm... thanks a lot for the quickly fix.

Great job and great library! :)
