### ISSUE TITLE
Question - How can we add logs for failed steps in the HTML report?

### ISSUE THREAD

**Issue by umangdivyanshu** [jonsamwell/flutter_gherkin#173]
Hi @jonsamwell, Could you please answer below queries -

I am using 3.0.0-rc.7 and in the HTML report I am getting screenshot added to failed step by using AttachScreenshotOnFailedStepHook().

However, I also need to have some logs in the report along with screenshot which could explain the reason of failure. Could you please guide me on how to add logs to the report?

**Comment by jonsamwell** [comment]
You can do something like this and it will appear in the report

```
import 'package:gherkin/gherkin.dart';

class WriteLogOnStepFailedHookextends Hook {
  /// Run after a step has executed
  @override
  Future<void> onAfterStep(World world, String step, StepResult stepResult) async {
    if (stepResult.result == StepExecutionResult.fail) {
      world.attach('Some info ..........','text/plain');
    }
  }
}
```

**Comment by umangdivyanshu** [comment]
Hi @jonsamwell, I have added the above code and updated the gherkin_suite_test.dart file for this hook configuration. But it does not seem to be working, logs are not getting attached in the report. Do I need to add something in step definition as well? Could you please provide an example here, if possible?

**Comment by umangdivyanshu** [comment]
Hi @jonsamwell, could you please answer the query here?

**Comment by jonsamwell** [comment]
Sorry @umangdivyanshu I will have time tomorrow to look into this

**Comment by jonsamwell** [comment]
This should work.  Note that you need to provide the step as the context to the attachment so the json reporter knows it relates to the step

```
import 'package:gherkin/gherkin.dart';

class AttachLogsOnFailedStepHook extends Hook {
  /// Run after a step has executed
  @override
  Future<void> onAfterStep(World world, String step, StepResult stepResult) async {
    if (stepResult.result == StepExecutionResult.fail) {
      final logs = await _getLogs();
      world.attach(logs, 'text/plain', step);
    }
  }

  Future<String> _getLogs() async {
    // logic to get logs
  }
}
```

**Comment by umangdivyanshu** [comment]
Thanks @jonsamwell for the help 👍 
Is there any plugin/library or in-built method which could be used to return the logs in _getLogs method?

**Comment by jonsamwell** [comment]
I use https://pub.dev/packages/logging

You could then have a  hook that listens to the logs but you'll have to come up with some way of retrieving the logs yourself

```
  Logger.root.level = Level.ALL;
  Logger.root.onRecord.listen(
    (LogRecord rec) {
      // save log somewhere to recall later

      print('${rec.loggerName}: ${rec.level} - ${rec.message}');
    },
  );
```

**Comment by umangdivyanshu** [comment]
Thanks @jonsamwell  for the help. Really appreciate it!
