### ISSUE TITLE
gherkin_suite_test.g.dart is sometimes not updated

### ISSUE THREAD

**Issue by bluego-joe** [jonsamwell/flutter_gherkin#177]
I am encountering a strange issue where sometimes running `flutter pub run build_runner build --delete-conflicting-outputs` does not update the contents of `gherkin_suite_test.g.dart`, after changing one or more `.feature` files. This behaviour seems to be mostly persistent, but cannot be produced 100% of the time.

I have found that deleting `gherkin_suite_test.g.dart` before running `flutter pub run build_runner build --delete-conflicting-outputs` does not solve the problem. I have found that it's necessary to first delete `gherkin_suite_test.g.dart`, then run `flutter clean`, then run `flutter pub get`, before attempting to regenerate the file.

In my experience, the problem may occur following any change to one of the `.feature` files. We have seen this problem, for example, when adding/rearranging steps, adding/removing features, and adding/removing tags.

Using version 3.0.0-rc.9.

**Comment by golane-august** [comment]
Deleting the file `.dart_tool/build/generated/your_project_folder/integration_test/gherkin_suite_test.gherkin_tests.g.part` can replace all these steps. This file should be deleted / checked when running `build_runner`

**Comment by jonsamwell** [comment]
This is the script I use to regenerate the when I change any feature files and seems to always work

```
flutter pub run build_runner clean
flutter pub run build_runner build --delete-conflicting-outputs
```

We don't have any control over the build_runner it just calls the generator classes if it things files have changed so it must not be taking the files outside of the main lib folder into account.  I'll investigate but not sure there is much I can do

**Comment by bluego-joe** [comment]
@jonsamwell, this works for me too. However if your project contains a lot of generated code, this can quite significantly increase the time taken to run `flutter pub run build_runner build`. Deleting the individual file, as per @golane-august's comment, appears to be equally effective, but a lot quicker.

I tried adding `integration_test/features/*.feature` to the `sources` in `build.yaml`, but this doesn't have any effect. Would you expect this to work, or am I misunderstanding the use of this file?

**Comment by vrnvorona** [comment]
clean is nice solution. I am dumb so i always meddle with packages and i disabled cache retrieval completely.

**Comment by jonsamwell** [comment]
Closing and current suggested workflow is 

```
flutter pub run build_runner clean
flutter pub run build_runner build --delete-conflicting-outputs
```
