### ISSUE TITLE
How to run tests marked with a specific tags

### ISSUE THREAD

**Issue by porturabo** [jonsamwell/flutter_gherkin#178]
I am using 3.0.0-rc.9 version of the package and want to use tags to be able to run tests for a specific group of tests. Based on [this example](https://github.com/jonsamwell/flutter_gherkin/blob/integration_test__package_support/example_with_integration_test/integration_test/features/check.feature#L1) tags can be added to the code without any issues, but I am not sure how to run the tests marked with tags like "@tag". Could you advice?

**Comment by AFASbart** [comment]
In your configuration (gherkin_test_suite.dart) should be an option ..tagExpression = "". There you can place your tag, I do not know if you have to include the @

**Comment by jonsamwell** [comment]
I use the below code to set various things from the command line or you can set the tag expression inline as @AFASbart  suggests (note that you need the '@')

```
@GherkinTestSuite(featurePaths: <String>[
  'test/integration/features/**.feature',
])
void main() {
  const targetConfig = String.fromEnvironment(
    'targetConfig',
    defaultValue: 'dev',
  );
  const tagExpression = String.fromEnvironment(
    'tagExpression',
    defaultValue: 'not @ignore',
  );

executeTestSuite(
    FlutterTestConfiguration()
    ..defaultTimeout = const Duration(seconds: 90)
    ..tagExpression = tagExpression
    ..reporters = [
      StdoutReporter(MessageLevel.error)
        ..setWriteLineFn(printFn)
        ..setWriteFn(printFn),
      ProgressReporter()
        ..setWriteLineFn(printFn)
        ..setWriteFn(printFn),
      TestRunSummaryReporter()
        ..setWriteLineFn(printFn)
        ..setWriteFn(printFn),
      JsonReporter(
        writeReport: (_, __) => Future<void>.value(),
      ),
    ]
  );
}
```

This command would set the tag expression

```
flutter drive --driver=test/integration/test_driver.dart --target=test/integration/suites/gherkin_suite_test.dart --flavor development --dart-define=targetConfig="dev" --dart-define=tagExpression="@debug"
```

**Comment by porturabo** [comment]
@jonsamwell thanks a lot
