### ISSUE TITLE
Non-run steps are not being showed in the report

### ISSUE THREAD

**Issue by AFASbart** [jonsamwell/flutter_gherkin#179]
Is it possible for the steps that have not been run (because a previous failed step) to still show up in the JSON report and for instance have the skipped status?

**Comment by AFASbart** [comment]
I see that we can maybe read the file which the feature is stored. But in my report the uri is empty. @jonsamwell Is this a known bug or?

**Comment by jonsamwell** [comment]
I think this is probably something to do with the generated code not catching exceptions around the runStep code so the runStep after the one that failed are not actually ran.

**Comment by AFASbart** [comment]
I have created this function, it will now be seen as a skipped step in the JSON report (and hooks).

**Comment by jonsamwell** [comment]
Should be fixed in the latest release `3.0.0-rc.10`
