### ISSUE TITLE
Resetting the app like a fresh install before a test

### ISSUE THREAD

**Issue by snickersv2** [jonsamwell/flutter_gherkin#18]
Hi,

Is there a way to rest the app like a fresh install before starting a test? just like restartAppBetweenScenarios.

Thank you,
Vic

**Comment by jonsamwell** [comment]
Hi @abanv2,

Yes I think this should be possible but it would be very very slow.  If you take a look at this class (https://github.com/jonsamwell/flutter_gherkin/blob/master/lib/src/flutter/hooks/app_runner_hook.dart) it is the hook that restarts the app after every test if the 'restartAppBetweenScenarios' flag is true.

You could use that hook as a template.  I'm not sure how to uninstall / install the app though.  This might have to be done via some utility outside of Flutter though.

**Comment by snickersv2** [comment]
thanks, i found a workaround so far by uninstalling the app, via calling Process.run ,  during onBeforeRun().

**Comment by jonsamwell** [comment]
Great. Could you post the code in case anyone else what's to achieve the
same.

Thanks

**Comment by snickersv2** [comment]
For android: await Process.run( <adb directory> , ['uninstall' , <package name>]);
For ios: await Process.run( <ideviceinstaller directory> , ['-U' , <bundle id> ]);

However, I haven't found anything about determining the platform of the target device by using Flutter driver or any test package. Calling Platform.operatingSystem returns the OS of my machine (in my case, macOS) instead of either iOS or Android.

**Comment by jonsamwell** [comment]
Thanks for the info.
