### ISSUE TITLE
Swipe step is not working with integration_test for flutter_gherkin 3.0.0-rc.9

### ISSUE THREAD

**Issue by veesmana** [jonsamwell/flutter_gherkin#180]
Hi
I use flutter_gherkin 3.0.0-rc.9 for my project but I can't use default swipe steps like:

- I swipe [down|left|right|up] by {int} pixels on the {string}
- I swipe [down|left|right|up] by {int} pixels on the on the [button|element|label|field|text|widget|dialog|popup] that contains the text {string}
Because I always get the error "Too many elements" 
And when I try to use custom steps I got the same error "Too many elements" but I have only one widget with this key
![image](https://user-images.githubusercontent.com/65387404/144821084-95e0adab-ada7-410c-ac6c-0b2833fe4d97.png)
![image](https://user-images.githubusercontent.com/65387404/144821224-7ef18e58-e56e-40ba-9371-4402b2fba0ed.png)

My flutter doctor:
![image](https://user-images.githubusercontent.com/65387404/144821446-0825dcac-db43-4690-8406-ff32a129c818.png)
and flutter version:
![image](https://user-images.githubusercontent.com/65387404/144821544-46ce0582-69e4-4cf1-8d1e-13f65a14054d.png)

Have you solution for this problem?

**Comment by jonsamwell** [comment]
Hmmm, I have a test for swiping (https://github.com/jonsamwell/flutter_gherkin/blob/integration_test__package_support/example_with_integration_test/integration_test/features/swiping.feature).

The swipe step expects a scrollable descendent element under the element given in the step so this could be the issue?

https://github.com/jonsamwell/flutter_gherkin/blob/integration_test__package_support/lib/src/flutter/adapters/widget_tester_app_driver_adapter.dart#L152


https://github.com/jonsamwell/flutter_gherkin/blob/integration_test__package_support/lib/src/flutter/steps/swipe_step.dart#L18

Are you able to debug this?

**Comment by veesmana** [comment]
Hi
Thank you for your helping. I understood how it working and  how I should work with it.
But I have one more question. Have we any solution to use swipe when we have more than 1 Scrollable widget in parent widget or we must to search widget only with 1 Scrollable widget inside it?

**Comment by jonsamwell** [comment]
In that case you could always just create a step that can handle this.  This is the code that performs the swipe so you could modify it to your needs in a custom step.

Step:

https://github.com/jonsamwell/flutter_gherkin/blob/integration_test__package_support/lib/src/flutter/steps/swipe_step.dart#L53

Scroll logic:

https://github.com/jonsamwell/flutter_gherkin/blob/integration_test__package_support/lib/src/flutter/adapters/widget_tester_app_driver_adapter.dart#L152
