### ISSUE TITLE
Question - How can we share data between steps in a scenario?

### ISSUE THREAD

**Issue by umangdivyanshu** [jonsamwell/flutter_gherkin#181]
Hey @jonsamwell, Hope you are doing well !!
 
I am trying to automate a scenario where I need to share data between test steps in a scenario. How can I do this? 

I tried to use context.world.attach(String testData, 'text/plain'), but I am not sure how to retrieve the attached data in the next step. If I use context.world.attach(), would it be a correct approach for this?

**Comment by jonsamwell** [comment]
Hi @umangdivyanshu this is exactly what the World object is for.  You should create a custom world object that can persist the returned data for you.  The world object is shared across the whole scenario so any step within a single scenario run can access it.  The attach method is just for attaching information for the reports to use.

You can see how to create a custom world in the example https://github.com/jonsamwell/flutter_gherkin/blob/integration_test__package_support/example_with_integration_test/integration_test/gherkin/world/custom_world.dart
