### ISSUE TITLE
tests fail when the app is restarted

### ISSUE THREAD

**Issue by veesmana** [jonsamwell/flutter_gherkin#183]
Hi
Could you help me?
Our tests crash every time when the app reload in one screen. And we get this error
![error](https://user-images.githubusercontent.com/65387404/145193483-4e63e446-4ca9-40e9-8cb6-2f52544fe246.PNG)

But this widget with error declared only once in the app and it can't have any duplicate. When use flutter_gherkin_2.0.0 we hadn't this problem
Screen from terminal:
![image](https://user-images.githubusercontent.com/65387404/145194424-471ef581-7bf0-4724-9344-9422978cea94.png)
Flutter doctor:
![image](https://user-images.githubusercontent.com/65387404/145195225-46ff83ea-717a-4583-8be0-1a4d07849d45.png)

**Comment by jonsamwell** [comment]
Is the key a static one?

**Comment by veesmana** [comment]
Yes, it is static

**Comment by jonsamwell** [comment]
Yes that will be it. As it is static is persists. The running instance is
not reloaded just the application within.  Make that an instance variable
and it will work.
