### ISSUE TITLE
Problem with test generation from config

### ISSUE THREAD

**Issue by veesmana** [jonsamwell/flutter_gherkin#185]
Hi
I try create file only with some tests and Create configuration like this:

_final config = TestConfiguration()
    ..features = [
      Glob(r"integration_test/features/test.feature")]
    ..reporters = [
      StdoutReporter(MessageLevel.info)
        ..setWriteLineFn(print)
        ..setWriteFn(print),
      ProgressReporter()
        ..setWriteLineFn(print)
        ..setWriteFn(print),
      TestRunSummaryReporter()
        ..setWriteLineFn(print)
        ..setWriteFn(print),
      JsonReporter(
        writeReport: (_, __) => Future<void>.value(),
      ),
    ]
    ..order = ExecutionOrder.sequential
    ..stepDefinitions = StepDefinitions.list;_
    
But in the generated file i get all tests from all features file. Can you give me advice how to fix it?

**Comment by vrnvorona** [comment]
Easier to assign all tests a tag based on their features and execute only them. I remember having difficulties with Glob as well, but don't remember if i ever solved it.

**Comment by AFASbart** [comment]
I have a fix for this, if you are using the rc (integration test) version, you have a piece of code (@GherkinTestSuite()) in your file.
In the brackets of that piece of code, you can (need) to specify the features path if it differs from the original path.
##### From:
```
@GherkinTestSuite()
```
##### To:

```
@GherkinTestSuite(
    featurePaths: <String>['integration_test/features/DM_ERP/**.feature'],
    executionOrder: ExecutionOrder.alphabetical)
```

**Comment by AFASbart** [comment]
I also made a pull request @jonsamwell, to make these unused variables deprecated. This should avoid these kind of issues. 

(PR: #187)

**Comment by veesmana** [comment]
Hello
Thank you to everyone for your advices. They are really helpful for me
@AFASbart if you already made pull request I will close my ticket
