### ISSUE TITLE
How Can we use flutter_gherkin on device farm ? 

### ISSUE THREAD

**Issue by yahyakara** [jonsamwell/flutter_gherkin#188]
Hi I am new for flutter test, I develop some tests with flutter  integration test but there is a lot of limitation on it :(
So I want to use flutter_gherkin but I want to know  Can we use flutter_gherkin on any device farm  etc ? I didn't find any document about this. 

Regards

**Comment by jonsamwell** [comment]
@yahyakara did you find a way to do this?

**Comment by yahyakara** [comment]
@jonsamwell No I still looking for a way I closed because I had another issue But We fixed it, 
I will continue about this :) Do you have any advice? :)
