### ISSUE TITLE
Failed to take screenshot Unknown method "_flutter.screenshot" is coming as error in Integration Testing in Chrome

### ISSUE THREAD

**Issue by skumarpk** [jonsamwell/flutter_gherkin#191]
When I try to take screenshots with Integration Testing then it throwing an error as -
Failed to take screenshot
_flutter.screenshot: (-32601) Unknown method "_flutter.screenshot".

This issue is only occurring in Chrome browser, same code working fine with Android device and able to take screenshots.
I have followed 'https://pub.dev/packages/flutter_gherkin#screenshot' and everything working fine except screenshot in Chrome browser.

Steps to Reproduce
Once app is launched in Chrome browser, try to take screenshot with BDD approach(Integration testing)
then it shows error as -
Failed to take screenshot
_flutter.screenshot: (-32601) Unknown method "_flutter.screenshot".

Expected results: Should take screenshot

Actual results: showing error in Json/html report

This is code inside app_test.dart page -
..hooks = [HookExample(), AttachScreenshotOnFailedStepHook()]

Below is the exception that occurring:

Failed to take screenshot
_flutter.screenshot: (-32601) Unknown method "_flutter.screenshot".
#0 new _OutstandingRequest (package:vm_service/src/vm_service.dart:1626:45)
#1 VmService._call (package:vm_service/src/vm_service.dart:2109:21)
#2 VmService.callServiceExtension (package:vm_service/src/vm_service.dart:2072:14)
#3 VmService.callMethod (package:vm_service/src/vm_service.dart:2062:12)
#4 VMServiceFlutterDriver.screenshot (package:flutter_driver/src/driver/vmservice_driver.dart:334:54)
#5 AttachScreenshotOnFailedStepHook.takeScreenshot (package:flutter_gherkin/src/flutter/hooks/attach_screenshot_on_failed_step_hook.dart:28:19)
#6 AttachScreenshotOnFailedStepHook.onAfterStep (package:flutter_gherkin/src/flutter/hooks/attach_screenshot_on_failed_step_hook.dart:18:32)
#7 AggregatedHook._invokeHooks (package:gherkin/src/hooks/aggregated_hook.dart:92:9)
#8 AggregatedHook.onAfterStep (package:gherkin/src/hooks/aggregated_hook.dart:85:7)
#9 FeatureFileRunner._runStep (package:gherkin/src/feature_file_runner.dart:349:5)
#10 FeatureFileRunner._runScenario (package:gherkin/src/feature_file_runner.dart:268:13)
#11 FeatureFileRunner._runScenarioInZone. (package:gherkin/src/feature_file_runner.dart:160:24)

**Comment by jonsamwell** [comment]
Hmmm, It looks like there is now implementation for this method when running in a browser

**Comment by skumarpk** [comment]
> Hmmm, It looks like there is now implementation for this method when running in a browser

Hi Jon,
It is still unimplemented method, can't take screenshot in browser. Any idea how long it will take to implement.

**Comment by jonsamwell** [comment]
It's within the Flutter framework so it is out of my control. You could file an issue with Flutter to see when they plan to implement it or see if there is a recommended alternative approach for taking screenshots on the web?

**Comment by jonsamwell** [comment]
Should be fixed in the latest release `3.0.0-rc.10`
