### ISSUE TITLE
[Question] How can we get scenario status?

### ISSUE THREAD

**Issue by umangdivyanshu** [jonsamwell/flutter_gherkin#201]
Hi @jonsamwell 

We can get the status of the step by using StepExecutionResult but couldn't find anything which gives the status of the scenario. 

How can we determine if a scenario is Pass/Fail? I need the scenario's status? Is there anything similar to StepExecutionResult by which we can identify the status of scenario as Pass/Fail?

**Comment by umangdivyanshu** [comment]
Hi @jonsamwell, could you please answer to above query?

**Comment by jonsamwell** [comment]
There isn't an easy way to do this yet we should probably add it to the `onAfterScenaro` hook I think https://github.com/jonsamwell/dart_gherkin/blob/master/lib/src/hooks/hook.dart#L37

Feel free to do a PR.

**Comment by AFASbart** [comment]
I have fixed this, this will now get added send to the hook but also added to the default JSON reporter. I will create PR tonight.

**Comment by umangdivyanshu** [comment]
Thanks @AFASbart for working on this.

**Comment by jonsamwell** [comment]
Fixed in the latest rc version (see https://github.com/jonsamwell/dart_gherkin/blob/master/lib/src/hooks/hook.dart#L49)
