### ISSUE TITLE
Multiple scenario and app always back to home

### ISSUE THREAD

**Issue by rizkavio21** [jonsamwell/flutter_gherkin#203]
Hello, I try to running Flutter Gherkin Automation. However, I'm having a little trouble getting it to work by running multiple scenarios at the same time. Is it really not possible to run it with multiple scenarios at the same time without a logout step in each scenario?

Then, I tried the code `restartAppBetweenScenarios = true` but why does the application keep returning to the home page? thanks

**Comment by jonsamwell** [comment]
Hi, you have to handle resetting your app state after / before every test as the actual application is being run not just a widget within it.  You can do this on with a reset hook similar to the one in the sample project here https://github.com/jonsamwell/flutter_gherkin/blob/integration_test__package_support/example_with_integration_test/integration_test/gherkin/hooks/reset_app_hook.dart

**Comment by rizkavio21** [comment]
ok thanks means i have to add a hook huh? or can I just add the hook to my app?

**Comment by jonsamwell** [comment]
You can add that hook but as each app is specific resetting the internal app state needs to be done depending on how to do that in your all.  For example you may need to clear preferences, database, navigate to login etc etc

**Comment by rizkavio21** [comment]
oke thanks, i will try it

**Comment by jonsamwell** [comment]
Great!

**Comment by rizkavio21** [comment]
currently i am using flutter gherkin 2, is it support for hook? or i need update to flutter gherkin 3?

**Comment by rizkavio21** [comment]
I'm trying to use RC version `flutter_gherkin: ^3.0.0-rc.9` but got some problems like undefined name 'FlutterDriverutils' What should I do now?

**Comment by jonsamwell** [comment]
@rizkavio21  FlutterDriverUtils is no longer in the RC version it relies on the driver instead `context.world.appDriver`.  See the example https://github.com/jonsamwell/flutter_gherkin/blob/integration_test__package_support/example_with_integration_test/integration_test/gherkin/steps/expect_todos_step.dart#L28

**Comment by rizkavio21** [comment]
ok i think i need to read it. how for `pre-defined step` can it be used in the RC version?

**Comment by jonsamwell** [comment]
@rizkavio21 it's all on the `context.world.appDriver`
