### ISSUE TITLE
How to start app and reset app before each gherkin scenario Run with latest integration test package?

### ISSUE THREAD

**Issue by amitkumar-qa** [jonsamwell/flutter_gherkin#206]
Hi @jonsamwell 

I am using latest integration test package `flutter_gherkin: ^3.0.0-rc.9` to write gherkin tests in flutter.
I want to start app as fresh every-time before each gherkin scenario run.
Could you please check and help with it how it is possible with latest integration test package?

Thanks
Amit

**Comment by jonsamwell** [comment]
See https://github.com/jonsamwell/flutter_gherkin/blob/integration_test__package_support/example_with_integration_test/integration_test/gherkin/hooks/reset_app_hook.dart

**Comment by amitkumar-qa** [comment]
@jonsamwell As i followed the above link shared by you. But that code requires lots of dependencies to create such as customworld , external applicationmanager and injector etc. Please clarify if i am on right track?

Thanks
Amit

**Comment by jonsamwell** [comment]
@amitkumar-qa the linked code is quite a robust pattern but you are correct it add complexity.  Depending on your app you might just need to clear shared preferences and return to the login screen.  If it is simple enough you could just do it all in the hook itself.


```
import 'package:gherkin/gherkin.dart';

import '../world/custom_world.dart';

class ResetAppHook extends Hook {
  @override
  int get priority => 100;

  /// Resets the application state before the test is run to ensure no test side effects
  @override
  Future<void> onAfterScenarioWorldCreated(
    World world,
    String scenario,
    Iterable<Tag> tags,
  ) async {
    await sharedPreferences.clear();
   // navigate to a certain page etc etc
  }
}
```

**Comment by amitkumar-qa** [comment]
@jonsamwell Thank you so much for providing the context. Any idea by when integration test support will be fully available as part of RC?

**Comment by jonsamwell** [comment]
The RC is ready to go I just need to find some time to get the documentation up-to-date.  Feel free to do a PR.

**Comment by amitkumar-qa** [comment]
Thank you @jonsamwell
