### ISSUE TITLE
Migrate from flutter_driver to integration_test package

### ISSUE THREAD

**Issue by snakebyte3d** [jonsamwell/flutter_gherkin#207]
Can you please update  dependencies so that it works with latest versions of analyzer package, especially 3.0.0+?

**Comment by snakebyte3d** [comment]
Changed to subject from "Analyzer ^3.0.0 support" to "Migrate from flutter_driver to integration_test package" to properly describe the root cause rather than the effect. Without doing these changes the new build_runner cannot be used which makes development with the new packages that depend on code generation impossible.

**Comment by jonsamwell** [comment]
@snakebyte3d see https://pub.dev/packages/flutter_gherkin/versions/3.0.0-rc.9

It is ready to go but the documentation needs to be updated.  Feel free to do a PR for the documentation then this can become the main version
