### ISSUE TITLE
Is there a support to skip installing fresh app on device?

### ISSUE THREAD

**Issue by snickersv2** [jonsamwell/flutter_gherkin#21]
Hi,

Is there support for running the test on an already installed build instead of installing a fresh app?
For reference there is a --build/--no-build flag in Flutter Driver, https://github.com/flutter/flutter/pull/30818

Thank you.

**Comment by jonsamwell** [comment]
Hi @snickersv2 

I think one note of caution is that the installed app would have to have the flutter driver extensions enabled (https://github.com/jonsamwell/flutter_gherkin/blob/master/example/test_driver/app.dart#L7) and also I'm not sure how flutter_gherkin would find out the communication uri to the app?  We'll have to  do some digging.

Although this would be a good option to have.  I'll see if I can work it in over the weekend.  PR's are welcome though!

**Comment by jonsamwell** [comment]
Hi @snickersv2 

This is now fix and available in the latest release (v1.0.0).  The app under test is now hot reloaded (the state is cleared) instead of shutdown, rebuilt and restarted which provides a huge speed boost for the tests.

Thanks,

Jon
