### ISSUE TITLE
How to set environment variables from command line

### ISSUE THREAD

**Issue by vhoang1102** [jonsamwell/flutter_gherkin#211]
Hi all, 

I'm looking for a way to set environment variables from command line, I have tried with "--dart-define" but not successfully. My running test command is "`dart app_test.dart`", so I expect something like "`dart app_test.dart -e DATADOG=true`"

Thanks

**Comment by jonsamwell** [comment]
This is how I am going it using the RC release

```
flutter drive --driver=test/integration/test_driver.dart --target=test/integration/suites/gherkin_suite_test.dart --flavor development --dart-define=targetConfig=dev --dart-define=tagExpression="not @ignore and @smoke"
```
