### ISSUE TITLE
How to pass multiple tags in configuration.dart ?

### ISSUE THREAD

**Issue by skumar11pk** [jonsamwell/flutter_gherkin#212]
I am using the below format and getting the error:

Feature File:
@smoke
  Scenario: User test
  Given I test it

@regression
  Scenario: User test
  Given I test it

Format:
..tagExpression = '@smoke and @regression'

Getting error in console:
Ignoring scenario `User test` as tag expression `@smoke and @regression` not satisfied

**Comment by jonsamwell** [comment]
That is expected as it is boolean logic. None of the tests have both the @smoke and @regression tag.  You want to use the or conjunction.

```
@smoke or @regression
```
