### ISSUE TITLE
Be able to add text to the JSON report

### ISSUE THREAD

**Issue by Stephane99** [jonsamwell/flutter_gherkin#216]
Hi,

How can I add more details in the report using world.attach()?

When a step is in error, I get the screenshot in the json file, and in the Html report (generated with Cucumber HTML Reporter).

Sometimes the step is in error when comparing an array of values with expect().
In this case I would like to get the results of the expect() in the report.

I tried to add text to JSON file with world.attach() in step body but no success.
How to implement world.attach() to add more text?

Example step definition:

```
StepDefinitionGeneric givenFooBar() =>
    given<FlutterWorld>(RegExp(r'Foo bar$'), (context) async => context.world.attach('More details', 'text/plain'));
```

Note: the same question has been partially processed in this post.
https://github.com/jonsamwell/flutter_gherkin/issues/26#issuecomment-505109481

Thanks for your help.

**Comment by jonsamwell** [comment]
I think this is now doing what you want.  The exceptions or `expect` failure reasons are now added to the json report.  Please get the latest rc version 3.0.0-rc.16

![image](https://user-images.githubusercontent.com/3694497/176817638-eb6e251b-aea2-4767-96fe-5a2601f0f4e4.png)
