### ISSUE TITLE
Tests not starting if the application has an infinite loop animation in the first view

### ISSUE THREAD

**Issue by youssef-t** [jonsamwell/flutter_gherkin#217]
Hello everyone,

I am using the integration test package version of flutter_gherkin. 
In order to configure the tests, we have to specify the entry point to the application (its main function) in the function `executeTestSuite`.

At the start of the test execution, the main function of the application is called using the method `startApp` contained in the following file: [https://github.com/jonsamwell/flutter_gherkin/blob/integration_test__package_support/lib/src/flutter/runners/gherkin_integration_test_runner.dart](https://github.com/jonsamwell/flutter_gherkin/blob/integration_test__package_support/lib/src/flutter/runners/gherkin_integration_test_runner.dart) .
<p align="center">
  <img src="https://user-images.githubusercontent.com/57002709/161987362-6e64a7e9-d5b7-4a71-a5ca-c70618e560d5.png" />
</p>

Calling `pumpAndSettle` is a really good approach to ensure that application is "loaded" by ensuring that there are no longer any frames scheduled. 
The problem is that, if the application has an infinite loop animation in the first view, the test is stuck at the start and the steps will never be executed  (until the timeout is exceeded and the test fails).

One solution to this problem is to have an option to call a simple `tester.pump` with a certain duration.

**Comment by jonsamwell** [comment]
Hi,

Yes this is a good point, I think there is a similar issue resolved in this PR that could be worth thinking about - instead of implicitly calling pumpAndSettle on every action (including startup) let the implementor have more control over this somehow?

https://github.com/jonsamwell/flutter_gherkin/pull/204/files

I'll give it some thought

**Comment by jonsamwell** [comment]
Should be fixed in the latest release `3.0.0-rc.10`

Although the app needs to pump after it is created to initialise but the new release buts a duration and timeout on the pump and settle
