### ISSUE TITLE
Retry test scenario in case of failure

### ISSUE THREAD

**Issue by olerudyshyn** [jonsamwell/flutter_gherkin#218]
Does flutter_gherkin supports test scenario retry in case of failure? Let's say I would like to retry test up to 3 times if it fails, since the test could be flaky due to long wait of data from third party service(some times).

**Comment by jonsamwell** [comment]
Yes this would be something good to get in

**Comment by AFASbart** [comment]
I have been working on this part for a bit, I hope to finish this in the near future. If anyone wants to also work on this, I can add you to the repository

**Comment by jonsamwell** [comment]
@AFASbart this would be excellent

**Comment by AFASbart** [comment]
I have made this, it seems to work and it can be configurable. I will create a PR tonight.

**Comment by jonsamwell** [comment]
Should be fixed in the latest release `3.0.0-rc.10`
