### ISSUE TITLE
 -- AppModule DISPOSED error after first scenario run and no further scenario gets executed

### ISSUE THREAD

**Issue by amitkumar-qa** [jonsamwell/flutter_gherkin#219]
Hi @jonsamwell 

In my feature file there are more than one scenario , but i am not able to run all scenarios as it runs only first scenario and after that getting  -- AppModule DISPOSED error due to which next scenario doesnt run.
Note: I am using integration test package with latest RC build -flutter_gherkin

**Comment by jonsamwell** [comment]
This sounds like a problem with your application rather than the library.
Remember all tests are atomic so your app is restarted after every test.
Perhaps you have some static dependencies that are not reset? If you can
provide a simple code sample that reproduces the error that would be good.

**Comment by amitkumar-qa** [comment]
@jonsamwell 
Sample code:


1. Gherkin suite test dart file:
`import 'package:gherkin/gherkin.dart';

// The application under test.
import 'package:appPackage/main.dart' as app;

import 'gherkin/configuration.dart';

part 'gherkin_suite_test.g.dart';

@GherkinTestSuite()
void main() {
  executeTestSuite(
    gherkinTestConfiguration,
        (World world) => app.main(),
  );
}`

2. Feature file:
`Feature: Login page scenarios

  Scenario: Scenario-1
    When I open the app
    Then User sees text "Welcome Back."
    Then User sees text "Sign in to your account"
    Then User sees text "Forgot Password?"
    Then User login with username "username" and password "password"
    Then User set location as "Mobile location"

  Scenario: Scenario-2
    When I open the app
    Then User sees text "Welcome Back."
    Then User sees text "Sign in to your account"
    Then User sees text "Forgot Password?"
    Then User login with username "username" and password "password"
    Then User set location as "Mobile location"`

3. Configuration file:
`FlutterTestConfiguration gherkinTestConfiguration =
FlutterTestConfiguration.DEFAULT([],)
  ..stepDefinitions = [
    iOpenTheApp(),
    iExpectToFindTheText(),
    userLogin(),
    setUserLocation()
  ]
  ..hooks = [AttachScreenshotStepHook()]
  ..reporters = [
    StdoutReporter(MessageLevel.error)
      ..setWriteLineFn(print)
      ..setWriteFn(print),
    ProgressReporter()
      ..setWriteLineFn(print)
      ..setWriteFn(print),
    TestRunSummaryReporter()
      ..setWriteLineFn(print)
      ..setWriteFn(print),
    JsonReporter(writeReport: (_, __) => Future<void>.value())
  ]
  ..features = [RegExp('features/*.*.feature')];
`
4. Logs:-----------------------------------------

`I/flutter (21160): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (21160): │ #0   AttachScreenshotStepHook.onAfterStep (file:///Users/amitkumar/Desktop/highlevel-flutter/integration_test/gherkin/hooks/screenshots_hooks.dart:58:12)
I/flutter (21160): │ #1   AggregatedHook.onAfterStep.<anonymous closure> (package:gherkin/src/hooks/aggregated_hook.dart:85:35)
I/flutter (21160): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (21160): │ 💡 onAfterStep 'Then User set location as "Mobile location"' StepExecutionResult.pass
I/flutter (21160): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (21160):    √ Then User set location as "Mobile location" # :0 took 8370ms
I/flutter (21160):      Attachment (image/png)
I/flutter (21160): PASSED: Scenario Scenario-1 # :0
I/flutter (21160): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (21160): │ #0   AttachScreenshotStepHook.onAfterScenario
(file:///Users/amitkumar/Desktop/highlevel-flutter/integration_test/gherkin/hooks/screenshots_hooks.dart:32:12)
I/flutter (21160): │ #1   AggregatedHook.onAfterScenario.<anonymous closure> (package:gherkin/src/hooks/aggregated_hook.dart:63:18)
I/flutter (21160): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (21160): │ 💡 running hook after scenario 'Scenario-1'
I/flutter (21160): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
**I/flutter (21160): -- AppModule DISPOSED**
I/flutter (21160): 00:18 +1: Login page scenarios: Scenario-2
I/flutter (21160): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (21160): │ #0   AttachScreenshotStepHook.onBeforeScenario
(file:///Users/amitkumar/Desktop/highlevel-flutter/integration_test/gherkin/hooks/screenshots_hooks.dart:41:12)
I/flutter (21160): │ #1   AggregatedHook.onBeforeScenario.<anonymous closure> (package:gherkin/src/hooks/aggregated_hook.dart:48:18)
I/flutter (21160): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (21160): │ 💡 running hook before scenario 'Scenario-2'
I/flutter (21160): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (21160): PASSED: Scenario Scenario-2 # :0
I/flutter (21160): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (21160): │ #0   AttachScreenshotStepHook.onAfterScenario
(file:///Users/amitkumar/Desktop/highlevel-flutter/integration_test/gherkin/hooks/screenshots_hooks.dart:32:12)
I/flutter (21160): │ #1   AggregatedHook.onAfterScenario.<anonymous closure> (package:gherkin/src/hooks/aggregated_hook.dart:63:18)
I/flutter (21160): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (21160): │ 💡 running hook after scenario 'Scenario-2'
I/flutter (21160): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (21160): 00:18 +1: Login page scenarios: Scenario-2 [E]
I/flutter (21160):   'package:flutter_test/src/binding.dart': Failed assertion: line 775 pos 14: '_pendingExceptionDetails != null': A test overrode FlutterError.onError but
either failed to return it to its original state, or had unexpected additional errors that it could not handle. Typically, this is caused by using expect() before restoring
FlutterError.onError.
I/flutter (21160):   dart:core-patch/errors_patch.dart 51:61       _AssertionError._doThrowNew
I/flutter (21160):   dart:core-patch/errors_patch.dart 40:5        _AssertionError._throwNew
I/flutter (21160):   package:flutter_test/src/binding.dart 775:14  TestWidgetsFlutterBinding._runTest.handleUncaughtError
I/flutter (21160):   package:flutter_test/src/binding.dart 780:9   TestWidgetsFlutterBinding._runTest.<fn>
I/flutter (21160):   dart:async/zone.dart 1109:14                  _Zone._processUncaughtError
I/flutter (21160):   dart:async/zone.dart 1312:5                   _CustomZone.handleUncaughtError
I/flutter (21160):   dart:async/future_impl.dart 716:16            Future._propagateToListeners
I/flutter (21160):   dart:async/future_impl.dart 609:5             Future._completeError
I/flutter (21160):   dart:async-patch/async_patch.dart 272:13      _completeOnAsyncError
I/flutter (21160):   package:flutter_test/src/binding.dart         TestWidgetsFlutterBinding._runTestBody
I/flutter (21160):   
I/flutter (21160): 00:18 +1 -1: (tearDownAll)
I/flutter (21160): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (21160): │ #0   AttachScreenshotStepHook.onAfterRun (file:///Users/amitkumar/Desktop/highlevel-flutter/integration_test/gherkin/hooks/screenshots_hooks.dart:24:12)
I/flutter (21160): │ #1   AggregatedHook.onAfterRun.<anonymous closure> (package:gherkin/src/hooks/aggregated_hook.dart:24:35)
I/flutter (21160): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (21160): │ 💡 onAfterRun
I/flutter (21160): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (21160): 2 scenarios (2 passed)
I/flutter (21160): 6 steps (6 passed)
I/flutter (21160): 0:00:18.400000
I/flutter (21160): 00:18 +2 -1: Some tests failed.
All tests passed.
`
Note: in logs -----it does nothing for second scenario, and it displays second scenario as passed , however second scenario didnt get executed

**Comment by jonsamwell** [comment]
@amitkumar-qa I am afraid there isn't enough to go on here.  The problem is clearing in your app code.  If you can create a sample repo with this problem I can take a look.  As I mentioned before it looks like in your AppModule disposed isn't being handled correctly indicating you might have some statics somewhere?

**Comment by amitkumar-qa** [comment]
@jonsamwell We are using modular structure in our app code :
Sample main.dart look like this:

**Comment by amitkumar-qa** [comment]
@jonsamwell found an alternative solution by changing some code in main function of the app. Thank you for your support
