### ISSUE TITLE
test exit without failed but didn't execute all scenario

### ISSUE THREAD

**Issue by linchen2chris** [jonsamwell/flutter_gherkin#224]
Hi, I put a tests which have 34 test scenarios, but it will exit after only run 5 or 6 scenarios, I check the report and find the scenarios are all success, I can't understand why this happen

**Comment by jonsamwell** [comment]
Could you try again in the latest release `3.0.0-rc.10`

**Comment by jonsamwell** [comment]
Can you give this a go in the latest release 3.0,0-rc-11 and include the verbose output if it is still failing

**Comment by jonsamwell** [comment]
Closing for now.  Feel free to re-open with reproduction steps
