### ISSUE TITLE
Branch `integration_test__package_support` not compatible with `dart_gherkin`

### ISSUE THREAD

**Issue by golane-august** [jonsamwell/flutter_gherkin#226]
Hey there,
since there is a version restriction for package dependency, I wanted to make a [PR](https://github.com/jonsamwell/flutter_gherkin/pull/227) to solve this to be compatible to other dependencies in my app. 
So I wanted to compile the project for `integration_test__package_support` , but either dart_`gherkin` version `2.0.8` nor the master branch `git: 'https://github.com/jonsamwell/dart_gherkin.git'` can be compiled in the mentioned branch. 
Can you plz fix and release this, for current `gherkin/master` linter of `flutter_gherkin` is complaining for `reporters` and `stepDefinitions` to be final? 

Thank you! Sorry you may can also publish release candidates more often, if you find the time to do so. Big thanks!

**Comment by jonsamwell** [comment]
Hi @golane-august I'm taking a look at this now

**Comment by jonsamwell** [comment]
Should be fixed in the latest release `3.0.0-rc.10`
