### ISSUE TITLE
[Question] How can we add the device and os version in the JSON report? 

### ISSUE THREAD

**Issue by umangdivyanshu** [jonsamwell/flutter_gherkin#228]
Hi @jonsamwell 

I am trying to add the device info into the report. I am able to get the device info using device_info_plus package but how could I add this info into the json/html report during runtime?

Thanks in advance.

**Comment by jonsamwell** [comment]
You can add a report attachments

```
context.world.attach('DEVICE INFO', 'text/plain');
```
