### ISSUE TITLE
Exception: Guarded function conflict error during tap in latest RC 3.0.0-rc.9

### ISSUE THREAD

**Issue by amitkumar-qa** [jonsamwell/flutter_gherkin#231]
@jonsamwell Getting error while taping on element in android ,
Below function gives error:
Future<void> selectClientDetails(String contactName) async { await appDriver.tap(clientDropdown); }
In above function appDriver is object of AppDriverAdapter.

Error below:

`I/flutter ( 7983): × Then User selects client "[test@test.com](mailto:test@test.com)" # :0 took 3ms
I/flutter ( 7983): Exception: Guarded function conflict.
I/flutter ( 7983): You must use "await" with all Future-returning test APIs.
I/flutter ( 7983): The guarded method "pumpAndSettle" from class WidgetTester was called from package:flutter_gherkin/src/flutter/adapters/widget_tester_app_driver_adapter.dart
on line 21.
I/flutter ( 7983): Then, the "selectClientDetails" method from class InvoiceDetailsPage was called from
file:///Users/ak/repo/integration_test/gherkin/steps/invoice_steps/invoice_details_page_steps.dart on line 10.
I/flutter ( 7983): The first method (WidgetTester.pumpAndSettle) had not yet finished executing at the time that the second method (InvoiceDetailsPage.selectClientDetails) was
called. Since both are guarded, and the second was not a nested call inside the first, the first must complete its execution before the second can be called. Typically, this is
achieved by putting an "await" statement in front of the call to the first.
I/flutter ( 7983):
I/flutter ( 7983): When the first method (WidgetTester.`

**Comment by jonsamwell** [comment]
@amitkumar-qa could you add your code here for that step.  I can't see any unawaited calls to pumpAndSettle

**Comment by jonsamwell** [comment]
Actually I think this is solved by this PR #230 

You could try that branch and see if you experience the same issue

**Comment by amitkumar-qa** [comment]
@jonsamwell Yes might be, leme try this branch

**Comment by jonsamwell** [comment]
@amitkumar-qa could you give this a go in the latest rc relesae `3.0.0-rc.10`?

**Comment by amitkumar-qa** [comment]
@jonsamwell Sure , let me check

**Comment by jonsamwell** [comment]
Thanks

**Comment by WernerRaathAtPolymorph** [comment]
FYI If you create your own step file using the exact same code as for [tap_widget_with_text_step.dart](https://github.com/jonsamwell/flutter_gherkin/blob/integration_test__package_support/lib/src/flutter/steps/tap_widget_with_text_step.dart), rename all cases of `tap` to something like `click` and omit the `await context.world.appDriver.waitForAppToSettle();` line, it actually succeeds.

I believe the issue here is with `await context.world.appDriver.waitForAppToSettle();`. @amitkumar-qa could you try this and see if it solves your issue?

**Comment by WernerRaathAtPolymorph** [comment]
I can confirm that this error happens before Scenarios as well. This issue is also intermittent. Could be a race condition?

**Comment by jonsamwell** [comment]
Should be fixed in Fixed in 3.0,0-rc-11

**Comment by jonsamwell** [comment]
You should be able to set the configuration parameter  `
waitImplicitlyAfterAction`
to false to stop the implicit pump and settle actions.

**Comment by amitkumar-qa** [comment]
@jonsamwell I tried with waitImplicitlyAfterAction`=true.
Even after i am getting below error

`══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following assertion was thrown running a test:
Guarded function conflict.
You must use "await" with all Future-returning test APIs.
The guarded method "pumpAndSettle" from class WidgetTester was
called from
package:flutter_gherkin/src/flutter/adapters/widget_tester_app_driver_adapter.dart
on line 42.
Then, it was called from
package:flutter_gherkin/src/flutter/runners/gherkin_integration_test_runner.dart
on line 530.
The first method had not yet finished executing at the time that
the second method was called. Since both are guarded, and the
second was not a nested call inside the first, the first must
complete its execution before the second can be called.
Typically, this is achieved by putting an "await" statement in
front of the call to the first.
`

**Comment by jonsamwell** [comment]
@amitkumar-qa try the new rc-15 release, I've removed the default frame binding policy as it was set to benchmarking which can not schedule all frames.

**Comment by amitkumar-qa** [comment]
@jonsamwell I will check and update you on this soon
