### ISSUE TITLE
Q: Why does each Scenario run all steps for the previous scenarios before its own within a feature?

### ISSUE THREAD

**Issue by WernerRaathAtPolymorph** [jonsamwell/flutter_gherkin#233]
Is there a way to override this behaviour?

**Comment by jonsamwell** [comment]
@WernerRaathAtPolymorph Could you clarify what you mean by this? A scenario should only run the steps contained within it unless there is a background keyword preceding it.

**Comment by jonsamwell** [comment]
Thanks for this it's perfect! I wish everyone did this!

It's odd, we have tests that cover more than one scenario is a single feature file so I am not sure why this doesn't work.  I'll have time to look at this tomorrow.

**Comment by jonsamwell** [comment]
Fixed in 3.0,0-rc-11
