### ISSUE TITLE
Error while taking screenshot after step in 3.0,0-rc-11

### ISSUE THREAD

**Issue by amitkumar-qa** [jonsamwell/flutter_gherkin#235]
@jonsamwell Getting error while taking screenshot after step execution, Could you please provide work around ASAP if possible because reports without screenshots doesnt make much sense?
 Note:-in 3.0,0-rc-9 , It was working fine.

Sample code and error below:
AttachScreenshotStepHook.onAfterStep function:

```
Run after a step has executed
  @override
  Future<void> onAfterStep(
      World world, String step, StepResult stepResult) async {
    logger.i("onAfterStep '$step' ${stepResult.result}");
    try {
      final screenshotData = await takeScreenshot(world);
      world.attach(screenshotData, 'image/png', step);
    } catch (e, st) {
      world.attach('Failed to take screenshot\n$e\n$st', 'text/plain', step);
    }
    return super.onAfterStep(world, step, stepResult);
  }
}

Future<String> takeScreenshot(World world) async {
  final bytes = await (world as FlutterWorld).appDriver.screenshot();
  return base64Encode(bytes);
}
```

`tter (15208): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (15208):    - Then User clicks on create invoice button # :0 took 300ms 
I/flutter (15208):      Attachment (text/plain): Failed to take screenshot
I/flutter (15208): 'package:integration_test/_callback_io.dart': Failed assertion: line 73 pos 12: '!_isSurfaceRendered': Surface already converted to an image
I/flutter (15208): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
I/flutter (15208): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
I/flutter (15208): #2      IOCallbackManager.convertFlutterSurfaceToImage (package:integration_test/_callback_io.dart:73:12)
I/flutter (15208): #3      IntegrationTestWidgetsFlutterBinding.convertFlutterSurfaceToImage (package:integration_test/integration_test.dart:204:27)
I/flutter (15208): #4      WidgetTesterAppDriverAdapter.screenshot (package:flutter_gherkin/src/flutter/adapters/widget_tester_app_driver_adapter.dart:72:21)
I/flutter (15208): #5      takeScreenshot (file:///myrepo/integration_test/gherkin/hooks/screenshots_hooks.dart:72:57)
I/flutter (15208): #6      AttachScreenshotStepHook.onAfterStep
`

**Comment by jonsamwell** [comment]
What devices are the tests running on?

**Comment by amitkumar-qa** [comment]
@jonsamwell Pixel 5 and pixel 2 on emulators, and pixel 6 on real device.

**Comment by jonsamwell** [comment]
@amitkumar-qa it seems that on Android this functionality is actually broken / not implemented in the flutter intergration_test library see https://github.com/flutter/flutter/issues/92381.

So I am not really sure what I can do here at the moment as it seems you can only take one screenshot per test because of this issue.

**Comment by jonsamwell** [comment]
@amitkumar-qa I've replaced the old screenshot code for now so see if this works for you

**Comment by amitkumar-qa** [comment]
@jonsamwell Screenshots are appearing but complete screen is not visible in screenshots instead it is showing like zoomed image screen shot which only display left portion of the screen 
<img width="532" alt="Screenshot 2022-06-28 at 6 17 45 PM" src="https://user-images.githubusercontent.com/94505953/176182232-8277d0f4-5797-443b-99f2-411fbdb554a5.png">
Requesting your help to fix this.

**Comment by jonsamwell** [comment]
@amitkumar-qa I've tried for a bit but cannot fix this.  It seems the layer that is being turned into an image (the parent layer) thinks it is smaller than the viewport size.

**Comment by amitkumar-qa** [comment]
@jonsamwell It was work fine 3.0,0-rc-9, Could you please revert the screenshot code as fix if possible ? Otherwise it will be difficult for our test report without screenshots.
Looking forward to hearing from you soon

**Comment by jonsamwell** [comment]
@youssef-t thanks for the pointer, that seems to work using the local coordinate system.  The is release in version 3.0.0-rc.16

**Comment by amitkumar-qa** [comment]
@jonsamwell works like a charm in 3.0.0-rc.16 
@youssef-t Really appreciate your suggestion. 

Thanks guys
