### ISSUE TITLE
flavor does not work

### ISSUE THREAD

**Issue by bmelnychuk** [jonsamwell/flutter_gherkin#24]
I think there is a problem with this line should not it be flavor instead of the target?

 ```
   if (_buildFlavor.isNotEmpty) {
      arguments.add("--target=$_appTarget");
    }
```

https://github.com/jonsamwell/flutter_gherkin/blob/9a67721650ddb3c571409f813711bde79ea6f76b/lib/src/flutter/flutter_run_process_handler.dart#L46

**Comment by jonsamwell** [comment]
@bmelnychuk Thanks for this.  There was a pending PR fixing this issue that has now been merged into the master branch.  I am aiming to get this published in the next couple of days.

https://github.com/jonsamwell/flutter_gherkin/blob/master/lib/src/flutter/flutter_run_process_handler.dart#L46
