### ISSUE TITLE
waitImplicitlyAfterAction parameter does not work

### ISSUE THREAD

**Issue by Ekhart86** [jonsamwell/flutter_gherkin#240]
Hi, I am using the latest version of flutter_gherkin 3.0.0-rc.16. I have a lot of endless animations in my application and despite the fact that the waitImplicitlyAfterAction: false parameter was added, it does not help me, and my tests continue to hang for 10 minutes due to the pumpAndSettle() method.
I had to modify the _appLifecyclePhasePumper method to somehow solve this problem. Please fix this...

```
 Future<void> _appLifecyclePhasePumper(
    FlutterTestConfiguration configuration,
    AppLifecyclePhase phase,
    WidgetTester tester,
  ) async {
    if (configuration.waitImplicitlyAfterAction) {
      if (appLifecyclePumpHandler != null) {
        await appLifecyclePumpHandler!(phase, tester);
      } else {
        await tester.pumpAndSettle();
      }
    }
  }
}
```

**Comment by jonsamwell** [comment]
@Ekhart86 you can provide your own appLifecyclePumpHandler function rather than modifying the code.  In your case it'll probably just be a no op.

```
import 'package:flutter_gherkin/flutter_gherkin.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:gherkin/gherkin.dart';

import 'gherkin/configuration.dart';

part 'gherkin_suite_test.g.dart';

@GherkinTestSuite(
  useAbsolutePaths: false,
)
void main() {
  executeTestSuite(
    appMainFunction: appInitializationFn,
    configuration: gherkinTestConfiguration,
    scenarioExecutionTimeout: Timeout(const Duration(minutes: 30)),
    // if your app has lots of endless animations you might need to
    // provide your own app lifecycle pump handler that doesn't pump
    // at certain lifecycle stages
    appLifecyclePumpHandler: (appPhase, widgetTester) => Future.value(),
  );
}
```

**Comment by Ekhart86** [comment]
Yes, you're right. I did not notice that it is possible to pass the appLifecyclePumpHandler from the executeTestSuite() function. This will solve the issue without interfering with the code. You can close the question, sorry)

**Comment by jonsamwell** [comment]
I'll add comments for the parameters on the `executeTestSuite()` to help users
