### ISSUE TITLE
Path in the test_suite_runner.g.dart file

### ISSUE THREAD

**Issue by Ekhart86** [jonsamwell/flutter_gherkin#241]
Hi! please tell me about the paths that are generated in the g.dart file. They are all generated from the user's home folder, and the console writes paths from my home folder, but not only I will run the tests, and the paths will be incorrect for others.

How can this be fixed?

<img width="1103" alt="Снимок экрана 2022-07-04 в 14 22 16" src="https://user-images.githubusercontent.com/25115868/177135706-378f520e-e38d-4e7c-84a4-04f1254588be.png">

**Comment by jonsamwell** [comment]
Please check the changelog but the path can be made relative by setting the
property on the GherkinTestSuite attribute.

https://github.com/jonsamwell/flutter_gherkin/blob/integration_test__package_support/CHANGELOG.md#300-rc11---24062022

**Comment by Ekhart86** [comment]
Thanks a lot! You can close this issue!)
