### ISSUE TITLE
Redundant feature file path escape 

### ISSUE THREAD

**Issue by youssef-t** [jonsamwell/flutter_gherkin#245]
Hello,

In the generated test file, we have the following:
https://github.com/jonsamwell/flutter_gherkin/blob/7ee9f801d1ddd201a95d46fa6130a86ab209ebb0/example_with_integration_test/integration_test/gherkin_suite_test.g.dart#L305

The additionnal backslashes are redundant because of the use of the raw string declaration (starting with `r'...'`): we don't need to use .  As a result, the reporters that implement [FeatureReporter](https://github.com/jonsamwell/dart_gherkin/blob/6b29b9a384baefb9ee2919cabb110e4ada833ef3/lib/src/reporters/reporter.dart#L75) don't get the feature file path correctly.
For example, the JSON report contains the following uri:
`"uri":".\\\\integration_test\\\\features\\\\create.feature"`

The issue concerns only `onBeforeRunFeature` and `onAfterRunFeature` methods.

**Comment by jonsamwell** [comment]
Thanks, I'll get this merge in over the weekend!
