### ISSUE TITLE
Q: Is it possible to only run the feature files you're currently writing?

### ISSUE THREAD

**Issue by WernerRaathAtPolymorph** [jonsamwell/flutter_gherkin#247]
I've been commenting-out feature file code in order to only focus on the feature files I'm busy writing. Is there another way for me to do this? My current approach won't scale well

**Comment by youssef-t** [comment]
I recommend you to use special tags for the scenarios that you want to run (the ones that you're writing). As a result, you will be able to filter them.

For more details, you can check the following issue #178.

**Comment by WernerRaathAtPolymorph** [comment]
Brilliant! Thanks!
