### ISSUE TITLE
Writing step definitions using annotations

### ISSUE THREAD

**Issue by nightscape** [jonsamwell/flutter_gherkin#25]
Hi @jonsamwell, thanks for writing this library.
I'm a relative Flutter noob, but have been working with Cucumber in a few other languages.
In most of those, a step definition is represented by a method with an annotation containing the RegEx part and some code generation / macro magic searches for such annotations, parses the method signature, aligns it with the RegEx and generates the required code.
Afais Dart's [source_gen](https://github.com/dart-lang/source_gen) should be capable of doing sth. like this.
Have you thought about this and do you think it would work?

**Comment by nightscape** [comment]
Just found [ogurets](https://pub.dev/packages/ogurets) which seems to do this.

**Comment by jonsamwell** [comment]
Hi @nightscape 

Thanks for trying out the library!

Yes I have toyed with the idea of using annotations after having written the library using simple atomic classes for step definitions.  I understand this is a bit less accessible though.  I wonder if something akin to the way CucumberJs does it would be better than annotations?

```

When<int>(
  r"a person who is {int} years old",
 Future<void> (age: int) async {
   // implementation
});

// or

WhenWithWorld<string, int>(
 r"a person called {string} who is {int} years old",
Future<void> (name: string, age: int, world: World) async {
 // implementation
});

**Comment by jonsamwell** [comment]
@nightscape how would debugging work with annotations and code generation?

**Comment by nightscape** [comment]
Good questions, I don't have much experience with how debugging interacts with generated code, but I would hope that one can just set breakpoints in generated code. After all it's just normal Dart code that happens to be generated. It's also in the same directory as the normal sources, so I'd assume it just gets treated the same.

**Comment by rvowles** [comment]
@jonsamwell Irina and my IDEA plugin works well with ogurets, it is a full integrated cucumber environment. Currently our only issue is with Android Studio which is using an old Dart.

**Comment by DhonyImamS** [comment]
> Hi @nightscape
> 
> Thanks for trying out the library!
> 
> Yes I have toyed with the idea of using annotations after having written the library using simple atomic classes for step definitions. I understand this is a bit less accessible though. I wonder if something akin to the way CucumberJs does it would be better than annotations?
> 
> ```
> 
> When<int>(
>   r"a person who is {int} years old",
>  Future<void> (age: int) async {
>    // implementation
> });
> 
> // or
> 
> WhenWithWorld<string, int>(
>  r"a person called {string} who is {int} years old",
> Future<void> (name: string, age: int, world: World) async {
>  // implementation
> });
> ```

i hope this will be implemented also, so that there's no way we should define each step in configuration file for flutter gherkin work to scan step definition class like it does currently

**Comment by lukasgarcya** [comment]
I can help generation code that it create the class. I have this project for generation code https://github.com/crud-Flutter

**Comment by jonsamwell** [comment]
@lukasgarcya you are welcome to provide a PR for this

However, I do like the atomic approach of a class per step as it make them much more reusable

**Comment by atmaramnaik** [comment]
flutter_gherkin_addons lib was written with same intention to provide dsl like constucts for creating step definations e.g.
GenericThen2 thenISeeSomethingAsSomethingOnDetailsPage(){
  return then2("I See {string} as {string}",(context,String text,String within) async  {
    final locator = find.byValueKey(within);
    context.expectMatch(await FlutterDriverUtils.getText(context.world.driver, locator,timeout: context.timeout), text);
  });
}

**Comment by jonsamwell** [comment]
@atmaramnaik yes I actually saw this yesterday, nice work!  I wonder if we should pull this into the main repo as is it a great shorthand way of creating steps.  It would be good to be able to specify the world type and pass in step configuration like timeouts.

Let me know your thoughts.

**Comment by atmaramnaik** [comment]
@jonsamwell Thanks for giving it thought. Yes, would raise a PR and once they are here will rely on them in other repo. Meanwhile that  repo is for putting together different tools (name is misleading) that can make testing simpler (like stubbing utility etc which i think may not suit here).

**Comment by jonsamwell** [comment]
@atmaramnaik yes agree things like stubbing and extra functionality belong in another library.  However, I think having a shorthand way of creating steps like in your library would be a good addition here.  Feel free to send a PR and we can work it in

**Comment by DenisBronx** [comment]
@jonsamwell I used Cucumber in the past and I tried out Ogurets too (very nice lib!) however I think the combination of `flutter_gherkin` and `flutter_gherkin_addons` gives a better result if used in the following way:

```
class MyFeatureSteps {

  Iterable<StepDefinitionBase> get steps => [
        given("my given step", (_) {
          // given step
        }),
        when("my when step",
            (_) {
          // when step
        }),
        then("my then step", (_) {
          // then step
        })
      ];
}
```
and the `app_test.dart` would look like
```
Future<void> main() {
  final config = FlutterTestConfiguration()
    ..flutterBuildTimeout = const Duration(minutes: 4)
    ..features = [Glob("test_driver/**/features/**.feature")]
    ..reporters = [ // reporters ]
    ..stepDefinitions = [
      ...MyFeatureSteps.steps
    ]
    ..targetAppPath = "test_driver/app.dart";
  return GherkinRunner().execute(config);
}
```

This removes the need for importing every single step and also unlike `Cucumber` or `Ogurets` you don't have the boilerplate of creating a method for each annotation like:

```
@Given('my given step')
  void myGivenStep() { // usually the method is named like the step and is redundant
    // given step
  }
```

**Comment by jonsamwell** [comment]
@DenisBronx I have created the function step syntax in the library now see my comment here https://github.com/jonsamwell/flutter_gherkin/issues/68#issuecomment-660576493

It is slightly different from that implemented in flutter_gherkin_addons so it is a bit more flexible but thanks to them for the initial idea!

I too do my steps similar to you but I modulise them a bit more depending on the areas of the app.

```
class AuthenticationSteps {
  static Iterable<StepDefinitionGeneric> STEPS = [
    StepOne(),
    StepFive(),
  ];

  static StepDefinitionGeneric StepOne() => given(
        'some step',
        (context) async {
          // do something
        },
      );

  static StepDefinitionGeneric StepFive() => given2<String, int, FlutterWorld>(
        'step five with {string} and {int}',
        (str, value, context) async {
          // do something
        },
      );
}

class AccountSteps {
  static Iterable<StepDefinitionGeneric> STEPS = [
    StepOne(),
    StepFive(),
  ];

  static StepDefinitionGeneric StepOne() => given(
        'some step account step',
        (context) async {
          // do something
        },
      );

  static StepDefinitionGeneric StepFive() => given2<String, int, FlutterWorld>(
        'step five with {string} and {int}',
        (str, value, context) async {
          // do something
        },
      );
}
```

Then in my configuration file:

```
Future<void> main() {
  final steps = [
    ...AuthenticationSteps.STEPS,
   ...AccountSteps.STEPS,
  ];

  final config = FlutterTestConfiguration.DEFAULT(steps);
  return GherkinRunner().execute(config);
}
```

**Comment by atmnk** [comment]
@jonsamwell thanks for accomodating that idea and sorry was bit occupied and couldn't create that PR. will update addons library to remove that redundancy and focus on other areas like stubbing etc.

**Comment by jonsamwell** [comment]
@atmnk thanks for the excellent idea!  No worries about the PR open source is very time consuming!

**Comment by frestoinc** [comment]
Hi @jonsamwell, question. 

Is there an option within the FlutterTestConfiguration to do a fresh installation on every run?

A scenario like login page, when user credentials already exist, screen will navigate to home page so test related to login page will fail due to timeoutexception

**Comment by jonsamwell** [comment]
@frestoinc you have the `restartAppBetweenScenarios` configuration parameter but what I think you need to do is clear the state in the app before each test starts.  If you choose to uninstall the app every time your tests will become painfully slow.  Please see my comment here https://github.com/jonsamwell/flutter_gherkin/issues/46#issuecomment-584462881 about using the `requestData` method on the driver to instruct the app to clear it's state i.e. delete the current logged in user and return to the login page etc.

Also if you require further help with this please create a new issue so this issue doesn't get polluted.
