### ISSUE TITLE
Reporter doesn't await for test.onStarted callback

### ISSUE THREAD

**Issue by SashaKryzh** [jonsamwell/flutter_gherkin#252]
The **test.onStarted** callback is not finished, but the **feature.onStarted** is already called.

Also, as I understood none of them are awaited. So what is the point of making them async?

My goal is to report data to the server, and I need to receive IDs for each feature, scenario, and step and later use these ids to finish them on the server.

flutter_gherkin: 3.0.0-rc.16

**Comment by jonsamwell** [comment]
It should be. I can't see any unawaited futures

https://github.com/jonsamwell/flutter_gherkin/blob/integration_test__package_support/lib/src/flutter/runners/gherkin_integration_test_runner.dart#L213

Are you able to do a sample that reproduces this error?

**Comment by SashaKryzh** [comment]
What about this line

https://github.com/jonsamwell/flutter_gherkin/blob/4378a2447d0e8d358cf746a22001871b754ccb83/lib/src/flutter/runners/gherkin_integration_test_runner.dart#L92

**Comment by jonsamwell** [comment]
Good spot! I'll look at fixing this tomorrow.

**Comment by jonsamwell** [comment]
Fixed in 3.0.0-rc.17
