### ISSUE TITLE
Features whose description contains more than one line are not built

### ISSUE THREAD

**Issue by Stephane99** [jonsamwell/flutter_gherkin#253]
Hi,
I usually add information about each feature.
E.g.
```
@feature_date_properties_edition
Feature: Edit document Date properties

	Tests covered:
	- User can select a date in the future or past via the date picker calendar,
	- User can set a date in the future or past via the date picker input,
	- An empty date property displays a placeholder ”DD/MM/YYYY” (FR/EN) or ”MM/DD/YYYY” (US).
```
But the description (that is here on 4 lines),  is not accepted when trying to generate the .part files with the commands:

    flutter pub run build_runner clean
    flutter pub run build_runner build --delete-conflicting-outputs

Eg.

    line 426, column 26 of .: Expected to find ','.
        ╷
    426 │ - User can set a date in the future or past via the date picker input,
        │                          ^^^
        ╵
    line 427, column 84 of .: Illegal character '8221'.
        ╷
    427 │ - An empty date property displays a placeholder ”DD/MM/YYYY” (FR/EN) or ”MM/DD/YYYY” (US).", tags:<String>['@feature_display_attachments_from_dms_document_in_creation'],),
        │                                                                                    ^
        ...
When I merge all lines in one, the build is in success.

Eg.

    Tests covered: - User can select a date in the future or past via the date picker calendar, - User can set a date in the future or past via the date picker input, - An empty date property displays a placeholder ”DD/MM/YYYY” (FR/EN) or ”MM/DD/YYYY” (US).

It now seems to accept only one line description.

Releases:
Multi-line descriptions were supported until the release 3.0.0-rc9.
This error appears at the latest with the release 3.0.0-rc16.

**Comment by jonsamwell** [comment]
Fixed in 3.0.0-rc.17

**Comment by Stephane99** [comment]
Thanks :)
It works well on my side.

**Comment by jonsamwell** [comment]
Awesome
