### ISSUE TITLE
It seems when we have any element with text dynamically set, it cannot be found by appDriver

### ISSUE THREAD

**Issue by cjmeyer-polymorph** [jonsamwell/flutter_gherkin#254]
E.g.  
```
TextButton(
              onPressed: () => doSomething(),
              child: const Text(
                Strings.myTextForButton,
              ),
            ),
```

When we run `I tap the button that contains the text "Send"`, or `I expect the text "Title text here" to be present` or anything else that finds by text, it doesn't find it

**Comment by jonsamwell** [comment]
@cjmeyer-polymorph are you able to get a sample repo that reproduces this and I will look into it?
