### ISSUE TITLE
I can't take screenshots for web tests.

### ISSUE THREAD

**Issue by Ekhart86** [jonsamwell/flutter_gherkin#255]
Hello everyone, I use the package version 3.0.0-rc.16. When running android tests, screenshots are created successfully, but when running web tests, screenshots are not created, although when I used version 3.0.0-rc.9, they were definitely created. I can't understand what's the matter, can someone help me? I get this error that comes from the integration_test package
![Снимок экрана 2022-07-15 в 13 51 26](https://user-images.githubusercontent.com/25115868/179200554-633967ba-23ee-43f4-8812-f5809b7cfce6.png)
![Снимок экрана 2022-07-15 в 13 52 13](https://user-images.githubusercontent.com/25115868/179200579-1a9d34e2-b3ce-4582-a5d6-6a05b9a949de.png)

I will be glad of any help!
P.S. The browser version and driver are selected correctly.

**Comment by jonsamwell** [comment]
@Ekhart86 are you able to get a sample repo that reproduces this and I will look into it?

**Comment by Ekhart86** [comment]
Okay I will prepare a separate test project and later I will send a link to it

**Comment by jonsamwell** [comment]
Much appreciated

**Comment by Ekhart86** [comment]
I created a basic application with a counter, made a mistake in the first and only step, and added a screenshot hook. Now if I run the test, it freezes at the screenshot creation stage and hangs indefinitely. if I remove the hook, the test immediately ends with an error. The example is not exactly the same as mine, but it also has the same problem with screenshots.
I think if it works in this test project, it will work with me.
I checked on browser version 103.0.5060.114. Macbook m1.

https://github.com/Ekhart86/web_screenshot_issue

Please see what I'm doing wrong.
