### ISSUE TITLE
Can not generate the suite part file when a step contains some special characters

### ISSUE THREAD

**Issue by Stephane99** [jonsamwell/flutter_gherkin#257]
Hi,
I have an error when trying to generate the suite part file for a feature with a step that contains a regular expression.

The step is:

`And the document property "String property" displays a Value-must-match-the-validation-rule error message with the rule "^[A-Z]{3}\\d{5}\$"`

The last part is no longer accepted now in version 3.0.0-rc16.
It is accepted with the previous version 3.0.0-rc9.

Here is the error in log:

```
[SEVERE] flutter_gherkin:gherkin_test_suite on integration_test/gherkin/suites/workflow/workflow_finalize_and_force_transitions_test.dart:
An error `FormatterException` occurred while formatting the generated source for
  `asset:aodocsmobile/integration_test/gherkin/suites/workflow/workflow_finalize_and_force_transitions_test.dart`
which was output to
  `integration_test/gherkin/suites/workflow/workflow_finalize_and_force_transitions_test.gherkin_tests.g.part`.
This may indicate an issue in the generator, the input source code, or in the
source formatter.
Could not format because the source could not be parsed:

line 10237, column 153 of .: Expected an identifier.
      ╷
10237 │     name: 'And the document property "String property" displays a Value-must-match-the-validation-rule error message with the rule "^[A-Z]{3}\\\\d{5}\\$"',
      │                                                                                                                                                         ^
      ╵
```

A second (non-blocking) remark, the name of the dart file in error is not the correct one.
The feature file containing the step in error is "string_properties_edition_with_validation_rules", not "workflow_finalize_and_force_transitions_test".

**Comment by jonsamwell** [comment]
Fixed in 3.0.0-rc.17
