### ISSUE TITLE
Adding inline screenshots and console logs

### ISSUE THREAD

**Issue by snickersv2** [jonsamwell/flutter_gherkin#26]
Hi, I'm wondering how we can add inline screenshots and logs to the JsonReporter which are to be displayed in the HTML report? 

Thank you.

**Comment by jonsamwell** [comment]
Hi @snickersv2 

This is a good idea and have been meaning to get around to it.

It looks like adding an image into the json report would be pretty simple:

(see https://github.com/gkushang/cucumber-html-reporter/blob/develop/lib/reporter.js#L261)

Although getting the image would be a bit harder as the underlying Gherkin engine is separate from the Flutter test_driver that would take the screenshot.  I need to investigate further but it looks like you would attached the screenshot to the world which would then get picked up by the reporter.  We would probably need a new hook (OnAfterStepFailed) to take the screenshot via the flutter driver and attach it to the json report.  

As for adding logs outputs I am not too sure.  You could use the attach mechanism on the world object (when I implement attach) to attach some text that the reporter could pickup.

Here is some basic information about attachments that I would use to implement this feature

https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/attachments.md

Would this be a good solution for you?

**Comment by snickersv2** [comment]
Hi, 
"As for adding logs outputs I am not too sure. You could use the attach mechanism on the world object (when I implement attach) to attach some text that the reporter could pickup."
- Yes I think this is good. I am thinking if anytime we call a logger during a step that it will get included in the report. If _attach_ is doing this then this will be helpful.

Regarding the screenshots, could it also be not limited to OnAfterStepFailed?

Additional question: 
1) I noticed there is a List<JsonRow> under JsonStep, can we add images and logs here for the meantime?

**Comment by jonsamwell** [comment]
Hi @snickersv2 

I have implemented the attach functionality now so you should be able to do everything you want to.  I have added a Hook in the flutter_gherkin library to take a screenshot if a step fails.  This works by overriding the onAfterStep hook.  You can of course override this class or create your own.  Just include it in the configuration object and it should work out of the box adding the attachments to the json output of the json reporter.

The hook is pretty simple:

```
import 'dart:convert';

import 'package:gherkin/gherkin.dart';
import 'package:meta/meta.dart';
import '../flutter_world.dart';

class AttachScreenhotOnFailedStepHook extends Hook {
  @override
  Future<void> onAfterStep(
      World world, String step, StepResult stepResult) async {
    if (stepResult.result == StepExecutionResult.fail) {
      final screenshotData = await takeScreenshot(world);
      world.attach(screenshotData, 'image/png', step);
    }
  }

  @protected
  Future<String> takeScreenshot(World world) async {
    final bytes = await (world as FlutterWorld).driver.screenshot();

    return base64Encode(bytes);
  }
}
```

It will need to be included in the test configuration to work.

```
import 'dart:async';
import 'package:flutter_gherkin/flutter_gherkin.dart';
import 'package:gherkin/gherkin.dart';
import 'package:glob/glob.dart';
import 'hooks/hook_example.dart';
import 'steps/colour_parameter.dart';
import 'steps/given_I_pick_a_colour_step.dart';
import 'steps/tap_button_n_times_step.dart';

Future<void> main() {
  final config = FlutterTestConfiguration()
    ..features = [Glob(r"test_driver/features/**.feature")]
    ..reporters = [
      ProgressReporter(),
      TestRunSummaryReporter(),
      JsonReporter(path: './report.json')
    ]
    ..hooks = [HookExample(), AttachScreenhotOnFailedStepHook()]
    ..stepDefinitions = [TapButtonNTimesStep(), GivenIPickAColour()]
    ..customStepParameterDefinitions = [ColourParameter()]
    ..restartAppBetweenScenarios = true
    ..targetAppPath = "test_driver/app.dart"
    ..exitAfterTestRun = true; // set to false if debugging to exit cleanly
  return GherkinRunner().execute(config);
}
```

![shot](https://user-images.githubusercontent.com/3694497/59885251-ffda0d00-93fd-11e9-9f62-b84cf4e076c9.PNG)

This should work the same with the logs.  I think you might have to have a class that implements `Reporter` and `Hook`.  You can override the `message` method on reporter which just attaches the messages to the world object.  You would have to store the world object from the hooks method `onAfterScenarioWorldCreated`.  That way you can call ```await reporter.message('message', MessageLevel.info);``` from within a step to log messages.  Let me know if you need a concrete example of this.

Let me know how you get on.

Jon

**Comment by snickersv2** [comment]
Hi Jon,

I was able to try the suggested hook and it worked for me. 
I also played around with a custom JsonReporter and edited the JsonRow list. I was able to attach a screenshot inside the JsonRow by adding a string with an img tag. I had to however, create my own JsonFeature class down to JsonRow class since they are only accessible within the library.

Thanks.

**Comment by jonsamwell** [comment]
Hi @snickersv2

Did the hook I did to attach an image not work for you? I did all the work
to attach an image to the JSON report so you should not need to modify
anything in that respect or have I miss understood something?

**Comment by snickersv2** [comment]
Hi @jonsamwell 
Yes it did work. I was able to have an image on the JSON report and that was for the end of the step if I understood it correctly.

The reason I tried modifications is because I wanted to include logs/screenshot in the middle of the step (I was trying around stuff while waiting for your answer ) and the way I did it was by adding strings to the JsonRow list under JsonStep. 

I did try if I could use world.attach() inside reporter. I was able to get the step name using reporter.onStepStarted() to use as the context parameter in world.attach() . However I am not able to access the world object from the reporter. Please let me know if I missed anything.

Thank you!

**Comment by jonsamwell** [comment]
Hi @snickersv2 

Feel free to PR your changes to the json reporter!

Why would you need to get the world object in the reporter? 

Perhaps we should modify the JsonReporter to be able to handle multiple attachments for a step.

That way you could attach anything from the step or a hook class and have it included in the report

Jon

**Comment by jonsamwell** [comment]
@snickersv2 is this working as you expect now?  Can I close this?

**Comment by snickersv2** [comment]
Hi @jonsamwell yes you can close this. I am able to make it work and I have no questions yet. However, should I reopen this or raise a new issue if there is something new about this topic I want to bring up? Thank you!

**Comment by jonsamwell** [comment]
Hi @snickersv2 I would just open an new issue.
