### ISSUE TITLE
[Question] How to make sure the next step executes only when previous is completed?

### ISSUE THREAD

**Issue by umangdivyanshu** [jonsamwell/flutter_gherkin#260]
Given I open the app
Then I should see search page
And I enter keyword in search input box
And I click on search suggestion
And I verify the search results

Take above example for instance, the execution is so fast that on the UI I could see the text entering in the input box, clicking on search suggestion and verification happening but in the terminal logs it shows that it is still executing _Then I should see search page_ step.

Sometimes it causes tests to fail. How can I make sure the next step executes only when previous one is completed.

**Comment by jonsamwell** [comment]
It should execute in order. All the code is async so things may appear out of order depending on scheduling (Especially with the logs). I would ensure that the code within your custom steps is correctly waiting for all async code.
