### ISSUE TITLE
Is it possibe to start the the test cases in chrome with a specific screen size?

### ISSUE THREAD

**Issue by murilodag** [jonsamwell/flutter_gherkin#262]
I would like to run the tests in a specific screen size. 
I found this [link](https://github.com/flutter/flutter/issues/65474) describing how to do it, but it does not seem to work for chrome/chromedrive.

**Comment by umangdivyanshu** [comment]
You can add --browser-dimension to the flutter drive command and set the screen size - 

`flutter drive --driver=test_driver/integration_test_driver.dart --target=integration_test/gherkin_suite_test.dart -d web-server --no-headless --browser-name=chrome --browser-dimension 1680,1000`

**Comment by murilodag** [comment]
@umangdivyanshu Thanks for your answer. It did in fact resize the screen.

Do you know why ```-d chrome``` does not allow to respect ```--browser-dimension``` flag?
