### ISSUE TITLE
Update documentation w.r.t 3.0.0-rc.17

### ISSUE THREAD

**Issue by umangdivyanshu** [jonsamwell/flutter_gherkin#263]
Hi @jonsamwell,

Could you please update the documentation or share an example for gherkin_suite_test.dart file for the latest changes w.r.t 3.0.0-rc.17. I am currently on w.r.t 3.0.0-rc.9 and tried updating to 3.0.0-rc.17 but I was getting a lot of errors and couldn't resolve them.

**Comment by jonsamwell** [comment]
What errors are you seeing?

**Comment by jonsamwell** [comment]
Feel free to open if you can provide more information as to the issue
