### ISSUE TITLE
Is it possible to restart flutter web for integration_test between scenario - restartAppBetweenScenarios

### ISSUE THREAD

**Issue by linchen2chris** [jonsamwell/flutter_gherkin#264]
hi, I notice we have [restartAppBetweenScenarios](https://github.com/jonsamwell/flutter_gherkin#restartappbetweenscenarios) configuration, but it seems only works for flutter driver, not integration test

**Comment by jonsamwell** [comment]
The integration test should restart the app between scenarios. So this property is not really applicable when using integration_test. You can create a hook to reset the persisted application state between scenarios. See the example. https://github.com/jonsamwell/flutter_gherkin/blob/integration_test__package_support/example_with_integration_test/integration_test/gherkin/hooks/reset_app_hook.dart
