### ISSUE TITLE
Planning to stop using the flutter drive

### ISSUE THREAD

**Issue by spaquis** [jonsamwell/flutter_gherkin#267]
Hi,
I'm currently using flutter_gherkin: 3.0.0-rc.17 and it works very well but i would like to get some coverage report and it's not possible with flutter drive. Is there some plan to try to use only flutter test or is it too complicated ? 
Thanks.

**Comment by jonsamwell** [comment]
@spaquis the RC version of this library uses flutter test! https://github.com/jonsamwell/flutter_gherkin/tree/integration_test__package_support

**Comment by spaquis** [comment]
Hi @jonsamwell ,
Thanks for your answer, i already use the RC version but even with it we need to launch tests by running flutter drive :
`flutter drive --driver=test_driver/integration_test_driver.dart --target=integration_test/gherkin_suite_test.dart`
And because of this, I can't collect coverage :).  I don't know if it's possible in the future to use only 
`flutter test integration_test/gherkin_suite_test.dart`

Thanks.
