### ISSUE TITLE
[Question] How to send tags in the run command as parameter?

### ISSUE THREAD

**Issue by joaofyz** [jonsamwell/flutter_gherkin#277]
Hello,

We are trying to run the test command with multiple tags as parameters in order to override the “tagExpression” configuration in gherkin_suite_test.dart. Is that possible?

We are using the 3.0.0_rc.17 version and using the following command to run the tests
`
flutter drive --driver=test_driver/integration_test_driver.dart --target=integration_test/gherkin_suite_test.dart --flavor pre
`

Thanks in advance

**Comment by jonsamwell** [comment]
Hi @joaofyz I am not quite sure what you mean here? The tag expression is basically a boolean statement so if you want to run all tests that have the tags '@smoke' and '@ios' you would just set the tagExpression to '@smoke and @ios'

**Comment by joaofyz** [comment]
Hi Jon, what I want is to set the tags dynamically when running the flutter drive command, and override that tagExpression of the gherkin_suite_test.dart.

Imagine you have specific tests for Regression, Smoke... and you want to run them when making a specific build in your CI. We don't want to have to change the gherkin_suite_test.dart tagExpression value, it's easier if we could add some kind of argument when running the flutter drive command.

It's that possible? Or can we achieve this on other way?

**Comment by jonsamwell** [comment]
Yeah I've done this using the args package. I'll put up an example tomorrow
morning

**Comment by joaofyz** [comment]
Hi @jonsamwell , just to remember you about this topic.

When you can, please share the example how we can do this 👍

Thanks in advance

**Comment by AFASbart** [comment]
I think it is best for you @joaofyz to just look at the documentation of https://pub.dev/packages/args

It seems your file look something like this:
```
@GherkinTestSuite(
    featurePaths: <String>['integration_test/features/**.feature'],
    executionOrder: ExecutionOrder.sequential)
Future<void> main(List<String> arguments) async {
  var parser = ArgParser();
  parser.addOption("tagExpression")
  var configuration = FlutterTestConfiguration(
    reporters: [
      TestRunSummaryReporter(),
      JsonReporter(
        writeReport: (_, __) => Future<void>.value(),
      ),
    ],
    tagExpression: parser.parse(arguments)["tagExpression"]
  );

  await executeTestSuite(
      configuration: configuration,
      appMainFunction: (World world) async => app.main(),
  );
}
```

**Comment by joaofyz** [comment]
We managed to solve this using the --dart-define parameter in the drive command.

Then we access it in our gherkin_suite_test.dart by using

`const tagExpression = String.fromEnvironment("tag");`
