### ISSUE TITLE
Error after upgrading to Flutter 1.7

### ISSUE THREAD

**Issue by snickersv2** [jonsamwell/flutter_gherkin#28]
Hi,

I encountered an error after upgrading to Flutter 1.7:

file:///Users/abanv2/Documents/Flutter/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/gherkin-1.0.3/lib/src/gherkin/steps/step_definition_implementations.dart:35:16: Error: Found unsupported uses of 'TInput1' in supertype 'StepDefinitionBase'.
abstract class StepDefinition1<TWorld extends World, TInput1>

Here is what I have in my pubspec.yaml:
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_driver:
    sdk: flutter
  test: any
  flutter_gherkin: ^1.0.4

Kindly advise. Thank you!

-------------------------------------------------------------
More info:

flutter doctor --verbose
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.7.8+hotfix.3 at /Users/abanv2/Documents/Flutter/sdk/flutter
    • Framework revision b712a172f9 (2 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/abanv2/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/abanv2/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • CocoaPods version 1.6.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 33.4.3
    • Dart plugin version 191.6183.87

[✓] Connected device (1 available)
    • SM A520F • 52105109ea678475 • android-arm64 • Android 8.0.0 (API 26) (emulator)

• No issues found!
Process finished with exit code 0

**Comment by jonsamwell** [comment]
@snickersv2 I found the same about 2 hours ago!  Just fixed the Gherkin library and going to update this library in a bit.  Thanks for the issue though.

**Comment by jonsamwell** [comment]
@snickersv2 I have updated the library to 1.0.5 so it should work if you upgrade.
