### ISSUE TITLE
How to use in widget test

### ISSUE THREAD

**Issue by snickersv2** [jonsamwell/flutter_gherkin#29]
Hi, this is more of a question than an issue.

Which components do we look at if we want to use this plugin for widget testing? We plan to have a set of widget tests per feature and to have html reporting on our widget tests as well.

Thank you.

**Comment by jonsamwell** [comment]
Hi @snickersv2 

I haven't tested widgets before but with this Gherkin lib but I would expect it would be easier to do it with the underlying Gherkin library as this flutter_gherkin lib relies on flutter driver which your widgets tests wouldn't need to do.

https://github.com/jonsamwell/dart_gherkin

Note that flutter_gherkin merely adds helper methods and the ability to interact with flutter driver on top of the core dart_gherkin lib.

For the unit type tests your could use it the same way you would any 'native' type tests

```dart test.dart```

It'll be worth looking at the example project https://github.com/jonsamwell/dart_gherkin/tree/master/example

Let me know how you get on.

Jon

**Comment by snickersv2** [comment]
Hi Jon, 

I am able to make progress somehow. What I did was create a custom world that holds the WidgetTester:

_testWidgets('Follow New Patient Request - Widget Test', (WidgetTester tester) async {

    final config = TestConfiguration()
      ..features = [Glob(r"test/features/**.feature")]
      ..reporters = [ProgressReporter(), TestRunSummaryReporter()]
      ..hooks=[CustomHook()]
      ..createWorld = (TestConfiguration config) {
        return Future.value(FlutterWidgetWorld(tester));
      }
      ..stepDefinitions = [WidgetValidation()];

    await GherkinRunner().execute(config);'
}_

However I encountered an error below but I'm not sure how to resolve it. I tried to call exit in the main function but I might not have done it correctly.

_tearDownAll(() async {
    exit(0);
  });_

**Error logs:**

Shell: 3 scenarios (3 passed)
Shell: 3 steps (3 passed)
Shell: 0:00:01.262000dart:async/stream_controller.dart 595:43                     _StreamController.addError
dart:async/stream_controller.dart 862:13                     _StreamSinkWrapper.addError
package:stream_channel/src/guarantee_channel.dart 144:14     _GuaranteeSink._addError
package:stream_channel/src/guarantee_channel.dart 135:5      _GuaranteeSink.addError
package:flutter_tools/src/test/flutter_platform.dart 478:29  FlutterPlatform._startTest.<fn>
===== asynchronous gap ===========================
dart:async/zone.dart 1053:19                                 _CustomZone.registerUnaryCallback
dart:async-patch/async_patch.dart 77:23                      _asyncThenWrapperHelper
package:flutter_tools/src/test/flutter_platform.dart         FlutterPlatform._startTest.<fn>
package:flutter_tools/src/test/flutter_platform.dart 678:26  FlutterPlatform._startTest
===== asynchronous gap ===========================
dart:async/zone.dart 1053:19                                 _CustomZone.registerUnaryCallback
dart:async-patch/async_patch.dart 77:23                      _asyncThenWrapperHelper
package:flutter_tools/src/test/flutter_platform.dart         FlutterPlatform._startTest
package:flutter_tools/src/test/flutter_platform.dart 362:36  FlutterPlatform.loadChannel
package:flutter_tools/src/test/flutter_platform.dart 315:46  FlutterPlatform.load
===== asynchronous gap ===========================
dart:async/zone.dart 1053:19                                 _CustomZone.registerUnaryCallback
dart:async-patch/async_patch.dart 77:23                      _asyncThenWrapperHelper
package:test_core/src/runner/loader.dart                     Loader.loadFile.<fn>
package:test_core/src/runner/load_suite.dart 98:31           new LoadSuite.<fn>.<fn>
===== asynchronous gap ===========================
dart:async/zone.dart 1045:19                                 _CustomZone.registerCallback
dart:async/zone.dart 962:22                                  _CustomZone.bindCallbackGuarded
dart:async/timer.dart 52:45                                  new Timer
dart:async/timer.dart 87:9                                   Timer.run
dart:async/future.dart 174:11                                new Future
package:test_api/src/backend/invoker.dart 399:21             Invoker._onRun.<fn>.<fn>.<fn>

Shell subprocess ended cleanly after tests finished. Did main() call exit()?


**Additional info:**
I run the above using `flutter test` command but when I tried using `flutter run -t` (so i can see the widget test in my test device), it didn't work because the process is running on the device and is not able to retrieve the feature files.

Let me know your thoughts. Thank you!
