### ISSUE TITLE
Restart App method needed

### ISSUE THREAD

**Issue by doubleoh** [jonsamwell/flutter_gherkin#30]
Hello,
In our app, we need to verify particular behavior remains after the app is restarted.
For example:
Scenario: verify that user stays logged in after restart
Given: I'm on login page
When: I login with "user1" credentials
Then: I'm on home page as "user1"
When: I restart the app
Then: I'm on home page as "user1"

Current implementation of restarts constraints the restart of application to only be available by separating the steps into different, sequential scenarios, so the above example would be:

Scenario: verify that user stays logged in after restart part1
Given: I'm on login page
When: I login with "user1" credentials
Then: I'm on home page as "user1"

Scenario: verify that user stays logged in after restart part2
Then: I'm on home page as "user1"

Which does not make much sense to me, as it is one scenario by design.

I've investigated how I can change that - and it's by getting access to the _restartApp() method in the app_runner_hook.dart hook. By calling it, I will be able to painlessly restart the app, just like it does in between scenarios.
But I think that it would be more convenient to have a native support from flutter_gherkin project for that and have a separate method for that in, for example, FlutterDriverUtils class.

Please let me know what you think about that.
Thanks

**Comment by doubleoh** [comment]
Hi again,
When I tried to implement my workaround I realized that in order to let my code use the _restartApp() I have to change a lot of layers and then either pass the hook object to my code, or pass the application process' object to my code.
So basically our team decided not to change gherkin's code for now.
So having a restart method would be really useful for us.
Thanks,

**Comment by jonsamwell** [comment]
Hi sorry for the late reply.

Yes this is a bit more complicated as when you restart the app you need to
also reconnect to the observatory port that the dart runtime needs to
listen to and instrument the app.  Otherwise the test would not be able to
continue.

I should get a bit of time later in the week to do this for you. So sorry
for the delay.

Jon

**Comment by doubleoh** [comment]
Will wait for the updates, thanks a lot!

**Comment by jonsamwell** [comment]
You can now restart the app under test using the ```restartApp``` method on the Flutter world instance that is available to any step.  Or you can use the build in step definition ```Then I restart the app```.

```
await world.restartApp();
```

see https://github.com/jonsamwell/flutter_gherkin/blob/master/lib/src/flutter/steps/restart_app_step.dart#L10

**Comment by doubleoh** [comment]
Thank you so much!

**Comment by jonsamwell** [comment]
No problem. Let me know if it suits your needs.
