### ISSUE TITLE
Support for background and scenario outline

### ISSUE THREAD

**Issue by alexeverettnoomi** [jonsamwell/flutter_gherkin#31]
Gherkin usually includes reuse of "given" for multiple scenarios through the use of background and the reuse of scenarios with scenario outlines.

Would be amazing if these were supported

https://cucumber.io/docs/gherkin/reference/#background
https://cucumber.io/docs/gherkin/reference/#scenario-outline

**Comment by jonsamwell** [comment]
Hi @alexeverettnoomi 

The use of 'Background' is supported already

See https://github.com/jonsamwell/dart_gherkin/blob/master/lib/src/gherkin/syntax/background_syntax.dart

That is in the core dart_gherkin repo which the flutter implementation uses.

Are you getting an error when trying to use a background block in your features?

**Comment by alexeverettnoomi** [comment]
Yeah I'm getting the error:

Unhandled exception:
Exception: Unknown runnable child given to Feature 'StepRunnable'
#0      FeatureRunnable.addChild (package:gherkin/src/gherkin/runnables/feature.dart:57:9)
#1      GherkinParser._parseBlock (package:gherkin/src/gherkin/parser.dart:75:21)
#2      GherkinParser._parseBlock (package:gherkin/src/gherkin/parser.dart:72:15)
#3      GherkinParser.parseFeatureFile (package:gherkin/src/gherkin/parser.dart:43:7)
<asynchronous suspension>
#4      GherkinRunner.execute (package:gherkin/src/test_runner.dart:44:27)
<asynchronous suspension>
#5      main (file:///Users/alexandereverett/Documents/dev/noomi-nursing-app/test_driver/app_test.dart:67:26)
<asynchronous suspension>
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

When I run 
`Feature:  QA-194 - When login to NHA unit selector overlay always shows with no unit selected

  Background:
    Given I have a site with 1 units, 1 apartments per unit, 1 common areas per unit, 1 coworkers, 1 residents
    And coworker 1 is logged in to the app

  Scenario: When logged into the app the unit drawer opens automatically
    Given I select unit 1
    When I tap the "confirm units" button
    Then the "unit selection drawer" does not exist`


But it works fine with:

`Feature:  QA-194 - When login to NHA unit selector overlay always shows with no unit selected

  Scenario: When logged into the app the unit drawer opens automatically
    Given I have a site with 1 units, 1 apartments per unit, 1 common areas per unit, 1 coworkers, 1 residents
    And coworker 1 is logged in to the app
    And I select unit 1
    When I tap the "confirm units" button
    Then the "unit selection drawer" does not exist`

**Comment by jonsamwell** [comment]
Thanks, I'll take a look

**Comment by jonsamwell** [comment]
@alexeverettnoomi I think it *might* be that your Background block does not have a name?

try this

```
Background: Setup site
Given I have a site with 1 units, 1 apartments per unit, 1 common areas per unit, 1 coworkers, 1 residents
And coworker 1 is logged in to the app

Scenario: When logged into the app the unit drawer opens automatically
Given I select unit 1
When I tap the "confirm units" button
Then the "unit selection drawer" does not exist
```

**Comment by jonsamwell** [comment]
OK, I have released v1.0.7 of flutter_gherkin which fixes the issue where a background block has no name.  Update it and let me know if it fixes it.

**Comment by alexeverettnoomi** [comment]
Works perfectly now, thank you so much :)

**Comment by jonsamwell** [comment]
@alexeverettnoomi I've added support for Scenario Outlines and Example blocks!  See https://github.com/jonsamwell/flutter_gherkin/blob/master/example/test_driver/features/counter_increases_scenerio_outline_example.feature & https://github.com/jonsamwell/dart_gherkin/blob/master/example/features/calculator_scenerio_outline_example.feature for a couple of examples
