### ISSUE TITLE
Documentation for using special characters like new line in a step

### ISSUE THREAD

**Issue by snickersv2** [jonsamwell/flutter_gherkin#33]
Hi @jonsamwell , I would like to ask if there is any documentation for using special/escape characters in a step especially if we're using RegEx?

Thank you!

**Comment by jonsamwell** [comment]
Hi @snickersv2 you should just be able to escape special characters as per normal with the regex.

The library is matching special patterns such as those used to identify variable types such as {int}, {string} etc

```
I have {int} cucumbers

I have a horse name {string}
```

It also allows simple pluralisation via '(s)'

```
I have {int} kangeroo(s)
```

See https://github.com/jonsamwell/flutter_gherkin#well-known-step-parameters

Are there any special characters that are not working?

**Comment by snickersv2** [comment]
Hi @jonsamwell , i'm having trouble using a text with \n in between on a {string} parameter .
I'm using {string} parameter in find.text() and it's not able to find it. However I did try find.text(<actual string with \n here>) and it worked so I was wondering if it's because the regex was not able to interpret the escape character?

**Comment by jonsamwell** [comment]
Could you provide a small example and I can look at it for you today.

**Comment by snickersv2** [comment]
@jonsamwell  here is the sample stepline in my feature file:
Then I verify that the 'You\’re now displaying\nthis message.' label is visible

and below is a sample step definition:

> class ThenIsPresent extends Then2WithWorld<String, String, FlutterWorld> {
  ThenIsPresent([StepDefinitionConfiguration configuration])
      : super(configuration);

  /// DESCRIPTION:
  /// verify an element is visible
  @override
  Future<void> executeStep(String locator, String notUsed) async {
    
    bool isPresent = await FlutterDriverUtils.isPresent(find.text(locator), world.driver);
    print('$locator : $isPresent');
    expect(isPresent, true,
        reason: 'Expected result: $locator is present.'
            ' Actual result: $locator is absent');
  }

  @override
  RegExp get pattern => RegExp(r'I verify that the {string} (icon|text|heading|button|label|value|title) is visible');
}

**Comment by snickersv2** [comment]
I found a workaround right now, https://github.com/jonsamwell/flutter_gherkin#multiline-strings

**Comment by jonsamwell** [comment]
@snickersv2 Thanks I'll have a look at this.  Of the top of my head I think it is most likely becuase the regex that replaces the '{string}' param in the framework is not multiline.  I think your work around it hte way to go at the moment.  I'll try and fix it up this week.

**Comment by jonsamwell** [comment]
@snickersv2 I have a fixed pending for this.  I am just waiting for another issue to be sorted and I will publish it so this will not work

``` Given I add the text "some text \n with a new \n line" as a comment```

**Comment by jonsamwell** [comment]
@snickersv2 This fix is now in the latest published version
