### ISSUE TITLE
adding flutter_gerkin to some projects seems to cause packages get to break

### ISSUE THREAD

**Issue by NickoftheSouth** [jonsamwell/flutter_gherkin#38]
I've been working on a Flutter project and trying to get cucumber testing added using flutter_gherkin.
The problem is when I add it to the pubspec file and run Packages get, dart starts eating up never ending amounts of Ram and never seems to complete.  
It's been running for well over two hours now and has risen to over 5 GB of ram used.  

My pubspec looks like this;
`
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  json_annotation:
  qr_flutter: 2.0.0+51
  qr_reader: ^0.1.3
  font_awesome_flutter:
  intl:
  http:
  shared_preferences: 0.4.3
  flutter_local_notifications: ^0.5.2
  flutter_gherkin:`

The output from flutter doctor is;
`Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.18362.418], locale en-NZ)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.
[√] Android Studio (version 3.5)
[!] IntelliJ IDEA Community Edition (version 2019.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code, 64-bit edition (version 1.38.1)
[√] Connected device (1 available)

! Doctor found issues in 2 categories.
`

Could this be a corrupted packages cache issue and is there some way to clear it out?
Any other suggestions would be appreciated.

**Comment by jonsamwell** [comment]
Hi, thanks for giving the project a try.

I've never seen this before, the flutter gherkin project doesn't depend on anything large 

https://github.com/jonsamwell/flutter_gherkin/blob/master/pubspec.yaml#L19

really just Gherkin which itself doesn't depend on anything at all really

https://github.com/jonsamwell/dart_gherkin/blob/master/pubspec.yaml#L8

Did you notice if there are any conflicts when running pub get?

You could try running it from the command line if your ide does it for you and doesn't give any output

```
flutter pub get
```

You pub-cache is usually store in your flutter source directory something like:

```
C:\Google\flutter\.pub-cache\
```

So you could try deleting that.

Or maybe run

```
pub cache repair
```

What version of Flutter are you on?

It might be that as you are not specifying versions for stuff like flutter_gherkin, intl, http etc it is just having a hard time figuring out what versions are compatible with the other versions.

**Comment by jonsamwell** [comment]
I've just tried a brand new Flutter project with your pubspec file content and it took 17 seconds to get everything.

```
name: test_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies: 
  flutter: 
    sdk: flutter 
  cupertino_icons: ^0.1.2
  json_annotation:
  qr_flutter: 2.0.0+51
  qr_reader: ^0.1.3
  font_awesome_flutter:
  intl:
  http:
  shared_preferences: 0.4.3
  flutter_local_notifications: ^0.5.2
  flutter_gherkin:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
```

This is the doctor output

```
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.18362.418], locale en-GB)
    • Flutter version 1.9.1+hotfix.4 at C:\Google\flutter
    • Framework revision cc949a8e8b (3 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\jon.samwell\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.39.2)
    • VS Code at C:\Users\jon.samwell\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.5.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

**Comment by jonsamwell** [comment]
Does this only happen if you add flutter gherkin?

**Comment by jonsamwell** [comment]
@NickoftheSouth Did you fix the problem? Am I OK to close this?
