### ISSUE TITLE
World should be renamed to Disposible ?

### ISSUE THREAD

**Issue by paul-hammant** [jonsamwell/flutter_gherkin#4]
Ref: https://docs.microsoft.com/en-us/dotne/api/system.idisposable.dispose?view=netframework-4.7.2

And: http://picocontainer.com/javadoc/core/index.html?org/picocontainer//class-useDisposable.html 

:)

**Comment by jonsamwell** [comment]
Hi @paul-hammant 

I was following the cucumber convention of a world object being able to store state between test steps.

https://docs.cucumber.io/cucumber/state/#world-object

Although the world object in flutter gherkin is a disposable itself.  There is no Dart disposable so perhaps we need a simple disposable base class / interface here?

**Comment by paul-hammant** [comment]
Aslak Hellesøy (Cucumber's creator) was also co-creator of PicoContainer, which as far back as early 2003 had Startable (start/stop)and Disposable (dispose) as major lifecycle interfaces ..... I'll poke fun at him the next time we're in a pub together - for the silly method name :)
