### ISSUE TITLE
feature files execution order

### ISSUE THREAD

**Issue by maheshmnj** [jonsamwell/flutter_gherkin#43]
Hi I have written set of feature files each feature in a single file which consists of multiple scenarios and I only have a single step file which consists of all the step defination classes required to run the test 
The problem is When I run the test the tests are executed in the order the feature files are in the directory is there any way to specify the order in which feature files should be executed,One way I understand is to write all the scenarios in one file,but I dont think its a good idea.
heres the folder structure
![Peek 2019-11-28 11-19](https://user-images.githubusercontent.com/31410839/69780335-fc2e8b80-11d0-11ea-8f8b-308e0ba114c3.gif)

**test_config.dart**
```
import 'dart:async';
import 'package:flutter_gherkin/flutter_gherkin.dart';
import 'package:gherkin/gherkin.dart';
import 'package:glob/glob.dart';

import 'steps/stepFile.dart';

Future<void> main() {
  final config = FlutterTestConfiguration()
    ..features = [Glob(r"test_driver/features/**.feature")]
    ..reporters = [
      ProgressReporter(),
      TestRunSummaryReporter(),
      JsonReporter(path: 'bddReport.json')
    ]
    ..stepDefinitions = [
      GivenPageIsPresent(),
      WhenSwipeRight(),
      ThenPageIsPresent(),
      WhenSwipeLeft()
    ]
    ..restartAppBetweenScenarios = false
    ..targetAppPath = "test_driver/app.dart"
    ..exitAfterTestRun = true;
  return GherkinRunner().execute(config);
}
```
let me know if you need some additional info

**Comment by jonsamwell** [comment]
Hi,

Typically tests should be independent and atomic and not rely on other test but it you need to execute then in sequential order you can set the configuration property `order`.  This will execute them in the order the feature files are found (usually name order in the folders).

see  https://github.com/jonsamwell/flutter_gherkin#order

You can set the logging to verbose for the logger ```StdoutReporter(MessageLevel.verbose),``` to see in what order the feature files are discovered and rename them accordingly i.e. `1_boxlist.feature, 2_login.feature ..... etc`

```
  final config = FlutterTestConfiguration()
    ..defaultTimeout = Duration(seconds: 30)
    ..features = [Glob(r"features/**.feature")]
    ..reporters = [
      ProgressReporter(),
      TestRunSummaryReporter(),
      JsonReporter(path: './report.json'),
      StdoutReporter(MessageLevel.verbose),
      FlutterDriverReporter(),
    ]
    ..order = ExecutionOrder.sequential
...
```

**Comment by maheshmnj** [comment]
thanks that was a helpful info I renamed the feature files but at the time of executing the tests I dont understand the order it is finding the feature files

**Comment by jonsamwell** [comment]
Feature files are just found using a Glob pattern so it is a really a system level detail on how they are handed back to the code.  Tests should not rely on any other tests so I think you have implemented them wrong according to Gherkin principles if this is the case. I think you are implementing a scenario when you need a step.  If you post an example of the scenarios that depend on each other I can help you figure out the best way to approach them.

**Comment by maheshmnj** [comment]
suppose I have a Onboarding screen where I am actually showcasing the key features of the app and here is the feature file to it
```
Feature: Onboarding Process

    User Should be able to go through the onboarding process
    smoothly inorder to reach the login screen

    Scenario: user swipes through the onboarding Process
        Given I have a "onboardingScreen1" on screen
        When I swipe left on screen "onboardingScreen1"
        Then I should see "onboardingScreen2" on screen
        When I swipe left on screen "onboardingScreen2"
        Then I should see "onboardingScreen3" on screen
        When I swipe right on screen "onboardingScreen3"
        Then I should see "onboardingScreen2" on screen
        When I swipe left on screen "onboardingScreen2"
        Then I should see "onboardingScreen3" on screen
        When I swipe left on screen "onboardingScreen3"
        Then I should see "onboardingScreen4" on screen

    Scenario:user Skips onBoarding Process
        Given I have a "onboardingScreen1" on screen
        When I tap "getStartedButtonKey"
        Then I should see "loginPage" on screen
```

and a corresponding stepfile.dart

```
import 'dart:async';
import 'package:flutter_driver/flutter_driver.dart';
import 'package:flutter_gherkin/flutter_gherkin.dart';
import 'package:gherkin/gherkin.dart';

class GivenPageIsPresent extends Given1WithWorld<String, FlutterWorld> {
  @override
  Future<void> executeStep(String input1) async {
    await FlutterDriverUtils.isPresent(find.byValueKey(input1), world.driver);
  }

  @override
  RegExp get pattern => RegExp(r"Given I have a {string} on screen");
}

class ThenPageIsPresent extends Then1WithWorld<String, FlutterWorld> {
  @override
  Future<void> executeStep(String input1) async {
    await FlutterDriverUtils.isPresent(find.byValueKey(input1), world.driver);
  }

  @override
  RegExp get pattern => RegExp(r"Then I should see {string} on screen");
}

class WhenTextIsEnteredInTextField
    extends When2WithWorld<String, String, FlutterWorld> {
  @override
  Future<void> executeStep(String input1, String input2) async {
    await FlutterDriverUtils.enterText(
        world.driver, find.byValueKey(input1), input2);
  }

  @override
  RegExp get pattern => RegExp(r"When I enter {string} in {string}");
}

class WhenSwipeLeft extends When1WithWorld<String, FlutterWorld> {
  @override
  Future<void> executeStep(String input1) async {
    // TODO: implement executeStep
    await world.driver
        .scroll(find.byValueKey(input1), -300, 0, Duration(seconds: 2));
    // await world.driver.scrollUntilVisible(
    //     find.byValueKey(input1), find.byValueKey(input1),
    //     dxScroll: -300, timeout: Duration(seconds: 5));
  }

  @override
  // TODO: implement pattern
  RegExp get pattern => RegExp(r"When I swipe left on screen {string}");
}

class WhenSwipeRight extends When1WithWorld<String, FlutterWorld> {
  @override
  Future<void> executeStep(String input1) async {
    // TODO: implement executeStep
    await world.driver
        .scroll(find.byValueKey(input1), 300, 0, Duration(milliseconds: 500));
    // await world.driver.scrollUntilVisible(
    //     find.byValueKey(input1), find.byValueKey(input1),
    //     dxScroll: 300);
  }

  @override
  // TODO: implement pattern
  RegExp get pattern => RegExp(r"When I swipe right on screen {string}");
}

```
if I want to test this feature(and some other features of app individually) How should I proceed

**Comment by jonsamwell** [comment]
Typically you would use the `Background` section of the feature file to setup the steps required to carry out the test.  This could be a simple as logging in or navigating to a particular screen.  Keep the tests atomic and independent from each leads to easier to maintain tests and less test fails it one thing changes it won't break all your tests.

https://relishapp.com/cucumber/cucumber/docs/gherkin/background

**Comment by jonsamwell** [comment]
Closing as no reply
