### ISSUE TITLE
Unable to debug on VS Code

### ISSUE THREAD

**Issue by psovit** [jonsamwell/flutter_gherkin#44]
I am getting the following exception when trying to debug my tests:

> E/flutter (25735): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: FileSystemException: Directory listing failed, path = './test_driver/features/' (OS Error: No such file or directory, errno = 2)

Here's my test configuration.

```
Future<void> main(List<String> arguments) {  
//by default run all features unless specified by arguments.
  var features = [Glob("test_driver/features/**.feature")];
  if(arguments != null && arguments.length > 0) {
    var parser = ArgParser();
    parser.addOption('feature');
    var results = parser.parse(arguments);
    features = [Glob("test_driver/features/" + results["feature"])];
  }
  
  final config = FlutterTestConfiguration()
    ..features = features
    ..reporters = [
      ProgressReporter(),
      TestRunSummaryReporter(),
      JsonReporter(path: './report.json')
    ] // you can include the "StdoutReporter()" without the message level parameter for verbose log information
//    ..hooks = [HookExample()]
    ..stepDefinitions = [
      //my steps here
    ]
//    ..customStepParameterDefinitions = [ColourParameter()]
    ..restartAppBetweenScenarios = true
    ..targetAppPath = "test_driver/app.dart"
    // ..tagExpression = "@smoke" // uncomment to see an example of running scenarios based on tag expressions
    ..exitAfterTestRun = false; // set to false if debugging to exit cleanly
  return GherkinRunner().execute(config);
}
```
The tests run fine when I run without debugging with this command:
`dart test_driver\app_test.dart`

Also, here's my vs code launch.json config.

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Flutter",
            "request": "launch",
            "type": "dart",
            "flutterMode": "debug"
        },
        {
            "name": "Debug Features Tests",
            "request": "launch",
            "type": "dart",
            "program": "test_driver/app_test.dart",
            "flutterMode": "debug",
        }
    ]
}
```

It appears that the configuration isn't working well when debugging and might be looking for feature files in my device/emulator and not in my development machine.

**Comment by jonsamwell** [comment]
I'm guess it is something to do with your cwd (current working directory) when debugging.  Note that it does not look at the emulator / device for feature file.

try this (if this doesn't work see what the cwd is when you are debugging):

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Flutter",
            "request": "launch",
            "type": "dart",
            "flutterMode": "debug"
        },
        {
            "name": "Debug Features Tests",
            "request": "launch",
            "type": "dart",
            "program": "app_test.dart",
            "cwd": "test_driver",
        }
    ]
}
```

**Comment by jonsamwell** [comment]
@psovit did this work?

**Comment by psovit** [comment]
@jonsamwell i tried your solution but still it's not working. I have created a demo project to replicate the issue here: [https://github.com/psovit/gherkin_flutter_debug_fail](https://github.com/psovit/gherkin_flutter_debug_fail)

If you can take a look to verify if my configuration is correct or not, that would be great.

Thanks.

**Comment by jonsamwell** [comment]
Just send you a PR with it working https://github.com/psovit/gherkin_flutter_debug_fail/pull/1

**Comment by psovit** [comment]
Thanks for the quick response. After merging your changes I am now able to run in debug mode.
Looks like it is hitting the breakpoints for the code inside the steps however it is not hitting any breakpoints inside the code for the app.

For example when I trigger tap interaction, the breakpoint doesn't hit inside the code.
Is it expected behavior?

**Comment by jonsamwell** [comment]
Hi @psovit 

Not a problem.

Yes that is expected behaviour, the flutter driver only drives the app and debugger attaches to the driver process not the app process.  Think of the driver as a window looking at the app which cannot see what is going on in the app only interact with the bits it can see.

Internally flutter gherkin (once started by the debugging session) spawns the app in a separate process so nothing can really get into the app code.

**Comment by psovit** [comment]
Great. Thanks for this awesome library and your support.

**Comment by jonsamwell** [comment]
Thanks!  Let me know if you have any other problems, sometimes the Gherkin paradigm can be confusing to get your head around at first.

**Comment by jonsamwell** [comment]
This is now the default debug config in version 1.1.5+1
