### ISSUE TITLE
Uninstalling app in between scenario?

### ISSUE THREAD

**Issue by psovit** [jonsamwell/flutter_gherkin#46]
Hi @jonsamwell ,
In my test scenarios I need to make sure that my app's state is always clean in between the scenarios. So, I tried few hooks in between scenarios like uninstalling app or cleaning app data in between scenario, then after that restarting the app; all done with `adb` commands.

However, when I do this, the test driver cannot connect with the app after it is restarted back again and gets stuck at:
`[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...`

Is there a way to achieve what I am trying to do?

**Comment by jonsamwell** [comment]
Yes, I ran into the same scenario and found uninstalling the app to be too slow really.  I eventually settle with handling commands sent to the app via Flutter driver extensions.

I'm a bit short on time now but will add a full example in the morning.  

https://github.com/flutter/flutter/blob/stable/packages/flutter_driver/lib/src/extension/extension.dart#L81

Basically you can (via the flutter driver) send a command signal ( a string) that the app (via the flutter driver) can handle and execute some code.  For instance I have a reset command that ensure no user is logged in, the app settings are defaulted and the app in is in a freshly installed state.

I'll app a code example in the morning 👍

**Comment by psovit** [comment]
@jonsamwell thanks for the immediate response :) i will try to follow your suggestion for now and see if i can get it to work. 
if you get a chance to update with the example please do let me know as well.

Thanks a lot.

**Comment by psovit** [comment]
@jonsamwell Sending command signals via string text solved our problem. The issue can be closed.

**Comment by iqbalmineraltown** [comment]
@psovit could you share minimum example, or steps to send command signal for this workaround?
Thanks

**Comment by jonsamwell** [comment]
You can use the enableFlutterDriverExtensions DataHandler property.

I am just finishing up for the evening but can do you a better example tomorrow.  For now here is a really quick example (with explanation so you have something to try out)

In the test app:

```
void main() {
  final commandRunner = ExternalApplicationCommandInvoker();
  enableFlutterDriverExtension(handler: (request) async {
    String result;
    print('************ RUNNING COMMAND: $request');

    if (request == 'APP:RESET') {
      result =
          await commandRunner.invokeCommand(ExternalApplicationCommand.reset);
    }

    if (request == 'APP:NOTIFICATIONS:DISABLE') {
      result = await commandRunner
          .invokeCommand(ExternalApplicationCommand.notificationsDisable);
    }

    return result;
  });

  AppRunner.run(
    ContainerConfiguration.dev,
    commandRunner: commandRunner,
  );
}
```

In the test:
```
import 'dart:io';

import 'package:flutter_gherkin/flutter_gherkin.dart';
import 'package:gherkin/gherkin.dart';

class AppStateResetHook extends Hook {
  @override
  Future<void> onAfterScenarioWorldCreated(World world, String scenario) async {
    await (world as FlutterWorld).driver.requestData(
          'APP:RESET',
          timeout: const Duration(seconds: 6),
        );
    if (world is FlutterWorld && world.disableAppNotifications) {
      await Future<void>.delayed(const Duration(seconds: 2));
      final result = await world.driver.requestData(
        'APP:NOTIFICATIONS:DISABLE',
        timeout: const Duration(seconds: 6),
      );
      stdout.writeln(result);
    }
  }
}

```

The above test hook invokes the flutter driver method that sends a chunk of string data to the app under test that it can then handle to do things.

Don't forget to add the hook into the gherkin configuration class.

I hope this helps.

**Comment by iqbalmineraltown** [comment]
thanks a lot @jonsamwell 😄

**Comment by jonsamwell** [comment]
No problem

**Comment by jsonConnor** [comment]
Hi @jonsamwell, I really enjoy using this lib for tests but ran into reset between scenarios issue. I just started working with flutter recently and didn't get how to handle this app reset stuff. As i can understand i should put first part of code into my instrumented flutter app. Second one is a hook that invokes app reset just after flutter world is created before test - that is clear.

I have no idea where should I put the third and fourth code sample to make it work. Should it be main class of app? I could not find an example in repository

**Comment by quan-codemetrics** [comment]
I have the same problem with @jsonConnor :) It would be great if you can help us with an example @jonsamwell. Thank you so much for your time.

**Comment by jonsamwell** [comment]
@quan-codemetrics @jsonConnor I've update the comment above in regards to where to place those snippets of code https://github.com/jonsamwell/flutter_gherkin/issues/46#issuecomment-584462881
