### ISSUE TITLE
Verify widget is enable/disable using flutter driver

### ISSUE THREAD

**Issue by longk15t** [jonsamwell/flutter_gherkin#51]
Hi @jonsamwell ,

Is there a way to verify if a widget is enable/disable by using flutter driver ? `FlutterDriverUtils` or `world.driver` doesn't have any method to verify this point.

**Comment by GarimaVats** [comment]
FlutterDriverUtils.isPresent() can work?

**Comment by longk15t** [comment]
It presents, but if it's clickable => it's enable. If it's unclickable => it's disable. (I'm not sure if the way I understand correctly)

**Comment by jonsamwell** [comment]
Do you have any sample code that you use to check this? I guess if the
element is present and a tap times out then it is disabled?

**Comment by GarimaVats** [comment]
You can made your logic like that if clicking of this link will redirect you next page then it is enable.  But if you are on same page it is disable(un-clickable).

**Comment by jonsamwell** [comment]
There would be know way to know if the page has changed. Also this should
work for all widget types that can be disabled. Buttons, text fields,
switches etc

**Comment by longk15t** [comment]
I don't want to click/tap on that widget to check if it's enable (app state would be changed that would affect next steps). I tried to get all properties of the widget by using `.getWidgetDiagnostics()` or `.getRenderTree()` or `.getRenderObjectDiagnostics()` but didn't found any helpful properties to indicate the widget is clickable/unclickable.

I found out that if the `onTap` property of widget is null then it's disabled, otherwise it's enable. Anyway to retrieve these properties ? Or any other solution except actual clicking on it ?

**Comment by iqbalmineraltown** [comment]
@longk15t could you explain your scenario which bring up this issue?

**Comment by Holloweye** [comment]
@longk15t You could add several Scenarios to test all fail cases. Then you don't need to check if that button is disabled in the "Success Scenario". Because if that button was enabled then one of your scenarios would fail and you know that something is broken.

**Comment by jonsamwell** [comment]
@longk15t I would add an issue to the Flutter repo requesting this feature https://github.com/flutter/flutter/issues

**Comment by QiuRRQ** [comment]
> Hi [@jonsamwell](https://github.com/jonsamwell) ,
> 
> Is there a way to verify if a widget is enable/disable by using flutter driver ? `FlutterDriverUtils` or `world.driver` doesn't have any method to verify this point.

Hi Did you find a way to solve this?
