### ISSUE TITLE
Error: Type 'LogLevel' not found

### ISSUE THREAD

**Issue by hieutrandn9889** [jonsamwell/flutter_gherkin#52]
Hello,

I run install flutter_gherkin: ^1.1.7+5 in pubspec.yaml file
with the command on MAC : flutter drive --target=test_driver/bdd.dart

**I got an error:**
✓ Built build/app/outputs/apk/debug/app-debug.apk.
I/flutter ( 3730): Observatory listening on http://127.0.0.1:43529/wrXAD3eclvE=/
../../../.pub-cache/hosted/pub.dartlang.org/flutter_gherkin-1.1.7+5/lib/src/flutter/reporters/flutter_driver_reporter.dart:58:17: Error: Type 'LogLevel' not found.
  bool _isLevel(LogLevel level, Iterable<LogLevel> levels) =>
                ^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/flutter_gherkin-1.1.7+5/lib/src/flutter/reporters/flutter_driver_reporter.dart:58:42: Error: Type 'LogLevel' not found.
  bool _isLevel(LogLevel level, Iterable<LogLevel> levels) =>
                                         ^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/flutter_gherkin-1.1.7+5/lib/src/flutter/reporters/flutter_driver_reporter.dart:28:25: Error: The getter 'flutterDriverLog' isn't defined for the class 'FlutterDriverReporter'.
 - 'FlutterDriverReporter' is from 'package:flutter_gherkin/src/flutter/reporters/flutter_driver_reporter.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/flutter_gherkin-1.1.7+5/lib/src/flutter/reporters/flutter_driver_reporter.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'flutterDriverLog'.
      subscriptions.add(flutterDriverLog
                        ^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/flutter_gherkin-1.1.7+5/lib/src/flutter/reporters/flutter_driver_reporter.dart:29:48: Error: The getter 'LogLevel' isn't defined for the class 'FlutterDriverReporter'.
 - 'FlutterDriverReporter' is from 'package:flutter_gherkin/src/flutter/reporters/flutter_driver_reporter.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/flutter_gherkin-1.1.7+5/lib/src/flutter/reporters/flutter_driver_reporter.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'LogLevel'.
          .where((log) => _isLevel(log.level, [LogLevel.info, LogLevel.trace]))
                                               ^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/flutter_gherkin-1.1.7+5/lib/src/flutter/reporters/flutter_driver_reporter.dart:29:63: Error: The getter 'LogLevel' isn't defined for the class 'FlutterDriverReporter'.
 - 'FlutterDriverReporter' is from 'package:flutter_gherkin/src/flutter/reporters/flutter_driver_reporter.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/flutter_gherkin-1.1.7+5/lib/src/flutter/reporters/flutter_driver_reporter.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'LogLevel'.
          .where((log) => _isLevel(log.level, [LogLevel.info, LogLevel.trace]))
                                                              ^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/flutter_gherkin-1.1.7+5/lib/src/flutter/reporters/flutter_driver_reporter.dart:36:25: Error: The getter 'flutterDriverLog' isn't defined for the class 'FlutterDriverReporter'.
 - 'FlutterDriverReporter' is from 'package:flutter_gherkin/src/flutter/reporters/flutter_driver_reporter.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/flutter_gherkin-1.1.7+5/lib/src/flutter/reporters/flutter_driver_reporter.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'flutterDriverLog'.
      subscriptions.add(flutterDriverLog
                        ^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/flutter_gherkin-1.1.7+5/lib/src/flutter/reporters/flutter_driver_reporter.dart:37:48: Error: The getter 'LogLevel' isn't defined for the class 'FlutterDriverReporter'.
 - 'FlutterDriverReporter' is from 'package:flutter_gherkin/src/flutter/reporters/flutter_driver_reporter.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/flutter_gherkin-1.1.7+5/lib/src/flutter/reporters/flutter_driver_reporter.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'LogLevel'.
          .where((log) => _isLevel(log.level, [LogLevel.warning]))
                                               ^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/flutter_gherkin-1.1.7+5/lib/src/flutter/reporters/flutter_driver_reporter.dart:44:25: Error: The getter 'flutterDriverLog' isn't defined for the class 'FlutterDriverReporter'.
 - 'FlutterDriverReporter' is from 'package:flutter_gherkin/src/flutter/reporters/flutter_driver_reporter.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/flutter_gherkin-1.1.7+5/lib/src/flutter/reporters/flutter_driver_reporter.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'flutterDriverLog'.
      subscriptions.add(flutterDriverLog
                        ^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/flutter_gherkin-1.1.7+5/lib/src/flutter/reporters/flutter_driver_reporter.dart:46:45: Error: The getter 'LogLevel' isn't defined for the class 'FlutterDriverReporter'.
 - 'FlutterDriverReporter' is from 'package:flutter_gherkin/src/flutter/reporters/flutter_driver_reporter.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/flutter_gherkin-1.1.7+5/lib/src/flutter/reporters/flutter_driver_reporter.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'LogLevel'.
              (log) => _isLevel(log.level, [LogLevel.critical, LogLevel.error]))
                                            ^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/flutter_gherkin-1.1.7+5/lib/src/flutter/reporters/flutter_driver_reporter.dart:46:64: Error: The getter 'LogLevel' isn't defined for the class 'FlutterDriverReporter'.
 - 'FlutterDriverReporter' is from 'package:flutter_gherkin/src/flutter/reporters/flutter_driver_reporter.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/flutter_gherkin-1.1.7+5/lib/src/flutter/reporters/flutter_driver_reporter.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'LogLevel'.
              (log) => _isLevel(log.level, [LogLevel.critical, LogLevel.error]))

**Comment by jonsamwell** [comment]
Could you give me the output from `flutter doctor --verbose`.  I'm guess you are not on the stable branch and if this is the case will need to use the release candidate version (1.1.8-rc.1) https://pub.dev/packages/flutter_gherkin/versions/1.1.8-rc.1

**Comment by hieutrandn9889** [comment]
Thank you!
The bug is fixed by the version above

**Comment by jonsamwell** [comment]
Great!
