### ISSUE TITLE
How to get color of a widget ?

### ISSUE THREAD

**Issue by longk15t** [jonsamwell/flutter_gherkin#53]
@jonsamwell Have a good day,

Can we retrieve color property of a widget by using flutter driver ? Any solution ? Thanks in andvanced.

**Comment by jonsamwell** [comment]
I suspect that this cannot be achieve with the current state of the Flutter driver.  I will check out what properties come back from a `getRenderObject()` driver call but I doubt this would be included.  I would suggest filing a feature request with the Flutter team.  The driver is still pretty immature unfortunately.

**Comment by GarimaVats** [comment]
@jonsamwell where can we raise request any path or link?

**Comment by jonsamwell** [comment]
Just the flutter main repo https://github.com/flutter/flutter/issues
