### ISSUE TITLE
Can't run  codemagic CI for flutter_gherkin:1.1.8...

### ISSUE THREAD

**Issue by hieutrandn9889** [jonsamwell/flutter_gherkin#54]
Dear,

Today, I run codemagic CI but that is not success. I got an issue for version 1.1.8 of flutter_gherkin

**Pls, see the log for more details:**

iPhone 11 Pro Max • 3542DBEA-36D3-47E9-A374-64798E37294B • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

== /usr/local/bin/flutter drive --target=test_driver/bdd.dart ==
Using device iPhone 11 Pro Max.
Starting application: test_driver/bdd.dart
Removing obsolete reference to flutter_assets from Runner.app
Running pod install...                                             10.3s
Running Xcode build...                                          
Xcode build done.                                           89.1s
flutter: Observatory listening on http://127.0.0.1:49506/AaYjVz3pWhs=/
../programs/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_gherkin-1.1.8-rc.1/lib/src/flutter/reporters/flutter_driver_reporter.dart:28:5: Error: The setter 'driverLog' isn't defined for the class 'FlutterDriverReporter'.
 - 'FlutterDriverReporter' is from 'package:flutter_gherkin/src/flutter/reporters/flutter_driver_reporter.dart' ('../programs/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_gherkin-1.1.8-rc.1/lib/src/flutter/reporters/flutter_driver_reporter.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'driverLog'.
    driverLog = _driverLogMessageHandler;
    ^^^^^^^^^
../programs/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_gherkin-1.1.8-rc.1/lib/src/flutter/reporters/flutter_driver_reporter.dart:32:5: Error: The setter 'driverLog' isn't defined for the class 'FlutterDriverReporter'.
 - 'FlutterDriverReporter' is from 'package:flutter_gherkin/src/flutter/reporters/flutter_driver_reporter.dart' ('../programs/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_gherkin-1.1.8-rc.1/lib/src/flutter/reporters/flutter_driver_reporter.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'driverLog'.
    driverLog = null;
    ^^^^^^^^^
Stopping application instance.
Driver tests failed: 254

**Comment by jonsamwell** [comment]
What Flutter channel and version is the CI server using?

**Comment by hieutrandn9889** [comment]
Hello, 
Thank you for replying to me
"What Flutter channel and version is the CI server using?"
>> Flutter channel is master. I don't know  CI server version.
I run location on my computer that is OK :))

**Comment by jonsamwell** [comment]
By the look of the error on the CI it is running the stable channel.  I would suggest running the stable channel locally unless there is something specific in master that you need.

You will be able to set the channel on the CI server somehow even it is is manually by running `flutter channel master`

**Comment by jonsamwell** [comment]
Note that if you run the stable channel you will have to switch to the latest 1.7 version of Flutter Gherkin

**Comment by hieutrandn9889** [comment]
I config CI server is master branch 
[https://files.fm/u/mxx2kpgx](url)

I will switch 1.7 version of FG

Thank you again!

**Comment by jonsamwell** [comment]
No problem
