### ISSUE TITLE
[Suggest] I can't getText in title app

### ISSUE THREAD

**Issue by hieutrandn9889** [jonsamwell/flutter_gherkin#56]
Dear,

I am using getText for title app >> But it can't support for that:
**Log**
Exception: DriverError: Error in Flutter application: Uncaught extension error while executing get_text: Unsupported operation: Type MaterialApp is currently not supported by getText

Pls help me to support for that

**Comment by jonsamwell** [comment]
This is a limitation of the getText flutter driver method.  It can only find the text of Text widgets.

To get the application title ensure the applicationTitle widget in the app bar has a key then use the key name to get the title.

![image](https://user-images.githubusercontent.com/3694497/75186182-8f109f00-579b-11ea-95bd-76e629e74d32.png)

```
The I expect the "page title" to be "Some page title"
```
