### ISSUE TITLE
Version set in pubspec.yaml is not honored

### ISSUE THREAD

**Issue by slc1973** [jonsamwell/flutter_gherkin#58]
Without any change of my code or pubspec.yaml I got errors from `flutter analyze`:

```
error • 'RuntimeHooks.onAfterScenarioWorldCreated' ('Future<void> Function(World, String)') isn't a valid override of 'Hook.onAfterScenarioWorldCreated' ('Future<void> Function(World, String, Iterable<Tag>)') • test_driver/gherkin_tests.dart:74:16 • invalid_override
...
```

I read in CHANGELOG.md, breaking change in version 1.1.7+6 is happened.

But when I try to set any version (1.1.6+4 p.e.) via pubspec.yaml which worked before breaking change, version 1.1.7 is still used.

I think to update CHANGELOG.md is not enough, one tag/release with new version must be created with every new version of software too...

**Comment by jonsamwell** [comment]
Hi @slc1973 you will just be able to update you onAfterScenarioWorldCreated signatures to 

```
Future<void> onAfterScenarioWorldCreated(
    World world,
    String scenario,
    Iterable<Tag> tags,
  )
```

and then it will work (see https://github.com/jonsamwell/dart_gherkin/blob/master/lib/src/hooks/hook.dart#L21).

Yes I usually agree with a breaking change being a new minor release rather then a interim update however v1.1.8 is currently a RC for more recent versions of Flutter so I was reluctant to update both versions.

**Comment by jonsamwell** [comment]
@slc1973 you could try setting a specific verison in the pub file (without the `^`)

```
flutter_gherkin: 1.1.7+5
```

**Comment by slc1973** [comment]
Yes, exactly this I do and looks like 1.1.7+6 is still used (after `flutter packages get`)

In .packages I can see:
```
gherkin:file:///Users/markusmarkowski/Development/flutter/.pub-cache/hosted/pub.dartlang.org/gherkin-1.1.7/lib/
```
but I expect:
```
gherkin:file:///Users/markusmarkowski/Development/flutter/.pub-cache/hosted/pub.dartlang.org/gherkin-1.1.7+6/lib/
```

In .pub-cache I found this versions:
```
gherkin-1.1.6+3/ 
gherkin-1.1.6+4/ 
gherkin-1.1.7/   
```

When I change gherkin-1.1.7 to gherkin-1.1.6+4 in .packages manually it works fine without issue

**Comment by jonsamwell** [comment]
I'll make sure to use specific versions in future releases - unfortunately there is no way to fix a current release - so closing now unless you have another suggestion or I have mis-understood?

**Comment by slc1973** [comment]
And when you try to set git tag v1.1.7+5 on commit https://github.com/jonsamwell/flutter_gherkin/commit/e4270dcd4487ba52d867a35dd60e48ea4c105c89 and git tag v1.1.7+6 on commit https://github.com/jonsamwell/flutter_gherkin/commit/a3bebfdedc3d47f4f67c67547bcd59b5747adcd4 ?

Like in flutter: https://github.com/flutter/flutter/tags ?

**Comment by jonsamwell** [comment]
@slc1973 done.

I'll ensure I tag the repository on every release now

**Comment by slc1973** [comment]
Great!
Looks very good, just tags in https://github.com/jonsamwell/dart_gherkin are missing now on last two commits too

**Comment by jonsamwell** [comment]
Just added them

**Comment by slc1973** [comment]
v1.1.6+4 tags the same commit like v1.1.17... (https://github.com/jonsamwell/dart_gherkin/commit/1dfb41db2f4c63aba1832925ee5feec29942c6ea)

But must be https://github.com/jonsamwell/dart_gherkin/commit/7986abe03ce54b47bfe4aa2b4afdd9348024486a tagged as v1.1.6+4

**Comment by jonsamwell** [comment]
@slc1973 fixed

**Comment by slc1973** [comment]
I overlooked that here https://github.com/jonsamwell/flutter_gherkin/commit/e4270dcd4487ba52d867a35dd60e48ea4c105c89#diff-fb2d52cd953afedcafc9fe7629c6f132R19
in pubspec.yaml in line 19 `gherkin: ^1.1.6+4` is used instead of `gherkin: 1.1.6+4` and version 1.1.7 is still registered in .packages 

Is better to set dependencies without "^" in the future I think

Our fix doesn't work but the fix with new 3rd parameter in onAfterScenarioWorldCreated() is much faster ;)

@jonsamwell thanks a lot for fast support!

**Comment by jonsamwell** [comment]
Yeah, I'll be sure to set the specific dependencies in the future
