### ISSUE TITLE
Change default flutter sdk path?

### ISSUE THREAD

**Issue by iqbalmineraltown** [jonsamwell/flutter_gherkin#59]
On my machine, I had 2 flutter versions, `1.9.1+hotfix.6` and latest stable `1.12.13+hotfix.8`
and the default `flutter` command is binded to `1.9.1+hotfix.6`

I already set the VSCode SDK to `1.12.13+hotfix.8` and there were no trouble for running other projects.
But when I tried to run with my other flutter version, it always run with my default flutter version. 

Do you have any idea about this @jonsamwell ?

**Comment by jonsamwell** [comment]
What OS do you use?  If it is windows check where you PATH is pointing.  Not sure about Mac

**Comment by jonsamwell** [comment]
Perhaps ask this question in the Flutter repo?

**Comment by jonsamwell** [comment]
If you run ```flutter doctor -v``` it'll tell you the path it is using

![image](https://user-images.githubusercontent.com/3694497/76597224-06904d80-6554-11ea-81fc-b22064b0579e.png)

**Comment by jonsamwell** [comment]
Closing as not relevant to the repo
