### ISSUE TITLE
gherkin for dart only?

### ISSUE THREAD

**Issue by kev52** [jonsamwell/flutter_gherkin#6]
Is there a way to use this library for dart packages only? 
AND/OR
Is is possible to test without flutter driver (Non UI acceptance tests)

**Comment by jonsamwell** [comment]
@kev52 

Yes this is possible.  The Gherkin part of the libraray is independent of Flutter.  I haven't tried this but the below code should work.  The key is not to use the FlutterTestConfiguraion class as that has special code to setup the FlutterDriver.  So you will need to use the base TestConfiguration class instead.  Obviously your step implementation could not use any flutter driver functionality.

Something like this should work:

```
import 'dart:async';
import 'package:glob/glob.dart';
import 'package:flutter_gherkin/flutter_gherkin.dart';
import 'hooks/hook_example.dart';
import 'steps/colour_parameter.dart';
import 'steps/given_I_pick_a_colour_step.dart';

Future<void> main() {
  final config = TestConfiguration()
    ..features = [Glob(r"test_driver/features/**.feature")]
    ..reporters = [
      ProgressReporter(),
      TestRunSummaryReporter()
    ] // you can include the "StdoutReporter()" without the message level parameter for verbose log information
    ..hooks = [HookExample()]
    ..stepDefinitions = [GivenIPickAColour()]
    ..customStepParameterDefinitions = [ColourParameter()]
    // ..tagExpression = "@smoke" // uncomment to see an example of running scenarios based on tag expressions
    ..exitAfterTestRun = true; // set to false if debugging to exit cleanly
  return GherkinRunner().execute(config);
}
```

If I get time today I will give this a proper test.  Let me know how you get on.

**Comment by jonsamwell** [comment]
@kev52 how did you get on?
