### ISSUE TITLE
Hook error 

### ISSUE THREAD

**Issue by winqoo** [jonsamwell/flutter_gherkin#60]
I tried updating gherkin to :

flutter_gherkin: 1.1.8-rc.1 

but keep getting: 
`../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_gherkin-1.1.8-rc.1/lib/src/flutter/hooks/app_runner_hook.dart:51:16: Error: The method 'FlutterAppRunnerHook.onAfterScenarioWorldCreated' has fewer positional arguments than those of overridden method 'Hook.onAfterScenarioWorldCreated'.
  Future<void> onAfterScenarioWorldCreated(`

**Comment by jonsamwell** [comment]
Hi,

Yes v1.18-rc.1 is for the dev branches as the way the Flutter driver logs things is different from the stable branch.  The current main version v1.1.7+6 is for the stable branch.  It looks like the two branches have gotten out of sync so I will push the latest changes into the RC branch today

**Comment by jonsamwell** [comment]
Fixed in version 1.1.8-rc.2 https://pub.dev/packages/flutter_gherkin/versions/1.1.8-rc.2
