### ISSUE TITLE
Unhandled exception in GherkinRunner.execute

### ISSUE THREAD

**Issue by winqoo** [jonsamwell/flutter_gherkin#61]
@jonsamwell 

I changed dependencies to **1.1.8-rc.2** and right now an error occurs when running tests

> Unhandled exception:
Exception: Unknown runnable child given to Scenario 'TextLineRunnable'
#0      ScenarioRunnable.addChild (package:gherkin/src/gherkin/runnables/scenario.dart:33:9)
#1      GherkinParser._parseBlock (package:gherkin/src/gherkin/parser.dart:120:21)
#2      GherkinParser._parseBlock (package:gherkin/src/gherkin/parser.dart:109:15)
#3      GherkinParser.parseFeatureFile (package:gherkin/src/gherkin/parser.dart:55:7)
<asynchronous suspension> #4      GherkinRunner.execute (package:gherkin/src/test_runner.dart:47:43)
<asynchronous suspension>

and that's my test_main.dart 
>Future<void> main() {
  final config = FlutterTestConfiguration()
    ..features = [Glob("ui_tests/features/**.feature")]
    ..reporters = [
      ProgressReporter(),
      TestRunSummaryReporter(),
      JsonReporter(path: './report.json')
    ]
    ..stepDefinitions = [
      LoginScreenOpened(),
    ]
    ..reporters = [ProgressReporter(), TestRunSummaryReporter()]
    ..restartAppBetweenScenarios = true
    ..targetAppPath = "ui_tests/ui_main.dart"
    ..exitAfterTestRun = true;
  return GherkinRunner().execute(config);
}

and the step:

> class LoginScreenOpened extends GivenWithWorld<FlutterWorld> {
  @override
  Future<void> executeStep() async {
    await world.driver
        .waitFor(find.byValueKey(UiTestKeys.executeLoginUserNameKey));
    await world.driver
        .waitFor(find.byValueKey(UiTestKeys.executeLoginPasswordKey));
    await world.driver
        .waitFor(find.byValueKey(UiTestKeys.executeLoginButtonKey));
  }
  @override
  RegExp get pattern => RegExp(r"login screen opened");
}

**Comment by jonsamwell** [comment]
Hi,

This usually indicates a formating error in the feature file. Could you
provide the contents of the whole feature file that is causing this.

Thanks

**Comment by winqoo** [comment]
Hi,

> Feature: User login
@SUIT-74
Scenario: Login necessary
  Given user has not logged in before
   When user starts the app
   Then the login screen opens

**Comment by jonsamwell** [comment]
@winqoo that runs fine for me.  Is that the whole contents of the feature file?

If so could you provide a example where the error can be reproduced and I'll be able to get it sorted.

**Comment by winqoo** [comment]
@jonsamwell you are right, There were some old feature files. I removed them and now it work fine. Thanks for fast responses

**Comment by jonsamwell** [comment]
Great, feel free to put the content here - the error should be a bit more friendly tbh!
