### ISSUE TITLE
Executing Some Given Steps before app launches.

### ISSUE THREAD

**Issue by atmaramnaik** [jonsamwell/flutter_gherkin#62]
Right now the way app is initialised is by means of hook that is executed before any step executes.
Will it be possible to launch the app as one of step itself like 
Given I open my app
This would help for doing some steps that might be preparatory for scenario like data setup etc and would look more Gherkinish
e.g.
Given User with name "abc" exists (This step can ingest data or mock data before even app is launched)
When I Open App
I see user "abc" in members section
......

**Comment by jonsamwell** [comment]
Typically this is what the Background section of a feature is for.

```
Feature: User's book library
  Background: Pre-load account data
   Given a new user account
   And their book store is populated with the books
   | Title                               | Genre  |
   | Catch 22                        | satire   |
   | Rendezvous with Rama | scifi     |

  @scifi @satire
  Scenario: User's book library shows stored books
    Given I am logged in
    And I am on the book library page
   Then I see the books
   | Title                                | Genre  |
   | Catch 22                         | satire   |
   | Rendezvous with Rama  | scifi     |
```

There is a step that restarts an app so you could wrap this in another step and create the `When I open the app` step.

I think it is OK to have the test automatically open the app in this scenario as the tests cannot really control the phone they are targeted towards driving a Flutter app.  Unlike say cumcumberjs which is targeted at driver a whole web browser for instance.

**Comment by atmaramnaik** [comment]
Yes, i saw restarting option can now work as work around for this, also looking at the way World objects are . populated this might not be possible hence closing this.

**Comment by jonsamwell** [comment]
Yeah, I could give you the option to provide your own hook to manage running/restarting/stopping the flutter app under test (https://github.com/jonsamwell/flutter_gherkin/blob/master/lib/src/flutter/flutter_test_configuration.dart#L114).  I suppose if you don't provide it or just have an empty hook you could manage the app availability yourself.
