### ISSUE TITLE
Run test on device/emulator/simulator

### ISSUE THREAD

**Issue by Hsilgos** [jonsamwell/flutter_gherkin#63]
Hi,
we are extending our functionality to support flutter and our cucumber-based integration tests are planned also to move.
Unfortunately the example which is located in directory 'test_driver' is not able to run on device and seems that it can't do it as well as dart_gherkin can't.
Is there plans to move in this direction?

**Comment by jonsamwell** [comment]
What version of flutter are you using? If you are using anything other than
the stable channel you will have to use the latest rc version of the
library.  As the way flutter driver logs things changed in the latest code
from how it works in the stable channel.

Is this what you were asking? I'd not could you clarify your question?

Thanks

**Comment by Hsilgos** [comment]
@jonsamwell 
My flutter doctor:

> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G3020, locale en-DE)
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
> [✓] Android Studio (version 3.4)
> [✓] Android Studio (version 3.6)
> [!] IntelliJ IDEA Community Edition (version 2018.3.1)
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
>     ✗ Dart plugin not installed; this adds Dart specific functionality.
> [✓] Connected device (1 available)

I check out rc:
> git checkout 1.1.8-rc.2

Now i go to `examples`
and run `flutter drive --target=test_driver/app.dart`

I get an error:

> Compiler message:                                                       
> lib/main.dart:84:50: Error: The getter 'headline4' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline4'.
>               style: Theme.of(context).textTheme.headline4, 

Ok, i go to `lib/main.dart` and comment out string with  'headline4', run again I get new error:

> ../lib/src/flutter/reporters/flutter_driver_reporter.dart:28:5: Error: The setter 'driverLog' isn't defined for the class 'FlutterDriverReporter'.
>  - 'FlutterDriverReporter' is from 'package:flutter_gherkin/src/flutter/reporters/flutter_driver_reporter.dart' ('../lib/src/flutter/reporters/flutter_driver_reporter.dart').
> Try correcting the name to the name of an existing setter, or defining a setter or field named 'driverLog'.
>     driverLog = _driverLogMessageHandler;
>     ^^^^^^^^^
> ../lib/src/flutter/reporters/flutter_driver_reporter.dart:32:5: Error: The setter 'driverLog' isn't defined for the class 'FlutterDriverReporter'.
>  - 'FlutterDriverReporter' is from 'package:flutter_gherkin/src/flutter/reporters/flutter_driver_reporter.dart' ('../lib/src/flutter/reporters/flutter_driver_reporter.dart').
> Try correcting the name to the name of an existing setter, or defining a setter or field named 'driverLog'.
>     driverLog = null;
>     ^^^^^^^^^

I comment out those string as well, run again `flutter drive --target=test_driver/app.dart` and finally have error:

> Unhandled exception:
> FileSystemException: Directory listing failed, path = './features/' (OS Error: No such file or directory, errno = 2)
> #0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:39:68)
> #1      _Directory.listSync (dart:io/directory_impl.dart:251:5)
> #2      _ListTreeNode.listSync (package:glob/src/list_tree.dart:402:12)
> #3      _ListTreeNode.listSync.<anonymous closure> (package:glob/src/list_tree.dart:410:35)
> #4      ExpandIterator.moveNext (dart:_internal/iterable.dart:484:29)
> #5      ExpandIterator.moveNext (dart:_internal/iterable.dart:478:31)
> #6      new List.from (dart:core-patch/array_patch.dart:47:19)
> #7      Iterable.toList (dart:core/iterable.dart:400:5)
> #8      ListTree.listSync (package:glob/src/list_tree.dart:201:37)
> #9      Glob.listSync (package:glob/glob.dart:151:22)
> #10     GherkinRunner.execute (package:gherkin/src/test_runner.dart:43:31)
> #11     main (file:///here_av_excluded/flutter_gherkin/example/test_driver/app_test.dart:44:26)
> #12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
> #13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

Obviously because there is no files on device and all feature files must be inside assets. This error I don't know how to fix easily :)

**Comment by jonsamwell** [comment]
Looks like you are using the rc version and are on the stable branch. Use
the 1.7.6 latest version and it will work fine.

**Comment by Hsilgos** [comment]
You mean tag 1.1.7+6? Ok, I'll try it a bit later. I guess it may help only with first two problem, but I don't see how it can help with third one, most important... But I'll check, thanks.

**Comment by jonsamwell** [comment]
Make sure to are changing your root directory to example before running the
command. As per the readme in the example folder.

**Comment by jonsamwell** [comment]
@Hsilgos Further to point 3 you mention.  No files or anything related to the test are stored on the device under test.  The device under test is purely the app.  All test files are parsed and executed by a separate dart process on your local machine.  Therefore, if it is having trouble finding the files I would say the cwd for the process is wrong.

As per the Readme.md in the example folder to run the example follow the below comands

```
To run this example:

1. Ensure dart is accessible in the command line (on your path variable)
2. Ensure an emulator or device is connected
3. In a command prompt (from the root of this library):
    ```bash
    cd example/test_driver

    dart app_test.dart
    ```
This will run the features files found in the folder `test_driver/features` against this example app.
```

I hope this helps.  As per my previous comment make sure you are using the latest stable release 1.1.7+6

**Comment by Hsilgos** [comment]
> All test files are parsed and executed by a separate dart process on your local machine.

Hm... According to [documentation](https://flutter.dev/docs/testing#integration-tests):
> Generally, an integration test runs on a real device or an OS emulator, such as iOS Simulator or Android Emulator.

I read it like my test scenarios also running on device (not locally). [Cucumber-android](https://github.com/cucumber/cucumber-android) for Android and [Cucumberish](https://github.com/Ahmed-Ali/Cucumberish) for iOS both execute scenarios on device and I expected that flutter_gherkin should also behave like this. It's crucial for us. Unfortunately we need to invent something else (or invent how to adopt our tests for flutter_gherkin).

Thank your for clarification, issue can be closed I guess...

**Comment by jonsamwell** [comment]
@Hsilgos I think you have misunderstood a fundamental principle of testing, in that the object under test should be separate from the test otherwise you are introducing a host of complexity and additional variables if the item under test, tests itself.

The way this library works, Flutter driver and indeed other Gherkin based frameworks i.e. cucumberjs etc., is to driver an *instance* of the item under test and as such be separate from the thing they are testing.

The documentation is referring to a test driving a Flutter app (externally) **on** a real device or an emulator.  The Flutter Driver itself is a separate process that connects to the Flutter app under test via a RPC protocol and is then able to send the app commands to execute i.e. tap a button, get the text of a widget etc.  This is achieved via the Dart VM service Proctol (https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md).

Although this is not to say your tests feature files and Gherkin steps cannot sit in the same project as your app under a `test` folder.  However, having the tests as assets in the app would not be recommended practice and I cannot really think how this would work.  This library for instance would fire up an instance of the app under test, connect to it via flutter driver and execute the steps outlined in your feature files.  This has a host of benefits like modular reporting, speed, being able to run on CI servers as well as following best testing practices.

I think if you want to have the feature files within the app as assets and the app internally testing itself you will have to write something *completely bespoke*.  I think this will be incredibility difficult and I am sorry to say this fairly pointless.

I am happy to going into more detail about the internals of how this library, Flutter driver and most Gherkin implementation works if you would like to understand this better.

**Comment by Hsilgos** [comment]
@jonsamwell Well, modern approach to test mobile applications separates testing logic from tested as you told. It works perfect for UI applications and I understand it very well.

But in our case we want to test non-UI framework. And we need to test it on simulator/device, because we have C++ code in framework and bridging code between C++ and Java/Swift/Flutter.

We chose approach with cucumber because it guarantees that all our scenarios are tested on all platforms in the same way and we didn't miss anything. Moreover this approach helps to combine steps with small effort on Java/Swift side and it more or less 'natural' for CI infrastructure due to it works with XCTest and JUnit under the hood.

In our implementation of steps on Java/Swift we're creating objects of the framework, we're combining them, calling methods, receiving  results in async callbacks and so on and there is no any UI involved.

I don't have good experience in Flutter, do you think that it's possible to organise our tests with flutter_gherkin in the same way?

**Comment by jonsamwell** [comment]
@Hsilgos I will give this some thought but I can see what you would require now.  I think it would be possible to use the underlying dart gherkin library to do this in the app itself.

The dart_gherkin library is the core gherkin functionality and test runner without any of the flutter bits laid over the top.  So in essence it is just dart code that could be run from anywhere.

https://github.com/jonsamwell/dart_gherkin

See the actual test runner that can be invoked inline https://github.com/jonsamwell/dart_gherkin/blob/master/lib/src/test_runner.dart

That being said at the moment it relies on `path` and `glob` to read the file system to find the feature files (https://github.com/jonsamwell/dart_gherkin/blob/master/lib/src/test_runner.dart#L43).  I would be happy to work with you to remove this dependency and have some way of discovering feature files to parse and execute, be that from the file system or from an asset folder in a flutter app.

Perhaps fork this and do some experimentation to see if you can make it do what you want.

**Comment by Hsilgos** [comment]
Yeah, this is the first project which I found and only then I discovered flutter_gherkin.

Thank you for advice, I'll probably try to do this, but can't promise how soon. In any case it shouldn't be rocket science.

**Comment by jonsamwell** [comment]
Great, let me know how you get on
