### ISSUE TITLE
Is this package usable with flutter widget test?

### ISSUE THREAD

**Issue by zaralockheart** [jonsamwell/flutter_gherkin#65]
Is this package for driver tests only? Can I use this package to run widget tests instead of driver test?

**Comment by jonsamwell** [comment]
Hi @zaralockheart,

This package is specifically gear towards Flutter driver tests.  To test against widget please use https://github.com/jonsamwell/dart_gherkin (https://pub.dev/packages/gherkin).  The Flutter Gherkin library just wraps this core Gherkin library and provides some driver specific functionality.

**Comment by zaralockheart** [comment]
Hi @jonsamwell thank you for clarifying. I wanted to ask how do I pump widget with https://github.com/jonsamwell/dart_gherkin as the sample is using a normal class instead of flutter widget. I'll open an issue there.
