### ISSUE TITLE
[web] flutter integration test

### ISSUE THREAD

**Issue by phamnhuvu-dev** [jonsamwell/flutter_gherkin#66]
https://github.com/flutter/flutter/issues/55694
## Steps to Reproduce

I follow this https://flutter.dev/docs/cookbook/testing/integration/introduction#6b-web

I run this command `flutter drive --target=test_driver/app.dart --browser-name=chrome -d chrome --release`

**Expected results:** 
Can run integration test for web.

**Actual results:** 
```
flutter drive --target=test_driver/app.dart --browser-name=chrome -d chrome --release
Starting application: test_driver/app.dart
Launching test_driver/app.dart on Chrome in release mode...
Compiling test_driver/app.dart for the Web...                       3.9s
Application finished.
Starting Flutter app under test 'test_driver/app.dart', this might take a few moments
Invoking from working directory `./` command: `flutter run --target=test_driver/app.dart --device-id=chrome`
Launching test_driver/app.dart on Chrome in debug mode...
Syncing files to device Chrome...                               
Compiler message:



Flutter build error: org-dartlang-app:///web_entrypoint.dart:4:8: Error: Error when reading 'org-dartlang-app:///null': File not found
import "null";
       ^

Flutter build error: org-dartlang-app:///web_entrypoint.dart:6:3: Error: Method not found: 'registerPlugins'.


registerPlugins(webPluginRegistry);
  ^^^^^^^^^^^^^^^
Syncing files to device Chrome...                               34,383ms (!)
Flutter build error: Failed to compile application.
Stopping application instance.

```

<details>
  <summary>Logs</summary>

```
flutter devices
2 connected devices:

Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.122
Web Server • web-server • web-javascript • Flutter Tools
```

```
[✓] Flutter (Channel beta, v1.17.0-3.2.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.17.0-3.2.pre at /home/phamnhuvu/Downloads/flutter_linux_v1.12.13+hotfix.9-stable/flutter
    • Framework revision 2a7bc389f2 (5 days ago), 2020-04-21 20:34:20 -0700
    • Engine revision 4c8c31f591
    • Dart version 2.8.0 (build 2.8.0-dev.20.10)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/phamnhuvu/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/phamnhuvu/Downloads/android-studio-ide-192.6392135-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /home/phamnhuvu/Downloads/android-studio-ide-192.6392135-linux/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.122
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

</details>

**Comment by phamnhuvu-dev** [comment]
Now I just use [gherkin](https://pub.dev/packages/gherkin) with Flutter driver, stop us [flutter_gherkin](https://pub.dev/packages/flutter_gherkin)

**Comment by jonsamwell** [comment]
@phamnhuvu-dev sorry for the late reply.  I need to spend time getting this library working for the flutter web but for now using the base gherkin library is a good work around.  I'll re-open this issue until the library supports flutter web.

**Comment by pripriya2** [comment]
@jonsamwell Hi, Is there any update on this? When will this support come?

**Comment by jonsamwell** [comment]
No update unfortunately. I just haven't had time to look at this but it is
on the roadmap. Any help would be appreciated.

**Comment by phamnhuvu-dev** [comment]
https://github.com/flutter/flutter/wiki/Running-Flutter-Driver-tests-with-Web
@jonsamwell I see you create a Processer in the code, so it is hard when the command line from flutter is changed. So anyway can run the BDD with `flutter drive` command line?

**Comment by jonsamwell** [comment]
This will be supported soon when the support to integration_test package arrives shortly

**Comment by phamnhuvu-dev** [comment]
@jonsamwell.
It is ok guy. I am combining your gherkin package and flutter driver and it is working well on Android, iOS and Web for integration test.
I am also testing the integration_test package, then apply it for our project.

And Happy Lunar New Year.

**Comment by jonsamwell** [comment]
Ah great I'm glad your testing the new integration_test migration of this project.  Let me know how if goes and if you have any thoughts.  I've got it successfully working with two very large apps and it is working well.

Happy Lunar New Year too!

**Comment by jonsamwell** [comment]
All see the new relesase https://pub.dev/packages/flutter_gherkin/versions/3.0.0-rc.1 .  I need to do the documentation but the code is working very well.  Feedback welcome
