### ISSUE TITLE
Cucumber-Ruby style step definitions

### ISSUE THREAD

**Issue by UTRGV-SOMEDW** [jonsamwell/flutter_gherkin#68]
Just curious, I'm new to Dart - coming from a Ruby background.
Found this package by looking for a Cucumber-style BDD framework in Flutter.

In Cucumber-Ruby writing step definitions is pretty simple:
```
When("I visit the homepage") do
   something
end
```

is it possible to have this style step definition in `flutter_gherkin` ?

I imagine it could look something like:

```
When("I visit the homepage", (){
    something
});
```

**Comment by jonsamwell** [comment]
@UTRGV-SOMEDW sorry I have taken so long to get back to you!  There are a number of reason the library cannot do exactly like above and the favoured approach up until now has been to create classes.  Primary the lack of reflection and code inclusion in the runtime i.e. without referencing a class it is not always included once compiled so the code could not be found even via runtime reflection. 

I have recently added help functions that simulate what you are after.  So for a simple test the code is quite minimal.

```
import 'package:gherkin/gherkin.dart';

StepDefinitionGeneric GoToHomePage() {
  return when(
    'I visit the homepage',
    (context) async {
     // do something here
    },
  );
}
```

Note that the function `GoToHomePage` still has to be included in the step declaration parameter of the configuration for the reasons noted above.

```
Future<void> main() {
  final steps = [
    TapButtonNTimesStep(),
    GoToHomePage(),
  ];

  final config = FlutterTestConfiguration.DEFAULT(
    steps,
    featurePath: 'features//**.feature',
    targetAppPath: 'test_driver/app.dart',
  );

  return GherkinRunner().execute(config);
}
```

You can also specify parameters and their types in the function, as well as the type of World object you might have.  The world object is available via the context object.

```
StepDefinitionGeneric ThenExpectElementToHaveValue() {
  return given2<String, String, FlutterWorld>(
    RegExp(r'I expect the {string} to be {string}$'),
    (key, value, context) async {
      final text = await FlutterDriverUtils.getText(
          context.world.driver,
          find.byValueKey(key),
        );
     context.expect(text, value);
    },
  );
}
```

I hope this is a step in the right direction to making it a bit easier to get going with this library.

Please let me know your thoughts
