### ISSUE TITLE
If data is heavy showing cucumber report is showing "TypeError: Cannot read property 'forEach' of undefined." error

### ISSUE THREAD

**Issue by GarimaVats** [jonsamwell/flutter_gherkin#69]
After running my all feature files which are now 20 ( approx 1500 steps), when I am executing command **node test_driver/cucumber_reporter.js**, I am facing **TypeError: Cannot read property 'forEach' of undefined**. While if I am running one feature file report is being generated.

**Comment by jonsamwell** [comment]
Hi @GarimaVats could you provide the js code you are using and the json report.

**Comment by GarimaVats** [comment]
var reporter = require('cucumber-html-reporter');

var options = {
        theme: 'bootstrap',
        jsonFile: 'test_driver/main_tests/test_report.json',
        output: 'test_driver/main_tests/cucumber_report.html',
        reportSuiteAsScenarios: true,
        scenarioTimestamp: true,
        launchReport: true,
        metadata: {
            "App Version":"0.3.2",
            "Test Environment": "Dev",
            "Device": "iOS/Android",
            "Platform": "MAC",
            "Parallel": "Scenarios",
            "Executed": "Local"
        }
    };

reporter.generate(options);

**Comment by jonsamwell** [comment]
@GarimaVats could you provide the test_report.json that makes this fail?

**Comment by GarimaVats** [comment]
It is very big size. when I copied it on word , it is showing 772 pages which is out of limit of this comment box. I believe big size of this report is issue. As I noticed if I am running only smoke tagged test, it is working fine. Again copy below error:/

Users/xyz/node_modules/cucumber-reporter/lib/reporter.js:236
                element.steps.forEach(function (step, count) {
                              ^

TypeError: Cannot read property 'forEach' of undefined

**Comment by GarimaVats** [comment]
I got the solution of it , I do below changes into reporter.js then its working fine for me

                **if (element.steps == undefined) {
                    return;
                }**

                element.steps.forEach(function (step, count) {
                    if (step.embeddings !== undefined) {
                        step.embeddings.forEach(function (embedding) {

but I am not able to checkin this into my git branch , so if you add this solution into your code so it will be helpful for me , so I can take latest version

**Comment by jonsamwell** [comment]
@GarimaVats the repository does not have an JavaScript code?

**Comment by GarimaVats** [comment]
This file is not part of our source code. This library is downloaded separately. Could you do code change in github of your library.

**Comment by jonsamwell** [comment]
@GarimaVats sorry I am not sure what change you want me to make?

**Comment by GarimaVats** [comment]
I debugged the java script, actually reason of that issue was , by mistake for one test scenario I commented out test steps only (Given, when ...then). Due to which exception was occur. Now I am closing this.
