### ISSUE TITLE
requestData() custom command doesn't work with gherkin in FlutterDriver, is there any alternate way

### ISSUE THREAD

**Issue by sohitEngg** [jonsamwell/flutter_gherkin#72]
I'm using flutter_gherkin for BDD test on my flutter Application. Recently I have a requirement in which I need to clear cache(SharePreference) for some scenarios so I have chosen to send custom command to my application. Here below is the code:

await world.driver.requestData("deleteChache");

and I am expecting the command in the main.dart in test environment as per below:

void main() { enableFlutterDriverExtension(handler: (message) async { stdout.write('##message received $message'); await app.deleteCache(); return null; }); app.main(); }

I am able to see the logs for sending part but there is no logs found for receiving part, looks like flutter driver is unable send the command to my App. Am I missing anything, is this because of gherkin environment?

Please Note that everything is working with Integration provided flutter, it is a problem that I am facing with gherkin integration.
Can you please check if it can be resolved, I can not move back to flutter integration at this moment?
Here is the reference link: https://github.com/flutter/flutter/issues/59047 which has been closed because it is not caused by flutter but third party library (gherkin).

Thanks in advance.

**Comment by jonsamwell** [comment]
Hi, the definitely works as I am doing this myself.

Can you give me a reproducing code sample of how you are doing it?

Please see the below link for a working sample of how I do it:


https://github.com/jonsamwell/flutter_gherkin/issues/46#issuecomment-584462881

**Comment by jonsamwell** [comment]
Also please note that you will not see the logs printed of the application
under test as this is a separate process from the actual testing process
and the do not share standard outs.  So I think this is your issue.

To confirm it is working I would return a string from the handler in the
test app that handles the request data call from the gherkin test step.
Then in the gherkin test step you can print the result.

You can however debug the application being tested please see
https://github.com/jonsamwell/flutter_gherkin/blob/master/README.md#debugging-the-app-under-test

**Comment by jonsamwell** [comment]
Closing from lack of response
