### ISSUE TITLE
When I put "And I tap the back button" so I receive this error: GenericFunctionStepDefinition<FlutterWorld> parameter count mismatch. Expect 1 parameters but got 0. Ensure you are extending the correct step class which would be Given

### ISSUE THREAD

**Issue by lukasgarcya** [jonsamwell/flutter_gherkin#76]
I think in this error is conflict with "I tap the {string} [button|element|label|icon|field|text|widget]"

**Comment by jonsamwell** [comment]
Thanks for reporting this - I have fixed it and added a test to cover this.  Fix is available in version https://pub.dev/packages/flutter_gherkin/versions/1.1.8+4
