### ISSUE TITLE
Long tap implementation

### ISSUE THREAD

**Issue by MounicaGit** [jonsamwell/flutter_gherkin#78]
How to implement a long tap using flutter_gherkin package?

**Comment by jonsamwell** [comment]
@MounicaGit I have added a new set of pre-defined steps that will help you achieve this

```
When I long press "controlKey" button

When I long press "controlKey" icon for 1500 milliseconds
```

Alternatively, you can use the util method to do it in a custom step (https://github.com/jonsamwell/flutter_gherkin/blob/master/lib/src/flutter/utils/driver_utils.dart#L73)

```
await FlutterDriverUtils.longPress(
        context.world.driver,
        finder,
        pressDuration: Duration(milliseconds: milliseconds),
      );
```

**Comment by MounicaGit** [comment]
Thank you @jonsamwell

**Comment by jonsamwell** [comment]
No problem!
