### ISSUE TITLE
identify the color of a widget 

### ISSUE THREAD

**Issue by MounicaGit** [jonsamwell/flutter_gherkin#79]
Is there any way to get the color of the widget using flutter_gherkin package?

**Comment by jonsamwell** [comment]
@MounicaGit I am afraid the Flutter driver does not support this.  Please fill a bug with the Flutter team for this

**Comment by nandhini0761** [comment]
Is there any way to get the color of the widget using flutter driver?

**Comment by jonsamwell** [comment]
@nandhini0761 I am afraid the Flutter driver does not support this. Please fill a bug with the Flutter team for this
