### ISSUE TITLE
Error: The method 'runZonedGuarded' isn't defined for the class 'FlutterTestConfiguration'.

### ISSUE THREAD

**Issue by ahmadvicky** [jonsamwell/flutter_gherkin#82]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en-ID)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

I tried running the application. i got message

 "Error: The method 'runZonedGuarded' isn't defined for the class 'FlutterTestConfiguration'.
 - 'FlutterTestConfiguration' is from 'package:flutter_gherkin/src/flutter/flutter_test_configuration.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/flutter_gherkin-1.1.8+8/lib/src/flutter/flutter_test_configuration.dart').
Try correcting the name to the name of an existing method, or defining a method named 'runZonedGuarded'."

**Comment by DouglasDao** [comment]
@ahmadvicky - I am also facing the same issue

**Comment by jonsamwell** [comment]
@DouglasDao what version of flutter are you using?

**Comment by DouglasDao** [comment]
@jonsamwell - Thanks for the reply. Issue was resolved. I was using old dart SDK so, once I update to latest version 2.9.3 version issue was resolved.

@ahmadvicky - You can try this just ensure are you using latest dart-sdk.

**Comment by jonsamwell** [comment]
Great!
