### ISSUE TITLE
How to mock (stub) api data in gherkin

### ISSUE THREAD

**Issue by 3lVv0w** [jonsamwell/flutter_gherkin#87]
is there any way to do without using [flutter_gherkin_addons](https://pub.dev/packages/flutter_gherkin_addons) ? and can you provide the example on that

**Comment by jonsamwell** [comment]
Hi @3lVv0w 

There isn't really a standard way of doing it and opinions might vary.  Personally I don't see much point in mock out data in end to end tests as that is really the point; testing the system as a whole.

We always have a test and production environments and target the Flutter build using flavours so we do not suffer from test data pollution in our production environments.

If you did want to mock it out though I would suggest using the custom data messages (see my comment https://github.com/jonsamwell/flutter_gherkin/issues/46#issuecomment-584462881 for a nice way of doing this) to tell the app to get data from a different source or mock it.

What is the scenario you have and want to achieve?

**Comment by jonsamwell** [comment]
Closing but feel free to re-open if the above does not resolve the issue
