### ISSUE TITLE
Assertions are missing in readme

### ISSUE THREAD

**Issue by vrnvorona** [jonsamwell/flutter_gherkin#89]
Well, Title. It seems you've intended to ass examples of assertions usage, but it's empty. WorldContext too.

**Comment by jonsamwell** [comment]
Thanks for noticing this - I'll try and find some time to update it although it is the same as the normal `expect` functionality

**Comment by vrnvorona** [comment]
Yeah, context.expect, took it from already-implemented-steps.

**Comment by jonsamwell** [comment]
Fixed in latest v1.1.9 release
