### ISSUE TITLE
Fail in final of test

### ISSUE THREAD

**Issue by lukasgarcya** [jonsamwell/flutter_gherkin#92]
Starting Flutter app under test 'test_driver/app.dart', this might take a few moments
before run hook
VMServiceFlutterDriver Connecting to Flutter application at http://127.0.0.1:38445/ScaIiPjZCT0=/
VMServiceFlutterDriver Isolate found with number: 3682545693255519
VMServiceFlutterDriver Isolate is not paused. Assuming application is ready.
VMServiceFlutterDriver Connected to Flutter application.
running hook before scenario 'counter should reset when app is restarted'
[33;10mRunning scenario: counter should reset when app is restarted # ./features/app_restart.feature:2[33;0m
[33;32m   √ Given I expect the "counter" to be "0" # ./features/app_restart.feature:3 took 108ms[33;0m
[33;32m   √ When I tap the "increment" button # ./features/app_restart.feature:4 took 472ms[33;0m
[33;32m   √ Then I expect the "counter" to be "1" # ./features/app_restart.feature:5 took 118ms[33;0m
VMServiceFlutterDriver Connecting to Flutter application at http://127.0.0.1:38445/ScaIiPjZCT0=/
VMServiceFlutterDriver Isolate found with number: 778646431923143
VMServiceFlutterDriver Isolate is not paused. Assuming application is ready.
VMServiceFlutterDriver Connected to Flutter application.
[33;32m   √ When I restart the app # ./features/app_restart.feature:6 took 3344ms[33;0m
[33;32m   √ Then I expect the "counter" to be "0" # ./features/app_restart.feature:7 took 146ms[33;0m
[33;32mPASSED: Scenario counter should reset when app is restarted # ./features/app_restart.feature:2[33;0m
Restarting Flutter app under test
running hook after scenario 'counter should reset when app is restarted'
VMServiceFlutterDriver Connecting to Flutter application at http://127.0.0.1:38445/ScaIiPjZCT0=/
Error waiting for no transient callbacks from Flutter driver:

`Failed assertion: boolean expression must not be null`

#0      VMServiceFlutterDriver.sendCommand (package:flutter_driver/src/driver/vmservice_driver.dart:351:29)
<asynchronous suspension>
#1      FlutterDriver.waitUntilNoTransientCallbacks (package:flutter_driver/src/driver/driver.dart:230:11)
#2      FlutterWorld._closeDriver (package:flutter_gherkin/src/flutter/flutter_world.dart:49:14)
#3      FlutterWorld.dispose (package:flutter_gherkin/src/flutter/flutter_world.dart:40:11)
#4      FeatureFileRunner._runScenario (package:gherkin/src/feature_file_runner.dart:276:16)
<asynchronous suspension>
#5      FeatureFileRunner._runScenarioInZone.<anonymous closure> (package:gherkin/src/feature_file_runner.dart:142:30)
#6      _rootRun (dart:async/zone.dart:1190:13)
#7      _CustomZone.run (dart:async/zone.dart:1093:19)
#8      _runZoned (dart:async/zone.dart:1630:10)
#9      runZonedGuarded (dart:async/zone.dart:1618:12)
#10     runZoned (dart:async/zone.dart:1547:12)
#11     FeatureFileRunner._runScenarioInZone (package:gherkin/src/feature_file_runner.dart:140:5)
#12     FeatureFileRunner._runFeature (package:gherkin/src/feature_file_runner.dart:74:21)
<asynchronous suspension>
#13     FeatureFileRunner.run (package:gherkin/src/feature_file_runner.dart:41:38)
#14     GherkinRunner.execute (package:gherkin/src/test_runner.dart:86:45)
<asynchronous suspension>
#15     main (file:///home/lukasgarcya/VisualStudioCodeProjects/flutter_gherkin/example/test_driver/app_test.dart:40:26)
#16     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

VMServiceFlutterDriver Isolate found with number: 483803094991227
VMServiceFlutterDriver Isolate is not paused. Assuming application is ready.
VMServiceFlutterDriver Connected to Flutter application.
running hook before scenario 'User can navigate back from page two'
[33;10mRunning scenario: User can navigate back from page two # ./features/back_navigation.feature:3[33;0m
[33;32m   √ Given I expect the "counter" to be "0" # ./features/back_navigation.feature:4 took 123ms[33;0m
[33;32m   √ When I tap the "increment" button # ./features/back_navigation.feature:5 took 394ms[33;0m
[33;32m   √ Then I expect the "counter" to be "1" # ./features/back_navigation.feature:6 took 63ms[33;0m
[33;32m   √ Given I tap the label that contains the text "Open page 2" # ./features/back_navigation.feature:8 took 396ms[33;0m
[33;32m   √ Then I expect the text "Contents of page 2" to be present # ./features/back_navigation.feature:9 took 67ms[33;0m
[33;32m   √ Given I tap the back button # ./features/back_navigation.feature:11 took 384ms[33;0m
[33;32m   √ Then I expect the "counter" to be "1" # ./features/back_navigation.feature:12 took 98ms[33;0m
[33;32mPASSED: Scenario User can navigate back from page two # ./features/back_navigation.feature:3[33;0m
Restarting Flutter app under test
running hook after scenario 'User can navigate back from page two'
VMServiceFlutterDriver Connecting to Flutter application at http://127.0.0.1:38445/ScaIiPjZCT0=/
Error waiting for no transient callbacks from Flutter driver:

`Failed assertion: boolean expression must not be null`

**Comment by lukasgarcya** [comment]
I tested in other notebook that I see the same error.

**Comment by jonsamwell** [comment]
@lukasgarcya what command are you using to run the tests?

**Comment by quan-codemetrics** [comment]
@jonsamwell I run dart app_test.dart and I get the error after every scenario. 
![image](https://user-images.githubusercontent.com/70996524/98502891-d08f9e80-2285-11eb-90d6-fd68e24da105.png)
Thank you for your effort in fixing this.

**Comment by lukasgarcya** [comment]
I run in Visual Studio Code and flutter drive --target=test_driver/app.dart

**Comment by jonsamwell** [comment]
Does this actually make the test fail or just print the error message

**Comment by lukasgarcya** [comment]
The test is running without error. After tests I receive this problem mentioned.

**Comment by jonsamwell** [comment]
Can you please see if the error is still present using this branch https://github.com/jonsamwell/flutter_gherkin/tree/close-driver-error-fix

**Comment by lukasgarcya** [comment]
@jonsamwell is working with this branch close-driver-error-fix.

**Comment by jonsamwell** [comment]
Great, I'll get this merged in a published tomorrow

**Comment by jonsamwell** [comment]
Fixed in latest v1.1.9 release
