### ISSUE TITLE
How to translate pattern to other language for functional step?

### ISSUE THREAD

**Issue by comerc** [jonsamwell/flutter_gherkin#94]
I have functional step in alient package, like this:
```dart
StepDefinitionGeneric ThenWaitForFlutter() {
  return then<FlutterWorld>(
    'I wait for Flutter',
    (StepContext<FlutterWorld> context) async {
      await FlutterDriverUtils.waitForFlutter(context.world.driver);
    },
  );
}
```
I want reuse it with other language, like the class step. For example: 
```dart
class ThenWaitForFlutter extends ThenWithWorld<FlutterWorld> {
  @override
  Future<void> executeStep() async {
    await FlutterDriverUtils.waitForFlutter(world.driver);
  }

  @override
  RegExp get pattern => RegExp(r"I wait for Flutter");
}

class ThenWaitForFlutterRu extends ThenWaitForFlutter {
  @override
  RegExp get pattern => RegExp(r"Я ожидаю Flutter");
}
```

**Comment by jonsamwell** [comment]
@comerc I have never considered a step could have translations i.e. multiple pattern.

I will consider this and perhaps provide a translation property on a step so it can be matched when running in languages other than English.  For now you will have to add the seconds step `ThenWaitForFlutterRu` to the `stepDefinitions` property on the configuration object.

See https://github.com/jonsamwell/flutter_gherkin#languages for creating features in different languages

**Comment by comerc** [comment]
I want to reuse original functional step. Like this example (if pattern will be allow setter):

```dart
StepDefinitionGeneric ThenWaitForFlutter() {
  return then<FlutterWorld>(
    'I wait for Flutter',
    (StepContext<FlutterWorld> context) async {
      await FlutterDriverUtils.waitForFlutter(context.world.driver);
    },
  );
}

StepDefinitionGeneric ThenWaitForFlutterRu() {
  final step = ThenWaitForFlutter();
  step.pattern = 'Я ожидаю Flutter';
  return step;
}
```

**Comment by jonsamwell** [comment]
Why not do something like this

```
StepDefinitionGeneric ThenWaitForFlutter(RegExp pattern = 'I wait for Flutter') {
  return then<FlutterWorld>(
    pattern,
    (StepContext<FlutterWorld> context) async {
      await FlutterDriverUtils.waitForFlutter(context.world.driver);
    },
  );
}

StepDefinitionGeneric ThenWaitForFlutterRu() {
  return ThenWaitForFlutter('Я ожидаю Flutter');
}
```

**Comment by comerc** [comment]
> Why not do something like this

I want to reuse "alient" steps. For example:

https://github.com/jonsamwell/flutter_gherkin/blob/master/lib/src/flutter/steps/restart_app_step.dart

**Comment by jonsamwell** [comment]
Ah, I seem what you mean.  I think the ultimate answer is to do this via translations.  If you translate all of those common steps I will get these translations in place.

For instance this would become

```
StepDefinitionGeneric RestartAppStep() {
  return given<FlutterWorld>(
    {
      'en': 'I restart the app',
      'ru': 'Я ожидаю Flutter',
   }
    (context) async {
      await context.world.restartApp(
        timeout: context.configuration?.timeout,
      );
    },
  );
}
```

In the meantime your only option would be to wrap these steps in steps with Russian patterns I am afraid.  I will get this in early next week though if you provide the translations

**Comment by comerc** [comment]
I don't want to bother the author of someone else's library every time I need a translation. I want to be able to add translations myself via pattern. :)

**Comment by comerc** [comment]
See first message again. :)

**Comment by jonsamwell** [comment]
OK, I'll have a think here, at a guess I'll have to provide a mapping from step pattern to the step code in the config object that can be overridden with different translations.  Although I think I favour just getting the Russian translations for these steps and doing it a proper way.  

I'll have a think and get back to you

**Comment by comerc** [comment]
https://github.com/jonsamwell/dart_gherkin/pull/18/commits/064861bb8b1bd875788d583af47255b62c7bb932

See pull request :)

**Comment by jonsamwell** [comment]
@comerc I don't think this is the solution to pattern problem you are having. Steps should be immutable and allowing them to mutate the pattern would be bad

**Comment by jonsamwell** [comment]
@comerc are you able to provide translations to the built in steps?
