### ISSUE TITLE
Tag negation not working as expected

### ISSUE THREAD

**Issue by sayadzad** [jonsamwell/flutter_gherkin#97]
Hi, when trying to use a tag expression such as `not @skip` I get the following exception:

```dart
Unhandled exception:
Bad state: No element
#0      ListQueue.removeFirst (dart:collection/queue.dart:758:25)
#1      TagExpressionEvaluator._evaluateRpn (package:gherkin/src/gherkin/expressions/tag_expression.dart:56:31)
#2      TagExpressionEvaluator.evaluate (package:gherkin/src/gherkin/expressions/tag_expression.dart:28:13)
#3      FeatureFileRunner._canRunScenario (package:gherkin/src/feature_file_runner.dart:123:35)
#4      FeatureFileRunner._runFeature (package:gherkin/src/feature_file_runner.dart:72:13)
<asynchronous suspension>
#5      FeatureFileRunner.run (package:gherkin/src/feature_file_runner.dart:41:38)
#6      GherkinRunner.execute (package:gherkin/src/test_runner.dart:86:45)
<asynchronous suspension>
```

I believe that the syntax allows for having these type of one-sided conditionals.

**Comment by jonsamwell** [comment]
@sayadzad are you able to provide a reproducing example.  I have just tried a single negated tag expression and it works as expected.  Are you perhaps not using a join when chaining conditional i.e. `@smoke and not @skip`?

**Comment by sayadzad** [comment]
@jonsamwell appreciate the fast reply and sorry for my late reply!

Sorry for the confusion, but what I meant was literally a tag expression being `not @skip`. This would ignore any tests with the tag `@skip`:

`..tagExpression = "not @skip"`

I believe the syntax allows for it, but I could be mistaken: https://cucumber.io/docs/cucumber/api/#ignoring-a-subset-of-scenarios. It definitely is an optional feature, but I can see it being useful. Let me know if you want more clarity.

**Comment by jonsamwell** [comment]
@sayadzad this already works, are you able to do up a small example of this not working?

**Comment by jonsamwell** [comment]
@sayadzad any update?

**Comment by jonsamwell** [comment]
Closing due to lack of response and it is working locally and when testing.  Feel free to reopen with more detail
